# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /tmp/yakut-dsdl-zmn42v0l/public_regulated_data_types-master/reg/drone/physics/kinematics/rotation/Planar.0.1.uavcan
#
# Generated at:  2021-09-29 15:15:52.658298 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     reg.drone.physics.kinematics.rotation.Planar
# Version:       0.1
#
# pylint: skip-file

from __future__ import annotations
import numpy as _np_
import typing as _ty_
import pydsdl as _pydsdl_
import pyuavcan.dsdl as _dsdl_
import uavcan.si.unit.angle
import uavcan.si.unit.angular_acceleration
import uavcan.si.unit.angular_velocity


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Planar_0_1(_dsdl_.CompositeObject):
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 angular_position:     _ty_.Optional[uavcan.si.unit.angle.Scalar_1_0] = None,
                 angular_velocity:     _ty_.Optional[uavcan.si.unit.angular_velocity.Scalar_1_0] = None,
                 angular_acceleration: _ty_.Optional[uavcan.si.unit.angular_acceleration.Scalar_1_0] = None) -> None:
        """
        reg.drone.physics.kinematics.rotation.Planar.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param angular_position:     uavcan.si.unit.angle.Scalar.1.0 angular_position
        :param angular_velocity:     uavcan.si.unit.angular_velocity.Scalar.1.0 angular_velocity
        :param angular_acceleration: uavcan.si.unit.angular_acceleration.Scalar.1.0 angular_acceleration
        """
        self._angular_position:     uavcan.si.unit.angle.Scalar_1_0
        self._angular_velocity:     uavcan.si.unit.angular_velocity.Scalar_1_0
        self._angular_acceleration: uavcan.si.unit.angular_acceleration.Scalar_1_0

        if angular_position is None:
            self.angular_position = uavcan.si.unit.angle.Scalar_1_0()
        elif isinstance(angular_position, uavcan.si.unit.angle.Scalar_1_0):
            self.angular_position = angular_position
        else:
            raise ValueError(f'angular_position: expected uavcan.si.unit.angle.Scalar_1_0 '
                             f'got {type(angular_position).__name__}')

        if angular_velocity is None:
            self.angular_velocity = uavcan.si.unit.angular_velocity.Scalar_1_0()
        elif isinstance(angular_velocity, uavcan.si.unit.angular_velocity.Scalar_1_0):
            self.angular_velocity = angular_velocity
        else:
            raise ValueError(f'angular_velocity: expected uavcan.si.unit.angular_velocity.Scalar_1_0 '
                             f'got {type(angular_velocity).__name__}')

        if angular_acceleration is None:
            self.angular_acceleration = uavcan.si.unit.angular_acceleration.Scalar_1_0()
        elif isinstance(angular_acceleration, uavcan.si.unit.angular_acceleration.Scalar_1_0):
            self.angular_acceleration = angular_acceleration
        else:
            raise ValueError(f'angular_acceleration: expected uavcan.si.unit.angular_acceleration.Scalar_1_0 '
                             f'got {type(angular_acceleration).__name__}')

    @property
    def angular_position(self) -> uavcan.si.unit.angle.Scalar_1_0:
        """
        uavcan.si.unit.angle.Scalar.1.0 angular_position
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._angular_position

    @angular_position.setter
    def angular_position(self, x: uavcan.si.unit.angle.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.angle.Scalar_1_0):
            self._angular_position = x
        else:
            raise ValueError(f'angular_position: expected uavcan.si.unit.angle.Scalar_1_0 got {type(x).__name__}')

    @property
    def angular_velocity(self) -> uavcan.si.unit.angular_velocity.Scalar_1_0:
        """
        uavcan.si.unit.angular_velocity.Scalar.1.0 angular_velocity
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._angular_velocity

    @angular_velocity.setter
    def angular_velocity(self, x: uavcan.si.unit.angular_velocity.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.angular_velocity.Scalar_1_0):
            self._angular_velocity = x
        else:
            raise ValueError(f'angular_velocity: expected uavcan.si.unit.angular_velocity.Scalar_1_0 got {type(x).__name__}')

    @property
    def angular_acceleration(self) -> uavcan.si.unit.angular_acceleration.Scalar_1_0:
        """
        uavcan.si.unit.angular_acceleration.Scalar.1.0 angular_acceleration
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._angular_acceleration

    @angular_acceleration.setter
    def angular_acceleration(self, x: uavcan.si.unit.angular_acceleration.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.angular_acceleration.Scalar_1_0):
            self._angular_acceleration = x
        else:
            raise ValueError(f'angular_acceleration: expected uavcan.si.unit.angular_acceleration.Scalar_1_0 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: Planar_0_1._SerializerTypeVar_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.angular_position._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.angular_velocity._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.angular_acceleration._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 96 <= (_ser_.current_bit_length - _base_offset_) <= 96, \
            'Bad serialization of reg.drone.physics.kinematics.rotation.Planar.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: Planar_0_1._DeserializerTypeVar_) -> Planar_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "angular_position"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.si.unit.angle.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "angular_velocity"
        _des_.pad_to_alignment(8)
        _f1_ = uavcan.si.unit.angular_velocity.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f2_ holds the value of "angular_acceleration"
        _des_.pad_to_alignment(8)
        _f2_ = uavcan.si.unit.angular_acceleration.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = Planar_0_1(
            angular_position=_f0_,
            angular_velocity=_f1_,
            angular_acceleration=_f2_)
        _des_.pad_to_alignment(8)
        assert 96 <= (_des_.consumed_bit_length - _base_offset_) <= 96, \
            'Bad deserialization of reg.drone.physics.kinematics.rotation.Planar.0.1'
        assert isinstance(self, Planar_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'angular_position=%s' % self.angular_position,
            'angular_velocity=%s' % self.angular_velocity,
            'angular_acceleration=%s' % self.angular_acceleration,
        ])
        return f'reg.drone.physics.kinematics.rotation.Planar.0.1({_o_0_})'

    _EXTENT_BYTES_ = 12

    _MODEL_: _pydsdl_.StructureType = _dsdl_.CompositeObject._restore_constant_(
        'ABzY8D1%gC0{^{L>u(!H5O<+znzlfr7LcF<!-q6Ha%Vesa3mz6M1&8fZb%?}s<wM~8_z0td&lmc6<1WELZC!iiAr5QBJrm(d*@dk'
        'CK8WYvNSg{J3I6H&FuVi_4oaSO7S!AXM;#Zu}2h>oW}eK4PxezFio;lam}oGZBNTQ)VXBe4l-t6*pHssr*_%Q5kV8Qe=1qei)1R8'
        'm%%{sP<e-3u!L$S%2cC}3U4Q-f=X+ylRlFQH5Mvnet#&xu$@Zh%CGjBH8%;>TJj**OxZ_x(To(wUe?TQa~4OF)NYW7YD%=r7hWlq'
        'FlXM)X+NaGQ{2l1*B%u;473;07!!keSm<2oR9p^l>yd@q!*h3LC6Gy;aLxOez`}N%Qhgeqn<U_x#7y)w*iIFb3aQd0Nh3_^o_T9$'
        'ble^Dw$S##nH&<o*j;Px5~Zn#sEnoq9b=q?_AvcCau**+8ajLxBD+15F^0Ln+N?F&jn(Gb+G@MiXt!JI?Rx#QTC?6>ZMK`O`r3M<'
        ')oj+RyDJY6ookXtoC<5Mk|+(Wsi2ygJ5y|sU{G@Y)PfK1C@e8znPef=EV3u&b#lOuSVXc^YQiJiHH$>0xeOT^Vn#BG1(?9sN#+me'
        'VXjvktSe6v(QNc<v7hBZ%tM0xl*caQghjQIAU;g`C4;`=zGKiY81zd9y}DQPO1s6hfhxREGNB!9eI7D<0yU^(c|nY5EsaQ>fQyd$'
        '?6)<yHo5+~_};_MA-(2Rl4jOaX9ZD%BuKFs%;W(}QfwJV%)^XHs#7^>l4~Rcj;#wD=8YX1MO^gGIl-6C+RbAua&Xp)5&AUFnf=W!'
        'cdE}-fCHA5fo$h`9$>i%7q0(Mphr%acRh#*yVExaJIbgiX0V$FDkxgvHsXp7k`!-1F{_9in#MCRHC0RJr>Z#HXK@;GJ-B?p;Ju;r'
        'L8l5I!V=s+hGqEVAN25I*~0`uLLS0YM8nJ}G_Yw8kR52AK&uODCi!ps@Kntgv?R2P_Jei!yr>qwfXy+#UyY?sY3z>ZgdN8se1pjB'
        ';(rfq-(5h|=;FU4>f;$i(J*AO>nit5zeKX`og-@&Z$HD26W)IKA9$OF;AL@l_oB;(WiwayGVH@5DEJ<pgU-kGtAA5J+WcZy`@>!B'
        'Pj<CG+SPu!tFiw2DFn>hyF-sE4bog!DGEnidG<17Hm6>)H@8yZHio$HNi+-Pi--@mTmF|s`=h+{&sm;ZGbn&Vrkr*IwHp)d$oY)='
        'xO9Gu+Q;XePpcid-d`A95e{Jq000'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
