# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/silver/zubax/sapog/firmware/tools/testing_uavcan/public_regulated_data_types/uavcan/file/408.Read.1.1.uavcan
#
# Generated at:  2021-09-29 15:16:17.924142 UTC
# Is deprecated: no
# Fixed port ID: 408
# Full name:     uavcan.file.Read
# Version:       1.1
#
# pylint: skip-file

from __future__ import annotations
import numpy as _np_
import typing as _ty_
import pydsdl as _pydsdl_
import pyuavcan.dsdl as _dsdl_
import uavcan.file
import uavcan.primitive


# noinspection PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Read_1_1(_dsdl_.FixedPortServiceObject):
    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Request(_dsdl_.CompositeObject):
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     offset: _ty_.Optional[_ty_.Union[int, _np_.uint64]] = None,
                     path:   _ty_.Optional[uavcan.file.Path_2_0] = None) -> None:
            """
            uavcan.file.Read.Request.1.1
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param offset: truncated uint40 offset
            :param path:   uavcan.file.Path.2.0 path
            """
            self._offset: int
            self._path:   uavcan.file.Path_2_0

            self.offset = offset if offset is not None else 0

            if path is None:
                self.path = uavcan.file.Path_2_0()
            elif isinstance(path, uavcan.file.Path_2_0):
                self.path = path
            else:
                raise ValueError(f'path: expected uavcan.file.Path_2_0 '
                                 f'got {type(path).__name__}')

        @property
        def offset(self) -> int:
            """
            truncated uint40 offset
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._offset

        @offset.setter
        def offset(self, x: _ty_.Union[int, _np_.uint64]) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 1099511627775:
                self._offset = x
            else:
                raise ValueError(f'offset: value {x} is not in [0, 1099511627775]')

        @property
        def path(self) -> uavcan.file.Path_2_0:
            """
            uavcan.file.Path.2.0 path
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._path

        @path.setter
        def path(self, x: uavcan.file.Path_2_0) -> None:
            if isinstance(x, uavcan.file.Path_2_0):
                self._path = x
            else:
                raise ValueError(f'path: expected uavcan.file.Path_2_0 got {type(x).__name__}')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: Read_1_1.Request._SerializerTypeVar_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_aligned_unsigned(self.offset, 40)
            _ser_.pad_to_alignment(8)
            self.path._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            assert 48 <= (_ser_.current_bit_length - _base_offset_) <= 2088, \
                'Bad serialization of uavcan.file.Read.Request.1.1'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: Read_1_1.Request._DeserializerTypeVar_) -> Read_1_1.Request:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f0_ holds the value of "offset"
            _f0_ = _des_.fetch_aligned_unsigned(40)
            # Temporary _f1_ holds the value of "path"
            _des_.pad_to_alignment(8)
            _f1_ = uavcan.file.Path_2_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Read_1_1.Request(
                offset=_f0_,
                path=_f1_)
            _des_.pad_to_alignment(8)
            assert 48 <= (_des_.consumed_bit_length - _base_offset_) <= 2088, \
                'Bad deserialization of uavcan.file.Read.Request.1.1'
            assert isinstance(self, Read_1_1.Request)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'offset=%s' % self.offset,
                'path=%s' % self.path,
            ])
            return f'uavcan.file.Read.Request.1.1({_o_0_})'

        _FIXED_PORT_ID_ = 408
        _EXTENT_BYTES_ = 300

        _MODEL_: _pydsdl_.DelimitedType = _dsdl_.CompositeObject._restore_constant_(
            'ABzY8L4#Cb0{^vGTaO$^8678%y>8pNVB!QtkYWLQRvPy>Rtyn-VR5pF8SmQcZY~c*o$BtIsfxS1ny%{I9ZR4D31mYHBGQo%g1?d9'
            '7V!e-tLnMzP4I#(duQtMUCwvDQ&s!f*{?pn(sO^B*UM>Y(kzUOs1(oCV;*NBj1rxf+9)g9=JMMjQ#n4SyVFv%U$$$Xx4&uo&ACVw'
            'g{WHDYcB8Ds!nWOiNi~tiwd5@#H%&mOL!5E6>M({p5nh>*TUGgS&8;UWt1++&iN0z&tJBqGov$qXg_b8ixIcBQgLmCX+MV1QzD+P'
            'YMbXal*rOW7(tYB%Ogv%owmKKC`Yx26<6LbjG7c8y;oQ<5!K<GE=IAkQ6`FsmF<X(C*0U5*QsdbcbcmYXNG87co%b<G({QxzTIw{'
            'Z%4-RBIQ-OZ0Knn%b+=@$73Ua%GoH@N!#>V48QCh%U9+3?o-gbxD4n+4g>O%e17!Is7IK|mw?k^U-Q~2h*cGzw#_RaaExN)z6)iY'
            'Mh~ZaITD%3MPWUJ^0m(L_eLx7b@}~Kj}ntVd{W2F1)x##MA>OO`gilKF1=_>1vzo|5B$EfQJk5!xi*V*0S$t-N58ktrJpP7<K4m6'
            'F4E@NNSAHHPBUVrd8{)9V6SY7TmuISvOOq8#jUQEnVm=l0?Buqm+$H#;Z_tUE~Rv7WhDxtCf2{ORc9HmrpH#Ei}rX{i}o*Vf3)(2'
            'iRHZxhWps{$~G@1Vq28Ls?$Px6y^K?pkl+W8<Zc;Y&raLRkWiXeZaEKZ_YR8iIa84v2=8XmiE3dV5>MNdEuIDtBwT%Nl=G$v$rC}'
            '(n2XQOO`>lv!x^0HF+IhuQV%wgeW|Rov3-ZsCQgZvGu~vI}g{l*LNRmyZ!RR=DV}vAdX5H3gl4pt!z7_c{a0-Jr~9mPiPbjS=s15'
            'W4?Lj&7ZWyJr`*H-+~D?*FTExzq9r3?t5J{vhG~S$IY|1Zr`386U~(+*@@z*7cw&XNZyo{EadOxZ)=D_Dv$;-ByFEI&x7a(B8^I2'
            '*+`}BR`XJ1bX_GPqE3w*kWDd^Iu}EuGDzR>aUJu6q2Z;T49BX<_jx6TR_n|R;o7QV68UBymURsBMwOVLs&KeaH8bp%ke4CpL3k^?'
            '8Tvu6J(AqOc||P@4cJqOXrIb!AN}i0ueSv!B4uPI4AvQ0U}lQ3oKd(;6bbYzWvXEB?{2&mvRx^dF0v^Dp;gL^fMFslQ-)d0jdg__'
            'Fp+U1+3IkW%o^lDhTT{ngKMl3W2il|+U=^ewk%b^5~ilCPh*)*92uA%vwf)&NiI?`R?ub^Pu)IBM^tNJuq^-zDCF%TYGGJkgp-i1'
            'h9TS`dsdK-Za*~GeMhT-djvtBXIAQZB4HSgaz15=q{gJ&U1l{Maqxu>*aMctNY*DKqCnP(NY{QEFm{8jd+1873MwGw$UU-viL*=<'
            'k7&$e4VRe@MIfYog^hfHYIwTA1zND`MrMW=GoAGlEw}P#@~&@yjYD$u!b6^>aC1zCF#8Lf*rlItM=SMV`8Z8AgnUA~e<ZKUzsr6t'
            '|M*n?X-hUu^?&Y!H*db>uN!aRZ`Td-&riVouUC3Kn(;LlS2_nY6%GYUEJ@J{0eB9|5N+(f2K3OXm?~IXT#i64kP>Lt35aIKb;c5&'
            'Whnm}A$uFqFn79w_m2g`U596eDQnp5bfh*SjtOWnxW%m_7?lZT9oHx>tRP-gf+rFLo#GG+*sbFZur5OsWT-ggW-yC;${veK|Ic1K'
            'j}C>}44CrMNv1%1RtS;0#vKcr$j*iZ=iGj*wlm&UIMS#<@K5mg#_AM^TAI8S3A`D{YAFJL0~)Xz1~UL$=;8*@%~-m~*#(GJEL?>5'
            'd~7=Y6rA@h;^pBwG4MJZ7X)HV%7B7<O+bjSa-@eam}=oM7YEANwE<*;@v^KmjwmF;L{;f3AVow!Au4Cphca-ILZK{$I$I?25=BR_'
            '&M)$v5`IRASs5@2FIFcyWBzj?XbDa`;I4~QdAW&k*wjXN&GdYAMMIY42S>ibWh)J0VfTe7e9qc6vfJ-<G*=TzyfSrWXX@4!SI3sC'
            'g31AOc+MxnHwn0-5l9|);SK`ef-dw5oeFnlhMrTy08^dg!bs-^2~+A?sZ;u~&N97E4wAWyhU~ro=1_sDPiJ3hL)^dxyaJB{<@$}j'
            'BWTMchtPBUz-i(nHB}R3dB!LTPAWZEoEQf6^#>RgGyN2ZB2VY0Mu?R^M{vF~I^+XWkKHNm1(W6u5#RuqLAtdto+P?TJ2j?dq(2np'
            'EUIHMF%%Ar-N2kU;CV^Ck_p#@n2ftht||gOj8(BZSRk-C1C8VzrwUV7i<7XcUtLl;^nQ_PPSJ(IPF<GTh(*KCx|{;V{@OL)&U@=O'
            'Zr%RzfEj%(X}4jK`B;0*T%!A~(PI&;hKLLnRztQiFR>%`qRxZGKIF5M>D<gxwHDKJ%fb2>3|LNYp3q<!g#Au^c)D=dj|HtaIpAB0'
            'qiY<umMGF)Rf5XDP}f{nLkyEgqz`<8<^Tb?yPRaCYj`Qwq&V(=AF>@B4&AN9-yw8qi6IkFP!kF|GNgA+VVi*0R_Ev<Z;nHL1RW`O'
            'MBH&m&#3|tc6%2h?II)w)b_Y|4VLal9+04m)lJO3Eb$ZGJXA;NJY1~l@Iq_X2}uJTonDM)(NKKBoGl(eFOm*HGdoQ>Rw>#PvIp^='
            '(zVH^15cVcAyi(vD?jjYcsP;38*Ab%m^*<JFmM|WalmvW-tHuVAzajN%&SE~EeQkFKkIbP9Vm1<PzP|YAzri~@`0ja&|`Qec0Aov'
            '#tR(@v%4C1&E(>xct9!YWdQ8-2D0wp^M$DM7=u9Cy^^8bI1&*iC_(p)xj!%9r`_7Vntxi1ZTV%tq^IdgE0^DqeR`Art-I0nWr}~Z'
            '3!VI{e<t3<J+HsG=gn6i8Ta=;c~M@HFZ$m^T$TM(Zh-P1?m8y_iPx%QjBPhRxzJq2v&#R@sfr{T6F-jr?tsmIcW^Qu%egP-$qv80'
            'f7N}8HV0=;d|At63+a7w!M%=GmS4vX6q@|(gh|>O{s$`UFv4gP000'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Response(_dsdl_.CompositeObject):
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     error: _ty_.Optional[uavcan.file.Error_1_0] = None,
                     data:  _ty_.Optional[uavcan.primitive.Unstructured_1_0] = None) -> None:
            """
            uavcan.file.Read.Response.1.1
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param error: uavcan.file.Error.1.0 error
            :param data:  uavcan.primitive.Unstructured.1.0 data
            """
            self._error: uavcan.file.Error_1_0
            self._data:  uavcan.primitive.Unstructured_1_0

            if error is None:
                self.error = uavcan.file.Error_1_0()
            elif isinstance(error, uavcan.file.Error_1_0):
                self.error = error
            else:
                raise ValueError(f'error: expected uavcan.file.Error_1_0 '
                                 f'got {type(error).__name__}')

            if data is None:
                self.data = uavcan.primitive.Unstructured_1_0()
            elif isinstance(data, uavcan.primitive.Unstructured_1_0):
                self.data = data
            else:
                raise ValueError(f'data: expected uavcan.primitive.Unstructured_1_0 '
                                 f'got {type(data).__name__}')

        @property
        def error(self) -> uavcan.file.Error_1_0:
            """
            uavcan.file.Error.1.0 error
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._error

        @error.setter
        def error(self, x: uavcan.file.Error_1_0) -> None:
            if isinstance(x, uavcan.file.Error_1_0):
                self._error = x
            else:
                raise ValueError(f'error: expected uavcan.file.Error_1_0 got {type(x).__name__}')

        @property
        def data(self) -> uavcan.primitive.Unstructured_1_0:
            """
            uavcan.primitive.Unstructured.1.0 data
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._data

        @data.setter
        def data(self, x: uavcan.primitive.Unstructured_1_0) -> None:
            if isinstance(x, uavcan.primitive.Unstructured_1_0):
                self._data = x
            else:
                raise ValueError(f'data: expected uavcan.primitive.Unstructured_1_0 got {type(x).__name__}')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: Read_1_1.Response._SerializerTypeVar_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.pad_to_alignment(8)
            self.error._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            self.data._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            assert 32 <= (_ser_.current_bit_length - _base_offset_) <= 2080, \
                'Bad serialization of uavcan.file.Read.Response.1.1'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: Read_1_1.Response._DeserializerTypeVar_) -> Read_1_1.Response:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f2_ holds the value of "error"
            _des_.pad_to_alignment(8)
            _f2_ = uavcan.file.Error_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            # Temporary _f3_ holds the value of "data"
            _des_.pad_to_alignment(8)
            _f3_ = uavcan.primitive.Unstructured_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Read_1_1.Response(
                error=_f2_,
                data=_f3_)
            _des_.pad_to_alignment(8)
            assert 32 <= (_des_.consumed_bit_length - _base_offset_) <= 2080, \
                'Bad deserialization of uavcan.file.Read.Response.1.1'
            assert isinstance(self, Read_1_1.Response)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'error=%s' % self.error,
                'data=%s' % self.data,
            ])
            return f'uavcan.file.Read.Response.1.1({_o_0_})'

        _FIXED_PORT_ID_ = 408
        _EXTENT_BYTES_ = 300

        _MODEL_: _pydsdl_.DelimitedType = _dsdl_.CompositeObject._restore_constant_(
            'ABzY8L4#Cb0{`t?TWlN06(#pc`4u{jZRO#3lQ=e=I3)d6o|bFNkubiLD%**QqF61(wT2Ew63eASr3j#Wq+n12Ss)ug{i@ocs8FDV'
            'ilT-3(MCWTKtBcasgD8`3KY;!0e$kLD0+v>r}&U4>(M0iOUs#i&pmVJ?u<0YyHmpFT_IQDSMFqTGLnkK{Ax-!qFOBaffkPGeswG{'
            'kxZnbrf%mB-qd5!3A~KlolNTXXZG2T><?{UPEw=sxNg|gl{<LHG}2>c+R$rFL^ZBWAjFet?ctaf_ur2q_OPx+@SjvN5l>;CM}4Rp'
            'sc0h3faG_I*Pq$MP24}SKeBWCRn0VwXgF=^Df<VA+Jti1%Fc<mqIxV+;jvGRXr`u`j2xAnM!GL|xSCd<VI*)c2k0S;>|&AWVT?wP'
            '7R|ex#Z4M4JJE+2_sG3?Dmot5BLi_$AJ>iAZ0uLVQB#fS@o|&d#EY!Pw3Mk%BqGS_x!kd#5)gCq-@ra#U6=~j$M&$DdqPc_T0Ei|'
            'k!ql9I*daRA8N5QG7!{AV$9CDY-~M}^W4B3qmNl8LA&V-#jDfAOV7}k={X018zeUM(*VwE5$i;0ym}^S=qWZYHKX+mYbLg7u@XAH'
            'n(Ml6Xk)B3h5fgR*VvzP2W>WpR2YMu--ye>dm$1Ud^e=_4G#|v7iiI|^tECTdMzhjxqSKJ<u(wzLW6hJTZ8vPHyfb2FSLQ=85nFz'
            '%iRv8gV%4|=(}@Az1bHU=xaoaJAbhaxB~+SH89+F<L=<__Yf_2ZNRVl&nb9Y=o3l2dldt3yukYg-pNWLu4qb9GpS-y%~X<!XxvOG'
            'W&&FyQ9~ay6UL;yj?IPh?F?=p^v?C$12<Lt_g){PbG6Suj&#_)rm$5(iKdiz!c?%>q7mhO!aypzVrs^?ZaP+}$rMtrqtVV}9lAAe'
            'yHCA4IH=yfKKyoHqa<Ir+D?)O@7+}gZ>e{NuHR^k*3(XsSW(`&H#9Uje7A80T&%$9xg%8zp&Fia)>a1l3Oz}$&<pf!dV_wK0{uRH'
            'm+Dlb3Hl!WfIg%j(~sz<^vCok^z$^XLJ=Kr=P?aS!u}+8NWCA;=n*xUFibTXu|v7TYATU7#&nfUg35}-&LsjgF`)-i(HJh)fe+GQ'
            'EfYv-$;5cze$<$FUo-T8nMlM^0i<R|<KwEcvIdgra4b5e8v1xT#sXH>;Z&e#!lDEUi?9E@Kj?Q_aVb@)mcr<U9yi&7`!G7D+n-<^'
            '1wt4CtC@lL_u)R0j+sj0K2~m3(I|<eZWLB0KU)*SF<g#LmzJ~2;)%fK`p<Umz;~kN?ZW3fdU@r{@oFMz=agn3smY0O0>_HXL7zzA'
            '=D?y47HHtUQnhQ2(J1as^tZXkhO|folT~L#f6sbD=~zrNCfE1UtDo9F;<Zv?+&YsEf=xW>FphH~8fO~|UT7J1A+yZ|Gmmb>!`xg}'
            '3b!3x&$W1An+>JIg;K>0M0fT-tU>%--t?+=%M-=jvb+QMakne&`;oexvufjfy2*xZ7}}(rJN}M_t=Qt^{5or`-8c`bdQ6{Sh2ZSq'
            'mD|ZvzMXPixSJ-mv8Xv|gUg+Jyfi!a*|!39j_f`>OWf?{a_+`o(O*01{SBR~nuVjdgR)yC-f%iuP&S)br0hEr`lod>R0DN<Sc{MA'
            '!+KITqs?mLy~4~PfApvZ^H_yx`U`Q<FTmxY3usQ<&WsYS_?0hw#W~<CA{5)iavR}^U=hjr%&}{^rjLk3vPxA#y6XCfj4a5$vOl)q'
            '=lu=sNEg{>kpoVjhs8SB)Q;>Y2P|@^1{Yhg?Xi|V<RCd@5pOYuMGkLhO&-HZA&=KZ!X9itvMGOZm^^NgCmdS=`wuYRqnq|6N5~Tv'
            'Io6N^_F~`hwy?-ia?B##rA#B2C)@TX$4R$Eo@&YoEwKOTE#Z<U$x{}2rY2w5i+Crtj7Od(&sgNymVD6)ZB9N?403`zYZ0ZKTgLji'
            'M@A$kiDHrG9UP?<e-{0PZHY&oBhOppR4HcFJg_XixNR}W3*?kVPH#9f=%JuB+Me0g*yKfW+9JNvIE!<3cH3i+GsI_+mo`04^g#QU'
            'cZ3HyOJ1_bxysz0LQG%v{JyedammZ%oJIU?<pI6WC$OWO$ScHekzl0`d`=~t-|?s<K!O&z&~`@96a6mk3O{n5T(HQc`ieP+*uhfO'
            'T;4S<<RZCbkt<uu8G57d)m`OEE|V)3>8Y)*Agixecbx~hN_s5v+Lm*N2<ZR%p718GlGiNqM)NwngfV(pExx&D{K)I%4U4?>Nclw+'
            '#JIMnV<2ymw=B|ISF>#P`%A68we2Id?fr$GA*YX4`bO9Hk`aq!>icQYB3ZJ@R@+Q9wjvpeOgnbWB8$EF?JoNG(5eSL`_Xm;{V95&'
            '?QFg6G+NIzv!8EnKZ_o7jeHh2_L)boh4p^RoA+Bp&!uYL)%Jat(R-!jpWnLwDk7{Q26)^>5d8VHZJc~HQujI}gl1sib#D#N*AfrI'
            'F-TC{?V<Lxfr=CuFa+J3!|vZQHqv77(Ccm;VPu;kAXOFwhTM(g&>e|`^qo*J>aLEK*_CKGC>9WsZWc3J6%(d*C@hYwKJs+K$VjLd'
            '9ITy<KfCGpNVP}-X11Hf{3EfzK@^F=+@o_@+;%QFydoV~*b1ZNU15X+FOq_#&GA~@GhUdIYHG03fL;Foj~!;LND$T-$29%2z!6*='
            'xCC%X;PMa;csTF~kQc!t5ifW-@Cx9SNH=tI&@Di>1bLY#pm3lFph(0AJ`Q{W_#_g9AO}GKf)eS09u9g0=#fY-^m5QEK(9plp`U|('
            '0s18}1VbDQ2{0s)5g6fMM1T>AjKU}fqXLXdgaYM&3P2^2gd_(^0g@8QK!$^i02v8WJH^4208<j?Hp@X)fUJbcwK%W@uq4dxGzZfH'
            'OiP&F84hLyn2|8QvmDF{Fe_n#=Qx-XU{1me&vP&@z`TShUf^IsfCUM2yvV_#0E-ePd5ME10hT1p@-hd@0xU~p1y(p%5nx5a6t8ly'
            'D!{6QIbP#nO@K8CXCco)9`h-&LU8fm62T?2Qt<HL!6eJ97`!}qMexe39J+bv7NJ{a1)=buh@i-<Bz!#hMDWS1D1tl$MF`5QEP8n8'
            '5urzBh0)7HuL!*|D~*00`bFrMS#b>UFeJi|%*tbghY=A*WL6%dJdBDkDzoaKJWvs+%<3b_LsEpK%<3n@Lq>#*j8zO%JWPo&C1V{!'
            'mWQkeSs5!CEFLToEE#JVrg@kaVOqv&h8Z4aM3|AWo?(`USrKMstZ10yVNQfO8EYEmd6*YrUdF111s)beSdg)<VUdSL5f){vY*^x9'
            'NrWXCYa5n%$n&r)!m^CD4J$mXh_E7Kb;BwTt0Jt*Sl_V5!<q<dGTw<+I;^LdxZ$N=fcNVpZg|+Cc1PUU1#!dc<e?*O?0~r8#nwW0'
            'w^iIwHaalb0dYgAoriC%xS>=8sc((A!Nz<Fk$tuE`>hr?SWbMUO6Z6i>%@)Pis^_O?TQ=DD#H#=y&ZAm5yTB=SL%oxyCH5=R>W#?'
            'gSGb7wvRaNy~P@@7dISP!i7C0zglsl)Za?nC`lWxqK&7CxWO#4h2D+Djau7{#f`@Ht;LPjKF!6A&G|JJH`?>97dNH~bCE@F@7BeQ'
            '!m)CN$8=#fTH|DDkn$yQqlCmxiaqS0#=TWMUsF7G?pqw{M&d>tYEK)e8;Bcq*!^3=X6Ld+`1RsOU4)Tsim*=HsEb2)Bn~?}ErhBT'
            'H}WNMqf&zfm0{bXRUL%pOX5c97}Ui=X19Hi^#{cHlDJWcoOM?RX9utwmf}W7`7PtmZX*7)yOzS1#Eq6L<{ybg+u}w`E{ogFWfS5?'
            'OGeAP!l<FR(URBdp7CPxL7Cc0V|Mvkc7=t6NgLU{V^=F~<cs1)wX^{q2|S*Xw!sy(4GFv+rf@KEqabn!dns=~2LEtO<PaLm8%)+H'
            'DjXeo<C`jPINC;@-@Lq0dd9|iu+n+PMx#Id(0(xIcDd-^QuJq^(4U9sFLFQJxd*Mv&+P=NpWCT^=!*W5Jz(|5^|+F*vQWknv6x<X'
            'kdr-U6`sV<=M=s0G@qfpuY{v<&6rf86WX}$w;Ml5^M~@)Kj@#?!%AOAwWsqaOGoYLs68FEr=#}lj@rY{Ogm~%NA20X+Eb~Rj@q*o'
            'wTI=dqxN*vp0BIgQ+ul5VFwH4Qw0zHAS^aLRoKfTh0=eT>>Md{jue_5DdgR?rwVfAR6$@r>K6|cbatrVqkpBx9{h)$EPRzNpDY+V'
            '{0f&#!5-(;Ugz<5`9L9Cc&W_>X9AVBe>!IWVlUHZWcj=5(*yjwfW}{j(%}bx#L+tciBzFqfZ{3llpWT!JISN_=>h6>Ui5X0e$_mE'
            '5B|$OJHyGzs-7|RxM{;^SMHb^DZU@gP$`ZdzpQ`Rh(gcMzqfeJNcE_z-}<4{zCz^R#j7<q*X;cuAspmr7aL^xeJ_R47E;4Hry6uJ'
            'SO5P2LXRb_6ixsD'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    def __repr__(self) -> str:
        return 'uavcan.file.Read.1.1()'


    _FIXED_PORT_ID_ = 408
    _MODEL_: _pydsdl_.ServiceType = _dsdl_.CompositeObject._restore_constant_(
        'ABzY8L4#Cb0{`t?O>i4Wb_NE&f+Y*G{6pKT^{lM5A)5jz$+GFcHMufns#=d^NXg+=oPYzM$sQV*L1qRb=~OD(O6`WKLTZsRQemYk'
        '6(uJfbx3WL<f5aFI^@9GlPZTqRk<jKRI!r7=DnU7U_b!;6Dh^J^v@9N?)To;ufKl%^N6_-{Y&c)Lh_&58<pjvT`XmDHn()Gq<^F3'
        'OFWw^nB|IT>ke<!o}1>@b-lo^E?0Qt+s5giHvYJgsU68#{12<#c5)7ti%{*z=e(qsQKZ=3GM>{7gIlu6v}08ZPSx6=ES590GMehE'
        'YS#;zk)6{K!xYzw_>e{#wPfx(w`|=sNKfKR@AJ0}7G~j}H-3sRbDHB=dcNv#yYc&|v`5dHts1r1C7qXwEf}d>QFAo6L%qZ+7WGlT'
        'jxCN~Gi-g{;Kj>^!{@ox-lyksdELpCxH0dD1|#JK4ZT%1i|DQI*Iu6V6_Hr>BGv&_QICGsm}=Bs%-N1+6g8_DRCKeN7e{Mxb8gP&'
        '=#^-$Xcii^Py>r!a}A3V;;{GWXe}Ld=%j`U#4&N4DJ(=j6ECBmT5`45dw9&UwB<(al`l0c#gZ!$$_SNi<ODDAGB<oqsGjCGSyG%5'
        'Z?O<{Oq^b+=4*%08x^gfJIf9B>)H!m_i}SIAYG+1u3R*iFWHUSTRzg3YY?=v@%KjU@Q-!J#XF6^dPr-LoLOnq)Lu&L<#OIE>FC(w'
        'z{@83!9lW3RJf%%rWIs%LFh;zai#XsMbju~4mY|srS4KoiyK5uY=3mTS}JMQa!1Q}?z&d0^2RS38J4Wuc`@#};dfB#l_|}b=Tp4G'
        '9laN%uXAN>37v`pKaqvvD_@uNUs*RAEJPo$8LTI23F2h6q+wGQrlz5~jcnyh70r;7Y`mK12t?pG=nzVZg+N15##+*hWQ$fL!QK`9'
        '_-kJ+i7p`uH{DLuY#-ENIjAUlXnJ&VWNPH<#FUg5U)4_dgM&CMZWEBU$(Njxp4Ljfc9c0ZXK4j0MTR6Vd7rVqro8t-gSaPwT3dlh'
        '!N^SR%INqPSI0aw;v3I|_>)@X+=UBGWxRGg5O#9;WjBzK(u%ks7KJVTO#EpTgF%sFH;5s{#?9LENc1IM%vDUw$?3($c<oruHmg>F'
        '=V+$pq$6v_fH2E^z}8C``UbwK=C!2(TdSD!19Q4nUeqi;;FxB~9zfHMZp`Q0$v#l2=8?P@pXYH@(O@g8*#lk^vNAyNAbT!5m~{)0'
        '?Kz>@XxySHY`amvaZ|iI^FQHGXdI33qDpGAsS%YlsP;0Jl~sbPa-)FptElRRdhP0^p{#mUaMd(Q%PJCDFRC_2#Y9$Bw^ax0=1dFw'
        'fE6Xp7V61?lcd(hevo2Wmchc)s>SCp+N+K!r7Y8Q)S`~QL{-abhRRB2L6Si==hQ`^7X+Co@;M!2vzlL)a?~AeozAAFI64I><myG#'
        '+*UI@JD*igX0vDxd#@T~!;{AtEPuzThTJ0;WVDha%<8;A#b~IkEvp4V6O;Nbdsd|-4sGEKxQ@OgMyeT7!VT<offrAIlv33*>WJ&Q'
        'im4kkfYe9L^(?wcQ%kz>HI=!(Mw2BM3P(tbItpqnuV#BIY<UZ{$`W63tH#sbRdYj(iZOQru(oh?bW$r8(M(4e!rBR3u`6zMgC(o&'
        ';iFg7;Ns6o`W^AQ_*-$NDt>WO)W^kN)U17;3GWRKx!aAi_^&q`#J4NR{9h(RA*yl5V9qkj=o$+b1&3Ht#Ho-%o+D+5HqN4nuE$uF'
        'rxC0=xQRk?At}+D)dCXDo~xGBf>tWw@Sn}9pCcMouCB=YZ@7wk9j#=mx?`*U>PXXwIL0v+Beyh15{!lk)k>}rE^I-(u((zbNYG_m'
        '#8T?HP6ODkgeXXn(PpOK$Gxn6!!2{$Ry~W-3st*c)!phsNk`hN2IoaNap$;G5S|VPIVa_@wd3>7!X=Fc2<?-5+==ByAez!-%_yKX'
        'Te4d4l)D4!SF5P7gbp@L;|zMYq!wF!mH=@o8WQ1U7n_-1K+d~U#0?K`69eBy!v;AqPmuu!+>Hqc5w&cXLs(cex$ASjq}$Hvehd?;'
        'R;gGfE>YMKm0Ol+r6?led_q)Gs|%%Hh7^Jlfa*8m<q8fuf|Yi$zsux5n{$5{uoSI0X2C3}?q`Ej6I|`k@1{}I-Efn~#inX=H)gtg'
        'm4k-8Bs;j|>$uq}rt;ib<lJ!kY|4o&<=r@1*5?KB%C43iKe~B?YvvtIH)uG}J6c(r=k6py?wAOqocG}Nr_e7r3*87^<Z{c5@th_M'
        '`qV7rhLP3{3QR>gmAptlXO>FlA{i(&!)R8$!qMj#1(x0JEDF;mZr}#oLLR4dIp64a1nsCo!$7a$4_r-TNG<B~x}%j;LZMNV?r*Ia'
        'Hjb~mfYD$U7to{FPidx#5G{8d!S!9GMLuO$=j1Bx2284JBft`F25Hx#YK4Mn6}@Oo%_#m5N*`4RCKU$`8G8xq_>xwx&|E2TISH{c'
        '?~UY1ot&P{>&D6cmIqpEpe;0yQ-)o&S}UP9e$@&Mhq-8!OpVZGQ`6N-#k6^A!uzwFfTDa=PQK}}ku&Emyx*_dW=E%`K&$6-rt34='
        '(M37Y^E`Dji^x#J$*g**ImD9Kt#R&e$zgv2J#DH9j8?0<sW~+=hYSdIui2sgpc59o=%W=|1~Yk1?d>wUFMz|FII=BK#M`Q*ykqcb'
        'Ijb=k7QUwVpv~jtKmuxVb5f$Xh9~MOMI5=m&#Ke7IC#4fcMoA!9Ad~kH)s-aS~7%dnqb>0t?HO%oJFoW4Z{zoB?S)=A4^X+se(aR'
        '%C>^EL`V#%I-S9*Kd?V?9g^~}%8I6y06)>1>#B`(9%!}k{Do7yTA<KCOQ#!*d^ChF)ntq7KsQKA58D1};;~96p{zQQzpk5AyR_Wz'
        'lBP)ry<Cx7e)Ny@hYS*U#+r9E*dM2407Gu$K^)z*0k5|bp(5O<pJ|R3feHi$8vl|P=j4Jys{_pd&5a>$(83^}(rGa0Fzg3At$1Cx'
        '-9SfyS#FKJ$t3X-9;6h_WpuENHyGBX``m%3mh)JMo|dO%jNP~-B21(N?KhhC+yLHd*Y?-VPpz_Px7n9;H0{<hc#h1_ne=bG9bHD~'
        '_`koQ6My9%69;jhmuc<unyojKyZb+p7RSU(?oGt&;!KYnp!hqv9TR_#r&Y-qrvbBvYA@rl%Dr>4asnqN{@8eTpf>Lgy89#8_h3KO'
        '_OrL<eJVnKxa-MUh;i)R>>+tNP6kiM(kWDVqf4bcls}I<R2##w%{}-D&sr*QmGf$syD?X&(ehxoJD_7h!BN_mxR*fTu9rXo*QJAp'
        ';+T6a;hpZSt(q$ntjpOsJh=HWyiLWCYvXKu;&;b$qf=AOdx4;~*!veQoWHOGjfci3uI4UHTpRzq8@6*h(3HG9(Gym9Cy<VeT)a3s'
        'J)Qe}bo}yYH(1Kq^E*&?_%f=xJT-dp>crGfP+RS@%UPbq9VZ@Kac9ZhwQgV$cM24NFrLZtqKt}iM{I96GB!4#Id^s^ox42#<;a!G'
        'pXcy-ZIs}AFp8V%emA1iCdxm#xK{-Je!-!j?F6qFI$-Q%u%5qk`O0YS>cm9u%E;6gqurc*?t`5;dE(mD+{C5a^yJ9J?%IZS;v^#F'
        '^tH*!iK(mI8F0R(&I^zKF8)pYr}z)?-{QZ-uf_i^914d*3o&{er^iuxoS?_6^vKZT6g|$<V}Kr?(&IyVd_j+k_-Gxs&3!&@%OHd&'
        '?ZMVr`zDfOpzVrj$~|<*({u2$sd+}(dW8!{>2z@2O5?hf?jDRO)NwaRx}mOHNIl_&)aHF;_8M;XywpaqBfJK5eCU1pr2FOL2!z7o'
        '#~Y}!o8>FrYxxTGTE1AQc|DWyuXmZ^{fx+;*e9jVqF!07S;itPT4!<hcZEJD+Ui)0#p}MS*`ba)mOvCN)s)8){QbGE?bsofs<Xpx'
        'U6O1a>Di7w#}3!o^KE*u6w8ioD#MPj=j$x(*{HK)TefCL(c|oe4og^r<;S-r&yKMd>g+|gZ4~Pdlk7{|mSxA;i*@#LR}5H-b+7D5'
        '7ki1lTxWg0rxDAmJC<j!u)aEbttTdIf%UKNN-ukry;f)6Yx5V@qP`Qm*2i9F->b9lZ;BUNVVgIe$Ob#XzF%i*)3=2B2T!b#y@A_S'
        'cGA_OZib(%zqu#&*bmsrIy>dt42%PL>4$q}gT2X4)!AEHjtoku*c#iuy{ER>57}FFmht=PjoIlvx53`VBNlsS+x<idZ2#`Q;9#fO'
        'J9XCI8rxH-GZP%&Gy7(jz03OREW0B=pcKjs>?<aAhGpw)u*HLn%Y?K0Zj}wN!8$v)V~?OD%AJ2I_}E!?uFl@;WK2Km9`spr;i+L^'
        '=h=I8_WrJXhSDhe!BfS`F0l9OY^a@GgT${7pE?fq0UN5bk9O@l)PV9IKNH;SL-tXfebSqU@1cz$;^L>z3?KWLeNtyXdLsX#7S!?C'
        'GwlQWl>MmAhC4V*qd(@C4!4)jw3m;`nn|}#wCZLz*0Py8Tk5PAUW<y~W+m9>M)y{1sm@m2cGO}8YjL}aG8t?&gpy;}b_V4IN?_aD'
        'oo!dK^{rm*@Ahtg8zt^^lexdO%w3eaw^43w`*QbD@<CAc(avSpQ2L=SzrK6<N2uX3>VRa}Q-bHy9qU;SYU<md300FaNQZZ)FSDsW'
        'G)F2y4ew0r&<?aB1X2ux;qB=j+qG_lMe1QVyt##$J+gpM$p}n_yW0`_Vh7>7reHQ4w6^qAtYN3fAXLI+b0uICZtRm;>{+Mf)vlHi'
        'kY^m~`)mL9w(TQS4+7lUYZP~%2nBY+0|IxR9LxPZ$AaDS;K04zAX<AWh_K@xD0r|vT#ud^E_6u{8a(WRZvFosI`o(a5FQi8swhj0'
        '5K<r%g-{$qNtT490?8<>#~>MJX-F%OjzT)l`k+sNz9{s?VLicAP!&+4pvGASG74m(kcqQF7*t>|3WISr1Vai8MPVq;hGAHN;V2Bp'
        '*%*u|FcyWeIGcn?1ty~~8D}#vqrglQX5wrXW)+x?!fc!g5DJJWh&Zc2MS)5bDsi?1OA0JSVJVKTy`jL3DBOsnZ&wspiNZ=8om*F+'
        '9))@wy}PQwY7|!E=-yij+={}jIQsXt0=J`ZJB|*%qrjag+=-)y?<#ON3U}k^;(H3*i^9D)`uM&A_oHw>j!u4{z=J3}h@+R+6j+PG'
        'TAV$EhYCE5!oxVa_>lsSqVOn=K7Opg<0w3i<0z~vu#WzW6A?lY2*n_jASxsykVGdZhz#inq+^gy5FPp=&=-Tg1Q9}wfEoieL6pcu'
        'AQOX3f=DqKfx#FICWsb85g3ZWP=bgt9D(5&3@3;hV-XmO!B~RGF&Tl$7)&OJ9y1Y`iNQ>Q=rJ3C*%-_wh#evVA_gKs{HR2r5`#*D'
        '__Gv&r5G$Fki~E#0ykoCBY`}Il?bfFU?qV}hI$0*F{mey%di@O)flWMkj-!_0=HstD}j85+Yz`OgWCyYG~9{6ofzCnAgAGO1n$P*'
        'ZUR{i_abmF2KN%kYq%eQ`!TqmKxV^(2t0_vg9LIL)*`STfwdT{C6L?jFai%_@GybwhDQ;26oW?z<TpHyz~dM^PT)+e`+vHg7CNNA'
        'OUaESU1}dBH=aUrBklU(Ai1#*$&ECYO7HGzazowf!ek$k8*2MF{Kh6X)K)_3w<ftkeLjVnGwtL1Tb<k>pJaR{93(e3Bsba_bCBHF'
        'X>!AjGIVj8K1gmnL2|=gl@5{{Pb0a}iipAF29*xCm(RH6!yd;wlN)YYB7`-*TzhiEuiq@W;ioo2UYlf(<Oa1^k+oYVH`?27o!sc&'
        'e)HtU<}$sL8{3oXp4`}(Y-e)gh8&9(luqwHxgoEWTR2wbXl$-$sZG<mpWN^@(M@rZE^5NN)tBk1kM4cFu5Ojw=+HW}1Fc&mH#&5W'
        '?MgS@%X;cJCO0}P%<Pec4atoTJ7Qn#(A}vt6-;id`^k+K2W6IF&#eV6Lf8G|hJOtjB9kk7-pS4j;&nf{(XzY}4jQKm*e$8J)m8qc'
        '_HS>){%W`#!mg4Vo1(b;L@0Kg+}IS${XNIBjpW9rh}ND8qOQq}O>sSXX1FMQ(1iA|JG%9DbTW`oYGdWup=(cWtb56gU}^)BaY!cp'
        '+=k-iHsX*@Qig+)8#2ieeU|ABSi=7lN^(TIr#C3A;bk}u(i^|2=?yoxu^!oedc*(DO7QD>8huM>;X@@9S}2A?A-nm-o<G{ZFZMLQ'
        '3NsM=Dop2>d_Ea5)M}uGS};o`UhrSvl3zyC{VJDV6SK5MHLn}=-DCGF-dla+XTiYk2EXO=-OBkKe4*ta=W~$rImr1O<b0k^&WCPJ'
        '4{|;SIiKz4d|He-$ocFh=R>|b$oU-Pe7>tWpZ2?jBwa5w?-r7H9FFz8TX>ci3;v%@9$YLOTrBjuSXd9Y-z_9scMDNE?YF(5bK&>s'
        'oc*hXpV1Y=SHX9O_%CYe-?O(*Elh1V)4Ol(kT2|5_zVHKf8eR&VPEa?(y0yQ-b<&}TCYs{mF&Rw`}NQClBa+9ZoOe@<D0<g^-*2l'
        '8kNMB3GWSUoi9N7S9<f2)qLwzkPyElkNpEZ{)ry{sQA7^e!JegNw4p!=Cl6?3PJ!9eO>?n'
    )
    assert isinstance(_MODEL_, _pydsdl_.ServiceType)
