# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/silver/zubax/sapog/firmware/tools/testing_uavcan/public_regulated_data_types/uavcan/si/unit/length/Scalar.1.0.uavcan
#
# Generated at:  2021-09-29 15:16:17.548853 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     uavcan.si.unit.length.Scalar
# Version:       1.0
#
# pylint: skip-file

from __future__ import annotations
import numpy as _np_
import typing as _ty_
import pydsdl as _pydsdl_
import pyuavcan.dsdl as _dsdl_


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Scalar_1_0(_dsdl_.CompositeObject):
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 meter: _ty_.Optional[_ty_.Union[int, float, _np_.float32]] = None) -> None:
        """
        uavcan.si.unit.length.Scalar.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param meter: saturated float32 meter
        """
        self._meter: float

        self.meter = meter if meter is not None else 0.0

    @property
    def meter(self) -> float:
        """
        saturated float32 meter
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._meter

    @meter.setter
    def meter(self, x: _ty_.Union[int, float, _np_.float32]) -> None:
        """Raises ValueError if the value is finite and outside of the permitted range, regardless of the cast mode."""
        x = float(x)
        in_range = -340282346638528859811704183484516925440.0 <= x <= 340282346638528859811704183484516925440.0
        if in_range or not _np_.isfinite(x):
            self._meter = x
        else:
            raise ValueError(f'meter: value {x} is not in [-340282346638528859811704183484516925440, 340282346638528859811704183484516925440]')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: Scalar_1_0._SerializerTypeVar_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        if _np_.isfinite(self.meter):
            if self.meter > 340282346638528859811704183484516925440.0:
                _ser_.add_aligned_f32(340282346638528859811704183484516925440.0)
            elif self.meter < -340282346638528859811704183484516925440.0:
                _ser_.add_aligned_f32(-340282346638528859811704183484516925440.0)
            else:
                _ser_.add_aligned_f32(self.meter)
        else:
            _ser_.add_aligned_f32(self.meter)
        _ser_.pad_to_alignment(8)
        assert 32 <= (_ser_.current_bit_length - _base_offset_) <= 32, \
            'Bad serialization of uavcan.si.unit.length.Scalar.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: Scalar_1_0._DeserializerTypeVar_) -> Scalar_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "meter"
        _f0_ = _des_.fetch_aligned_f32()
        self = Scalar_1_0(
            meter=_f0_)
        _des_.pad_to_alignment(8)
        assert 32 <= (_des_.consumed_bit_length - _base_offset_) <= 32, \
            'Bad deserialization of uavcan.si.unit.length.Scalar.1.0'
        assert isinstance(self, Scalar_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'meter=%s' % self.meter,
        ])
        return f'uavcan.si.unit.length.Scalar.1.0({_o_0_})'

    _EXTENT_BYTES_ = 4

    _MODEL_: _pydsdl_.StructureType = _dsdl_.CompositeObject._restore_constant_(
        'ABzY8L4#Cb0{?YWOHUL*5MBc-2tGm}o=oH<aGBZ1EDi@Rns8Y`BF3BP^h`H9o%Bpk`myekkjOzJNhg|6{x^S))y(1|hB;MDJ-@HM'
        '{<8S%_d@IH^Uv!kGfYOra4o15r!<p1BDpGSWrXG6A01oma_cnzFs(UU!p=FI!M1Ocik29E=IA)5Rb)iuDq$nZtC20D<D5#W!7r0B'
        '*G8xcik4scII}NdcyHMH2It^c3AI*>%vo;W6Wq1Y-z4zueZeK0Z?ZxdwUpSf-d*Lj7NxLaj2RF1rK0v<FsmdJmNcuwa1&eR)L2p~'
        '#-Z5oPmiw4Ls|3&V+SFGFj`;XJ@^e`EUg&T>}I3y*r%i;WW}*C_(ap(B7B3i?9XiM;kWupr<eBn$?k4H9rV(4u$OkbFFQ#$?I&q6'
        '=<e?I21(L^Fw12{+qX+@IkLM*n99Mo@Gtf2H<%>Zw7Jh26kElbL4=Ign&;GV1{eM@IS~`iNUgLbg2AC*BStx$a|}pMYKr^&)3{J2'
        'kByLc#P}44OkzW8HHuG!E<aPvW2=-jF;29i8j(f|aqTiGa-#Xj$uMw!AQR70jEI9=;)bfYkxSH#I#H7V2&bS17ty@3;hJNSbGRtB'
        'iyefWNhI;b^{wZeW1_w7gMav1*tb{yF}ky>`vszE@SArvG1D?r2m?1c;H5$(g?qiLxu#a>xpwZ8yb!3zBK1#>C}YUOe@Vrw5IuAf'
        'K~8T+vBQ{3$KeNT4>y0B3?EJ1G=kx>%MflUsvt`==p-0RL7K>Is9qs_Qq$_{T^+j2WG;*T0OHPqrQ-tt00'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
