# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /tmp/yakut-dsdl-zmn42v0l/public_regulated_data_types-master/uavcan/metatransport/ethernet/EtherType.0.1.uavcan
#
# Generated at:  2021-09-29 15:15:51.768708 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     uavcan.metatransport.ethernet.EtherType
# Version:       0.1
#
# pylint: skip-file

from __future__ import annotations
import numpy as _np_
import typing as _ty_
import pydsdl as _pydsdl_
import pyuavcan.dsdl as _dsdl_


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class EtherType_0_1(_dsdl_.CompositeObject):
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    IP_V4: int = 2048
    ARP:   int = 2054
    IP_V6: int = 34525

    def __init__(self,
                 value: _ty_.Optional[_ty_.Union[int, _np_.uint16]] = None) -> None:
        """
        uavcan.metatransport.ethernet.EtherType.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param value: saturated uint16 value
        """
        self._value: int

        self.value = value if value is not None else 0

    @property
    def value(self) -> int:
        """
        saturated uint16 value
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._value

    @value.setter
    def value(self, x: _ty_.Union[int, _np_.uint16]) -> None:
        """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
        x = int(x)
        if 0 <= x <= 65535:
            self._value = x
        else:
            raise ValueError(f'value: value {x} is not in [0, 65535]')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: EtherType_0_1._SerializerTypeVar_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.add_aligned_u16(max(min(self.value, 65535), 0))
        _ser_.pad_to_alignment(8)
        assert 16 <= (_ser_.current_bit_length - _base_offset_) <= 16, \
            'Bad serialization of uavcan.metatransport.ethernet.EtherType.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: EtherType_0_1._DeserializerTypeVar_) -> EtherType_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "value"
        _f0_ = _des_.fetch_aligned_u16()
        self = EtherType_0_1(
            value=_f0_)
        _des_.pad_to_alignment(8)
        assert 16 <= (_des_.consumed_bit_length - _base_offset_) <= 16, \
            'Bad deserialization of uavcan.metatransport.ethernet.EtherType.0.1'
        assert isinstance(self, EtherType_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'value=%s' % self.value,
        ])
        return f'uavcan.metatransport.ethernet.EtherType.0.1({_o_0_})'

    _EXTENT_BYTES_ = 2

    _MODEL_: _pydsdl_.StructureType = _dsdl_.CompositeObject._restore_constant_(
        'ABzY8CxcXB0{@j%ZEqAe5Dp>-X?ST+5E4ifgJ^+B*-OI(AwKm;gA^THqXZ)Hfm+`6+}WzvUfJGL4hac9P!-7%NVq?v|FPrC-X+jR'
        'Rrkw|Ju}a|J>$3Yf7;gE<O?^dF?U>L)Pa>u$=57bkkP`Fm2uKT3>WsitqWgUcs{NmevbFv#W(S8Xi?2d)ZeMus9-uP!831}c9pR{'
        '124d8@Yz-pCZ1t|j=(x;bQE*p?0zGEj=j0wso&$f7|v1Vy_I?G!Npe?<Am&HRxz}mNKpJJt3}G0XVgyup5R_tSxPTQXtDf4J2}+A'
        'x3!01ljscW9L=St3iQy6*jqyIf;mr1!y$^x;mXbwD7j^usC$-FsiOCBH-^j9d8RqD{5a4bbuL<=HDap94CW~}MGSKhZ!d<0O{0^K'
        'pCuud#g#_7+FKIW#CPIGgRs3r_d8MC6t}_|+Q40(mJA1#1(!PfMZpWZ%;OzX(*R;6d^51DNVg94PZ}BZVSatB^Dw4TT#g}c|5rw*'
        'ySqD+e8h@aZP3Mfg4yW&512_|5B>$Hb-%N*zA;0BuzZX#G#?)_G9eOiN!%0Pi$~&t_*wi^<0v^`Lki}B#}DBm9moUVG;x(m9{b@E'
        'b*8ojph5wy7!E4vwlAypnEh7!)zsD1*QM^PkJePXs&gd^YGGKb1bM_dw^||(z_t(9qW#5Mw5My)o~=c;mi?F=+9DmPU=D*@&_0oN'
        'BnyZi#Le*6UPB}@b0kGW6-SsO90n3;O!6_=-rCwCyD*dv<EBxPZtaD!(vJy(knL{2n=L*U(h-F=1ph`W)Dc%QrHHF@2cDS0u?Su;'
        'PcW^?mE>SCls6;?VnM+OZOFh_@}j%H+3jbE)wx18{V-+Y5&f|&|MfYB^N*!}IyvvbjQim<HB}7cBoH?)bAw~RzCDA|;CiQOf2jb='
        'Huh+Z&(K0hd?dun@a+!cT<YOJjKr@=+pm>kcKo$gtbB}jdrO~Oj&E3Xh!A@Vb&hqGQm3Z@1$K~xv*~$2Ql$JB(-z|B(>nFBtH{~x'
        'Z}N*NS$zcn00'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
