#
# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2021-09-29 15:16:17.558241 UTC
# Namespace:     uavcan.si.unit.torque
#

from uavcan.si.unit.torque.Scalar_1_0 import Scalar_1_0 as Scalar_1_0
from uavcan.si.unit.torque.Vector3_1_0 import Vector3_1_0 as Vector3_1_0
