# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /tmp/yakut-dsdl-zmn42v0l/public_regulated_data_types-master/reg/drone/physics/kinematics/cartesian/Point.0.1.uavcan
#
# Generated at:  2021-09-29 15:15:52.563887 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     reg.drone.physics.kinematics.cartesian.Point
# Version:       0.1
#
# pylint: skip-file

from __future__ import annotations
import numpy as _np_
import typing as _ty_
import pydsdl as _pydsdl_
import pyuavcan.dsdl as _dsdl_
import uavcan.si.unit.length


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Point_0_1(_dsdl_.CompositeObject):
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 value: _ty_.Optional[uavcan.si.unit.length.WideVector3_1_0] = None) -> None:
        """
        reg.drone.physics.kinematics.cartesian.Point.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param value: uavcan.si.unit.length.WideVector3.1.0 value
        """
        self._value: uavcan.si.unit.length.WideVector3_1_0

        if value is None:
            self.value = uavcan.si.unit.length.WideVector3_1_0()
        elif isinstance(value, uavcan.si.unit.length.WideVector3_1_0):
            self.value = value
        else:
            raise ValueError(f'value: expected uavcan.si.unit.length.WideVector3_1_0 '
                             f'got {type(value).__name__}')

    @property
    def value(self) -> uavcan.si.unit.length.WideVector3_1_0:
        """
        uavcan.si.unit.length.WideVector3.1.0 value
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._value

    @value.setter
    def value(self, x: uavcan.si.unit.length.WideVector3_1_0) -> None:
        if isinstance(x, uavcan.si.unit.length.WideVector3_1_0):
            self._value = x
        else:
            raise ValueError(f'value: expected uavcan.si.unit.length.WideVector3_1_0 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: Point_0_1._SerializerTypeVar_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.value._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 192 <= (_ser_.current_bit_length - _base_offset_) <= 192, \
            'Bad serialization of reg.drone.physics.kinematics.cartesian.Point.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: Point_0_1._DeserializerTypeVar_) -> Point_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "value"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.si.unit.length.WideVector3_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = Point_0_1(
            value=_f0_)
        _des_.pad_to_alignment(8)
        assert 192 <= (_des_.consumed_bit_length - _base_offset_) <= 192, \
            'Bad deserialization of reg.drone.physics.kinematics.cartesian.Point.0.1'
        assert isinstance(self, Point_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'value=%s' % self.value,
        ])
        return f'reg.drone.physics.kinematics.cartesian.Point.0.1({_o_0_})'

    _EXTENT_BYTES_ = 24

    _MODEL_: _pydsdl_.StructureType = _dsdl_.CompositeObject._restore_constant_(
        'ABzY8D1%gC0{`t+TW=IM6yDrO0^t$@lmdkfr4T5Yo%?uNC@Dx0l1qr7qIp3h?~IA3?Cy+aW}_?;Qh8_v(nz(0EAbO}LTyo7Dpe}#'
        '6aS$61bzaKJ<fUvq~xiOWu?{k**-oOkIy;&X84D{Cu(cI@<`f?@~EW+In83yif@r-i)ulbw9_Py3o6R(SBtD07Tt_~*-NRoFHYVO'
        'x5Z335_Cu#)=y`2S&OoyL$#Fk@;J=3n{kJ>Ng-)SvV!I@>1c~d+$lsk7Oc=LkCTpIwQ}^D;`arv;eqeO9Z_xzNKs^QvkUvgb+MU;'
        'uY^Q7G9S}cwC>r~AR+|`3h6Ez>`$_ha=J@aLU1IHwQeUav=;3w7fkyqj_5TS7D;9aHp<5F0Io?#*u-_gcB$P{<-twd$THFs<(~O?'
        'l}2BzY5ZJHy?IvK1KOf(+9~=@Z5C6S#qGF=S3qKXzLk*TO)cAkW?Te)w*{VqI75;bK|6^c&ZFhN#cI3Urd@!wOL9q`?YH6zI2q&x'
        '=|m)pURQJ%^t8z`oJcp4hHqpfEa02u@U7+*2OUe!K&@tYzUTUuVcEzvEyMA2WY~`B*{0=LhNs(><9a^QJsr?79c0_S?>av64bS#m'
        'q{}^~t9wY-P2^a}b9D##j)Ppw^jsHt$nXru)@?a!IfiW^({@3<ZJCB;x(N9&G!O_Q8%)4ow;aoJ4A)1l4%Q6a@m$9-Ol0bwYub+O'
        '>$<O7$hS<`Z0jBvLynGY5V9;EbW3ZNX}KU}nx=0f!*!639LKl7s%b&A5F&(*OxM(H!?ryL9-OtnThBncZ}_I~BV?G44!-NAYarV&'
        'Z3KE<B;?_Do8>rsu9Spv(Gz&691fZ-IO5~gO<4aTa4Cw7V^L0=kBk2Ox(Y*eC(5B9Nkv)TOiA8rH<MNzigM}_Z6|Qg<k!5M(u}};'
        'U%y#ff{?|KLhNk0`wC5I5x-q-Ft`c6v-2RgbD`U6k*v2-2z0HGR+ozJ#SEU~c@rWZ4%%@?;HQ$1RY^wWt?jmm)QShBXpQ4Rg+mI5'
        '6^=+8<amo3k4hZkcubAQ)p)Ct+a_^@;|aCCUE)@bcPQK`af0JrYJF14?^g3uO3xlO-mCQQlemlH_au&SykG5qU*aUk2bBJUO8$_<'
        '{TzQFaW}_@mA)eqw{Ton`==!y<oKw>eH?$N^c_?3A4weL__*@xgv4VU&q%Cud{W{ej!!9jA4}ZB@oDAntkR<?zZ(*VIo6eZL*gvQ'
        'ro>YmTM|!jY%4pC#A%LQiHAA%l)p&X^Cj-(_!AZ9rxJH^d`8(lD{-9T&s5y!)cMRQ`xhnZ94{$<nZzZIS0!HL_^w36@dJr796wZc'
        'pQw1ANqoxjbA>MyzU<?ru>nQ)S7fFls3I3DvQ!aPk=2Uat;mClJgmr*iae{x^NPHv$V)}KP;lvLN;+$uPt7%DqCk@xY14vc0x~5^'
        'AZ=?<I7m75T1yO?y?*1pE!dCjKn`6YqG?7$QqV};D|ZApWGf2NBrAeA5)0*IkSE<Nq_EJUK}w+Jm#k5=(?*Zn>=v`Kbj;prcWiS-'
        'Z#B|x6ADHEO&!t`RIc~Ze6|fOg=UR@A8q7uL-x@|zu+`p>!X^X=~`b3Do?;j4rVji{-EEj#32>;*iY<d<}!b+X0S8toNBadrDc&s'
        'QQTSnSN(z2Ie0*%{bhm2;K&y6Q+65ti|;DQyGrtZt0e5v#`4kcy)wI?aInX>#n;pDZex=<`{f?{b%Fg>=Km%2VXd+D)^Dh{eq;Tu'
        '-+1-bZ>+ubp#~UL6=1(Z#+RoqR1)<tNis-cFq7Al8+B4o<(7Kfsps%UqMCSnarpBU`-A<pG5^`4h5kWk{{RT1XG`J?000'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
