# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /tmp/yakut-dsdl-zmn42v0l/public_regulated_data_types-master/reg/drone/physics/kinematics/cartesian/PoseVar.0.1.uavcan
#
# Generated at:  2021-09-29 15:15:52.581478 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     reg.drone.physics.kinematics.cartesian.PoseVar
# Version:       0.1
#
# pylint: skip-file

from __future__ import annotations
import numpy as _np_
import typing as _ty_
import pydsdl as _pydsdl_
import pyuavcan.dsdl as _dsdl_
import reg.drone.physics.kinematics.cartesian


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class PoseVar_0_1(_dsdl_.CompositeObject):
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 value:          _ty_.Optional[reg.drone.physics.kinematics.cartesian.Pose_0_1] = None,
                 covariance_urt: _ty_.Optional[_ty_.Union[_np_.ndarray, _ty_.List[float]]] = None) -> None:
        """
        reg.drone.physics.kinematics.cartesian.PoseVar.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param value:          reg.drone.physics.kinematics.cartesian.Pose.0.1 value
        :param covariance_urt: saturated float16[21] covariance_urt
        """
        self._value:          reg.drone.physics.kinematics.cartesian.Pose_0_1
        self._covariance_urt: _np_.ndarray

        if value is None:
            self.value = reg.drone.physics.kinematics.cartesian.Pose_0_1()
        elif isinstance(value, reg.drone.physics.kinematics.cartesian.Pose_0_1):
            self.value = value
        else:
            raise ValueError(f'value: expected reg.drone.physics.kinematics.cartesian.Pose_0_1 '
                             f'got {type(value).__name__}')

        if covariance_urt is None:
            self.covariance_urt = _np_.zeros(21, _np_.float16)
        else:
            if isinstance(covariance_urt, _np_.ndarray) and covariance_urt.dtype == _np_.float16 and covariance_urt.ndim == 1 and covariance_urt.size == 21:
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._covariance_urt = covariance_urt
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                covariance_urt = _np_.array(covariance_urt, _np_.float16).flatten()
                if not covariance_urt.size == 21:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'covariance_urt: invalid array length: not {covariance_urt.size} == 21')
                self._covariance_urt = covariance_urt
            assert isinstance(self._covariance_urt, _np_.ndarray)
            assert self._covariance_urt.dtype == _np_.float16
            assert self._covariance_urt.ndim == 1
            assert len(self._covariance_urt) == 21

    @property
    def value(self) -> reg.drone.physics.kinematics.cartesian.Pose_0_1:
        """
        reg.drone.physics.kinematics.cartesian.Pose.0.1 value
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._value

    @value.setter
    def value(self, x: reg.drone.physics.kinematics.cartesian.Pose_0_1) -> None:
        if isinstance(x, reg.drone.physics.kinematics.cartesian.Pose_0_1):
            self._value = x
        else:
            raise ValueError(f'value: expected reg.drone.physics.kinematics.cartesian.Pose_0_1 got {type(x).__name__}')

    @property
    def covariance_urt(self) -> _np_.ndarray:
        """
        saturated float16[21] covariance_urt
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._covariance_urt

    @covariance_urt.setter
    def covariance_urt(self, x: _ty_.Union[_np_.ndarray, _ty_.List[float]]) -> None:
        if isinstance(x, _np_.ndarray) and x.dtype == _np_.float16 and x.ndim == 1 and x.size == 21:
            # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
            self._covariance_urt = x
        else:
            # Last resort, slow construction of a new array. New memory may be allocated.
            x = _np_.array(x, _np_.float16).flatten()
            if not x.size == 21:  # Length cannot be checked before casting and flattening
                raise ValueError(f'covariance_urt: invalid array length: not {x.size} == 21')
            self._covariance_urt = x
        assert isinstance(self._covariance_urt, _np_.ndarray)
        assert self._covariance_urt.dtype == _np_.float16
        assert self._covariance_urt.ndim == 1
        assert len(self._covariance_urt) == 21

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: PoseVar_0_1._SerializerTypeVar_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.value._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        assert len(self.covariance_urt) == 21, 'self.covariance_urt: saturated float16[21]'
        _ser_.add_aligned_array_of_standard_bit_length_primitives(self.covariance_urt)
        _ser_.pad_to_alignment(8)
        assert 656 <= (_ser_.current_bit_length - _base_offset_) <= 656, \
            'Bad serialization of reg.drone.physics.kinematics.cartesian.PoseVar.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: PoseVar_0_1._DeserializerTypeVar_) -> PoseVar_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "value"
        _des_.pad_to_alignment(8)
        _f0_ = reg.drone.physics.kinematics.cartesian.Pose_0_1._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "covariance_urt"
        _f1_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.float16, 21)
        assert len(_f1_) == 21, 'saturated float16[21]'
        self = PoseVar_0_1(
            value=_f0_,
            covariance_urt=_f1_)
        _des_.pad_to_alignment(8)
        assert 656 <= (_des_.consumed_bit_length - _base_offset_) <= 656, \
            'Bad deserialization of reg.drone.physics.kinematics.cartesian.PoseVar.0.1'
        assert isinstance(self, PoseVar_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'value=%s' % self.value,
            'covariance_urt=%s' % _np_.array2string(self.covariance_urt, separator=',', edgeitems=10, threshold=1024, max_line_width=10240000),
        ])
        return f'reg.drone.physics.kinematics.cartesian.PoseVar.0.1({_o_0_})'

    _EXTENT_BYTES_ = 82

    _MODEL_: _pydsdl_.StructureType = _dsdl_.CompositeObject._restore_constant_(
        'ABzY8D1%gC0{`uq-EZ606~JZLisg?uj$<cok|s==C5{tI{3g})BVDi{!>v;<?NX;(!%-6BOGgp~lJcxz8Q6zz4nSZ8$^qFP_mn;C'
        'Z4Y@_k!{$P0RskXFZmPlC**PGN{5oo*h`BJeW?V<=aBc_b1$j;J0I7<$gh5JHq-fpC!6i6SFIHc&vI?EX5Tf-HLGA$oO;voY~PB*'
        '{qOs3tKzp@>w|XFia(3be-ht|7s8y;Fze7>aILjM)pZ(Hp-J1GUGWNc?1oi0eWq4S*S9>|Y!p@;&$?l{ahNwYEZ4K0Mocr|=nd3A'
        'i%EtI{XG684krxL_g%Z(f|2pZFx4K5?DdMn+!foZRr`w@H>##@8a`Vw&313nTzKJ2tTm>ibSzmDorHDJX*6_bo5_n`*reU?U$D8W'
        '$x|(JqXI)byU=RbexYVH)_hv{(5_lHtcvfrQrFH9$-HPMJhsQna$U0>hqG7gO{@BD$KpHe*3KVwzhTv^y4CQzuWqk5-*oM|?b{pB'
        'W9&-JG5wuZCXBM}8{K8c<P!WE71Q&Lx>JR>Du#zwlHqJv;WD%>vnI9$K8>%#A`Q<s8&%V-Za1_AcIxIDypdLwO?=xmD?V%;54O}5'
        ')WOE8GL*>(T1it&k|4>tDoTQ)@wy-@q9%)yCJ7oZONy$MbY9~@Dx#vxa;c;$CA}nQvZm@h8zZW`rt`e0E0V6MyrP#BMOP(JQ&nBl'
        '1x-+7US@YCMUW+3lvOY<OQIl&s;-ydQqZBZF2fY?<t0VZ6hSTNDi5;>yrQX!B8a-kYpN(Ka*5|lyrh>T5eCb=29xOuuglO$l1gBk'
        '%_fPG3cW;8EXlf{Dmt$#N=brQMG2l39uXd07gdp$1zFbM;bE~7tX30rz9f{yQc2eZQQ=|jyr>GgEQqoWc2zxQFTYg|$KdB`nibn`'
        '$7DDhG0HV~#b=Y9(EmkXQ~2rYIGp^B?RWRr`*4YSA{;iHW*l;R8S&cnvQx7wad>FisyndH*su9s({fGN@BN*%&!|uvK&Q*$%yp}2'
        '`S$Mpvc?@)JG~D54qR*1YNp#xcLG}*X02t#zl;~irN}G8laCm6yAhMeOfff^GRk&st7bB*WQcXmL?nxH8084c9Fy6I?8EC(CWj-E'
        '$Lle?9>;zYOy(joiS7HD9FNEp$^%SJMr0b>4`TlrynhJo%;NPN+CR+XbVQCYnUBakj(>&8gAqB3_K#uz<4n#+<W(kTB60%lon&%f'
        'L^vFOipgUUInCtZh`fgO&S3v<F*zEMv$(EvOrD9z0+U=s&NF#DB8xcR1tw=BauL_NgmwzJ?jn;T5#e!ufyt$ah)ga<L}Kz>L}Z*t'
        'Ve(W&R3=YEM8oy!IA4j$xrn@u&-ra84@Be*ocB#8$0G6;KKI-BelFqsSDEA^vWn}aOs+;`lgX<Q*<w<U$O9%9BJvRDeT2{RgvrMd'
        'd5ZEG%I96VoF77EK2a7DMNgEgiL#m~G*LDaWh+r0B+A1?d6Xzm66I;4JWG`4sI<W0TANL?(FxFaugpM!AeF0Iz6H^I#Hc!eZ3Y~N'
        '86Mgexs7tWn<3nb>0`R+K~$((P1mZJzEzFyhf~IF7K)6f<NAhOjjx3V4bN%06$=__meDl9=ZCcD*PF$*d8g$sG1swlx89J&4Zc=v'
        'w#wiz3<$q~Cz$L<d~c}^A;ofw-8fqG>>`V!#je9CZi}M@p}-fqy}<Jr)bwClmxVuwcN=!aitp1u(Ld8G^m`qjLEokCVW91}mKC#F'
        'wHs?M_#bFpfjp<#ZH`GEUfC`3m>Tf?@xYS|JjplBlhDu8?xP!f8C~Ew=wI%|>jLC$^t4C+dY}I78vT3deHHYft=P%Ri<p%c`&oIh'
        'mz5VgSvmLsA@KtAA3%J#csc38RUF3!h+!I!b8d4c*JMLDyTN&oBUy!bcjxf0p7u}r?*ab<{s;W;;6L9vUg#VGbX>r$h49H#A#66*'
        'p!)oN3t)5`ow0kC!L)#yKxNc4!cm>RLEqe>Z_#(ca}v})IuvZGD(Q-->rnj(tTYsKsH0?7sEG=cVOSN>?~;+-QU3t7523?#db8W%'
        'N8OFudD>ef0P=(XL4Gzx{xFiCMe?&L^0P>O9?2g?^7Bak1d^Xc^7AS3$B_Iil0Svy=aKv@l0Spw??>|UNd7RAKab?kBKgxu{v?v0'
        'NAgEf<iCpKA4T$yAo;UM{y`*v3dx^9^7BZ34$03V`HM*Y0+N3g$v=bSpGNXIB>x1Ge;mm_isa8D`G=AGStNf3$)85@r;z+fB!3*q'
        '&m;N!ko*xOKbs<7NAeet{COllkK_kPet_f$NPd9i2S|Q^<OfK8kdPlF<Od1)K|+3zkRK%E2MPH>LVl2tA0*@l3Hd=nevptKB;*GP'
        '`9VT{kdPnr$shU2X8Z1rz(14CWY&KR(Z3)2Z~q_D{*Kou_PxgTq`wpH_e$`4F?{{^EHz2O_yFbs%mbLaFi$wH4dt@AEs|S|>4o)Q'
        'Gh~jgw;9{N0ln2@+x=Sdde3?xt$!)!JBs_c%T9xxRWx=zie!hR>?G2)8th*byLt_6yVn>b|AXZJ8=w5I9|3n@dBDT+r6FptKVLkK'
        'W>Rr9mm(sEL}ZYNp;R2rBN3BGL@q_d6cRCoL`)+Q86+ZyL`)(PbE!Bwi$vs+h$BeEBoZ-%M9d-)<0&GJAQ4kYL=K7IkcfFCVj79a'
        'BM})S;uI2b6p1*5L`)(PIV9pD5^**aM~@;Avq;1g5|KwDvPgu8L@Xf@3rNIkNW=*w;uR!f7Ku23M2sU5xfBr`5}_jzc_d;5iQtil'
        'X(ZwS60wCuY$6d9iC9G<t|mn22@wkk5%UQVc_adMBqGt#XiwYhX<I$*K~H<w(;oG-Cq3<HPkYwWo+nzDj*eDNg2e!i0UQH3QgG~c'
        'aQu?<p6Tu9JvmiTc)5R?GxxI7oVnC#&NQCpEUz#+S2}biaC-FfYrQ2-Rh$jeg*3Ec87<d`wXXgLQo$cIA%|RY?KSFiK5K@ulpQJi'
        ')Z+RhILKvPd-L`2aqh*>54-=J;%>WU-TJt9x08u-3uUL;K96nb(Y|Xoyjmxf<;<GXSmVr1+hZ-R<KykJ)ABpFcbR$><xP|y?R7sj'
        '_QKMa`;4!0$;lua{?qZBJFoke>$gO1w@-c1HLK$vrOd4MpA*gQxaMB^0i(A>FuP+|+$(n;4nwYgaQ%-U)_*s=z1(SiP36uF)BP$H'
        '&-$m3nsqMLw?NygrukX6Q_~Ek!&GPgum52<N$;X8G{K*wsTbPP4UCz>e*uiN8o!bz000'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
