#
# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2021-09-29 15:15:52.663659 UTC
# Namespace:     reg.drone.service.battery
#

from reg.drone.service.battery.Error_0_1 import Error_0_1 as Error_0_1
from reg.drone.service.battery.Parameters_0_3 import Parameters_0_3 as Parameters_0_3
from reg.drone.service.battery.Parameters_0_2 import Parameters_0_2 as Parameters_0_2
from reg.drone.service.battery.Parameters_0_1 import Parameters_0_1 as Parameters_0_1
from reg.drone.service.battery.Status_0_2 import Status_0_2 as Status_0_2
from reg.drone.service.battery.Status_0_1 import Status_0_1 as Status_0_1
from reg.drone.service.battery.Technology_0_1 import Technology_0_1 as Technology_0_1
from reg.drone.service.battery.__0_1 import __0_1 as __0_1
