# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /tmp/yakut-dsdl-zmn42v0l/public_regulated_data_types-master/reg/drone/service/battery/Parameters.0.1.uavcan
#
# Generated at:  2021-09-29 15:15:52.686899 UTC
# Is deprecated: yes
# Fixed port ID: None
# Full name:     reg.drone.service.battery.Parameters
# Version:       0.1
#
# pylint: skip-file

from __future__ import annotations
import numpy as _np_
import typing as _ty_
import pydsdl as _pydsdl_
import pyuavcan.dsdl as _dsdl_
import warnings as _warnings_
import reg.drone.service.battery
import uavcan.si.unit.electric_charge
import uavcan.si.unit.electric_current
import uavcan.si.unit.mass
import uavcan.si.unit.voltage


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Parameters_0_1(_dsdl_.CompositeObject):
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 unique_id:                   _ty_.Optional[_ty_.Union[int, _np_.uint64]] = None,
                 mass:                        _ty_.Optional[uavcan.si.unit.mass.Scalar_1_0] = None,
                 design_capacity:             _ty_.Optional[uavcan.si.unit.electric_charge.Scalar_1_0] = None,
                 design_cell_voltage_min_max: _ty_.Optional[_ty_.Union[_np_.ndarray, _ty_.List[uavcan.si.unit.voltage.Scalar_1_0]]] = None,
                 discharge_current:           _ty_.Optional[uavcan.si.unit.electric_current.Scalar_1_0] = None,
                 discharge_current_burst:     _ty_.Optional[uavcan.si.unit.electric_current.Scalar_1_0] = None,
                 charge_current:              _ty_.Optional[uavcan.si.unit.electric_current.Scalar_1_0] = None,
                 charge_current_fast:         _ty_.Optional[uavcan.si.unit.electric_current.Scalar_1_0] = None,
                 charge_termination_treshold: _ty_.Optional[uavcan.si.unit.electric_current.Scalar_1_0] = None,
                 charge_voltage:              _ty_.Optional[uavcan.si.unit.voltage.Scalar_1_0] = None,
                 cycle_count:                 _ty_.Optional[_ty_.Union[int, _np_.uint16]] = None,
                 series_cell_count:           _ty_.Optional[_ty_.Union[int, _np_.uint8]] = None,
                 state_of_health_pct:         _ty_.Optional[_ty_.Union[int, _np_.uint8]] = None,
                 technology:                  _ty_.Optional[reg.drone.service.battery.Technology_0_1] = None) -> None:
        """
        reg.drone.service.battery.Parameters.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param unique_id:                   truncated uint64 unique_id
        :param mass:                        uavcan.si.unit.mass.Scalar.1.0 mass
        :param design_capacity:             uavcan.si.unit.electric_charge.Scalar.1.0 design_capacity
        :param design_cell_voltage_min_max: uavcan.si.unit.voltage.Scalar.1.0[2] design_cell_voltage_min_max
        :param discharge_current:           uavcan.si.unit.electric_current.Scalar.1.0 discharge_current
        :param discharge_current_burst:     uavcan.si.unit.electric_current.Scalar.1.0 discharge_current_burst
        :param charge_current:              uavcan.si.unit.electric_current.Scalar.1.0 charge_current
        :param charge_current_fast:         uavcan.si.unit.electric_current.Scalar.1.0 charge_current_fast
        :param charge_termination_treshold: uavcan.si.unit.electric_current.Scalar.1.0 charge_termination_treshold
        :param charge_voltage:              uavcan.si.unit.voltage.Scalar.1.0 charge_voltage
        :param cycle_count:                 saturated uint16 cycle_count
        :param series_cell_count:           saturated uint8 series_cell_count
        :param state_of_health_pct:         saturated uint7 state_of_health_pct
        :param technology:                  reg.drone.service.battery.Technology.0.1 technology
        """
        _warnings_.warn('Data type reg.drone.service.battery.Parameters.0.1 is deprecated', DeprecationWarning)

        self._unique_id:                   int
        self._mass:                        uavcan.si.unit.mass.Scalar_1_0
        self._design_capacity:             uavcan.si.unit.electric_charge.Scalar_1_0
        self._design_cell_voltage_min_max: _np_.ndarray
        self._discharge_current:           uavcan.si.unit.electric_current.Scalar_1_0
        self._discharge_current_burst:     uavcan.si.unit.electric_current.Scalar_1_0
        self._charge_current:              uavcan.si.unit.electric_current.Scalar_1_0
        self._charge_current_fast:         uavcan.si.unit.electric_current.Scalar_1_0
        self._charge_termination_treshold: uavcan.si.unit.electric_current.Scalar_1_0
        self._charge_voltage:              uavcan.si.unit.voltage.Scalar_1_0
        self._cycle_count:                 int
        self._series_cell_count:           int
        self._state_of_health_pct:         int
        self._technology:                  reg.drone.service.battery.Technology_0_1

        self.unique_id = unique_id if unique_id is not None else 0

        if mass is None:
            self.mass = uavcan.si.unit.mass.Scalar_1_0()
        elif isinstance(mass, uavcan.si.unit.mass.Scalar_1_0):
            self.mass = mass
        else:
            raise ValueError(f'mass: expected uavcan.si.unit.mass.Scalar_1_0 '
                             f'got {type(mass).__name__}')

        if design_capacity is None:
            self.design_capacity = uavcan.si.unit.electric_charge.Scalar_1_0()
        elif isinstance(design_capacity, uavcan.si.unit.electric_charge.Scalar_1_0):
            self.design_capacity = design_capacity
        else:
            raise ValueError(f'design_capacity: expected uavcan.si.unit.electric_charge.Scalar_1_0 '
                             f'got {type(design_capacity).__name__}')

        if design_cell_voltage_min_max is None:
            self.design_cell_voltage_min_max = _np_.array([uavcan.si.unit.voltage.Scalar_1_0() for _ in range(2)], object)
        else:
            if isinstance(design_cell_voltage_min_max, _np_.ndarray) and design_cell_voltage_min_max.dtype == object and design_cell_voltage_min_max.ndim == 1 and design_cell_voltage_min_max.size == 2:
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._design_cell_voltage_min_max = design_cell_voltage_min_max
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                design_cell_voltage_min_max = _np_.array(design_cell_voltage_min_max, object).flatten()
                if not design_cell_voltage_min_max.size == 2:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'design_cell_voltage_min_max: invalid array length: not {design_cell_voltage_min_max.size} == 2')
                self._design_cell_voltage_min_max = design_cell_voltage_min_max
            assert isinstance(self._design_cell_voltage_min_max, _np_.ndarray)
            assert self._design_cell_voltage_min_max.dtype == object
            assert self._design_cell_voltage_min_max.ndim == 1
            assert len(self._design_cell_voltage_min_max) == 2

        if discharge_current is None:
            self.discharge_current = uavcan.si.unit.electric_current.Scalar_1_0()
        elif isinstance(discharge_current, uavcan.si.unit.electric_current.Scalar_1_0):
            self.discharge_current = discharge_current
        else:
            raise ValueError(f'discharge_current: expected uavcan.si.unit.electric_current.Scalar_1_0 '
                             f'got {type(discharge_current).__name__}')

        if discharge_current_burst is None:
            self.discharge_current_burst = uavcan.si.unit.electric_current.Scalar_1_0()
        elif isinstance(discharge_current_burst, uavcan.si.unit.electric_current.Scalar_1_0):
            self.discharge_current_burst = discharge_current_burst
        else:
            raise ValueError(f'discharge_current_burst: expected uavcan.si.unit.electric_current.Scalar_1_0 '
                             f'got {type(discharge_current_burst).__name__}')

        if charge_current is None:
            self.charge_current = uavcan.si.unit.electric_current.Scalar_1_0()
        elif isinstance(charge_current, uavcan.si.unit.electric_current.Scalar_1_0):
            self.charge_current = charge_current
        else:
            raise ValueError(f'charge_current: expected uavcan.si.unit.electric_current.Scalar_1_0 '
                             f'got {type(charge_current).__name__}')

        if charge_current_fast is None:
            self.charge_current_fast = uavcan.si.unit.electric_current.Scalar_1_0()
        elif isinstance(charge_current_fast, uavcan.si.unit.electric_current.Scalar_1_0):
            self.charge_current_fast = charge_current_fast
        else:
            raise ValueError(f'charge_current_fast: expected uavcan.si.unit.electric_current.Scalar_1_0 '
                             f'got {type(charge_current_fast).__name__}')

        if charge_termination_treshold is None:
            self.charge_termination_treshold = uavcan.si.unit.electric_current.Scalar_1_0()
        elif isinstance(charge_termination_treshold, uavcan.si.unit.electric_current.Scalar_1_0):
            self.charge_termination_treshold = charge_termination_treshold
        else:
            raise ValueError(f'charge_termination_treshold: expected uavcan.si.unit.electric_current.Scalar_1_0 '
                             f'got {type(charge_termination_treshold).__name__}')

        if charge_voltage is None:
            self.charge_voltage = uavcan.si.unit.voltage.Scalar_1_0()
        elif isinstance(charge_voltage, uavcan.si.unit.voltage.Scalar_1_0):
            self.charge_voltage = charge_voltage
        else:
            raise ValueError(f'charge_voltage: expected uavcan.si.unit.voltage.Scalar_1_0 '
                             f'got {type(charge_voltage).__name__}')

        self.cycle_count = cycle_count if cycle_count is not None else 0

        self.series_cell_count = series_cell_count if series_cell_count is not None else 0

        self.state_of_health_pct = state_of_health_pct if state_of_health_pct is not None else 0

        if technology is None:
            self.technology = reg.drone.service.battery.Technology_0_1()
        elif isinstance(technology, reg.drone.service.battery.Technology_0_1):
            self.technology = technology
        else:
            raise ValueError(f'technology: expected reg.drone.service.battery.Technology_0_1 '
                             f'got {type(technology).__name__}')

    @property
    def unique_id(self) -> int:
        """
        truncated uint64 unique_id
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._unique_id

    @unique_id.setter
    def unique_id(self, x: _ty_.Union[int, _np_.uint64]) -> None:
        """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
        x = int(x)
        if 0 <= x <= 18446744073709551615:
            self._unique_id = x
        else:
            raise ValueError(f'unique_id: value {x} is not in [0, 18446744073709551615]')

    @property
    def mass(self) -> uavcan.si.unit.mass.Scalar_1_0:
        """
        uavcan.si.unit.mass.Scalar.1.0 mass
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._mass

    @mass.setter
    def mass(self, x: uavcan.si.unit.mass.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.mass.Scalar_1_0):
            self._mass = x
        else:
            raise ValueError(f'mass: expected uavcan.si.unit.mass.Scalar_1_0 got {type(x).__name__}')

    @property
    def design_capacity(self) -> uavcan.si.unit.electric_charge.Scalar_1_0:
        """
        uavcan.si.unit.electric_charge.Scalar.1.0 design_capacity
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._design_capacity

    @design_capacity.setter
    def design_capacity(self, x: uavcan.si.unit.electric_charge.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.electric_charge.Scalar_1_0):
            self._design_capacity = x
        else:
            raise ValueError(f'design_capacity: expected uavcan.si.unit.electric_charge.Scalar_1_0 got {type(x).__name__}')

    @property
    def design_cell_voltage_min_max(self) -> _np_.ndarray:
        """
        uavcan.si.unit.voltage.Scalar.1.0[2] design_cell_voltage_min_max
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._design_cell_voltage_min_max

    @design_cell_voltage_min_max.setter
    def design_cell_voltage_min_max(self, x: _ty_.Union[_np_.ndarray, _ty_.List[uavcan.si.unit.voltage.Scalar_1_0]]) -> None:
        if isinstance(x, _np_.ndarray) and x.dtype == object and x.ndim == 1 and x.size == 2:
            # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
            self._design_cell_voltage_min_max = x
        else:
            # Last resort, slow construction of a new array. New memory may be allocated.
            x = _np_.array(x, object).flatten()
            if not x.size == 2:  # Length cannot be checked before casting and flattening
                raise ValueError(f'design_cell_voltage_min_max: invalid array length: not {x.size} == 2')
            self._design_cell_voltage_min_max = x
        assert isinstance(self._design_cell_voltage_min_max, _np_.ndarray)
        assert self._design_cell_voltage_min_max.dtype == object
        assert self._design_cell_voltage_min_max.ndim == 1
        assert len(self._design_cell_voltage_min_max) == 2

    @property
    def discharge_current(self) -> uavcan.si.unit.electric_current.Scalar_1_0:
        """
        uavcan.si.unit.electric_current.Scalar.1.0 discharge_current
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._discharge_current

    @discharge_current.setter
    def discharge_current(self, x: uavcan.si.unit.electric_current.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.electric_current.Scalar_1_0):
            self._discharge_current = x
        else:
            raise ValueError(f'discharge_current: expected uavcan.si.unit.electric_current.Scalar_1_0 got {type(x).__name__}')

    @property
    def discharge_current_burst(self) -> uavcan.si.unit.electric_current.Scalar_1_0:
        """
        uavcan.si.unit.electric_current.Scalar.1.0 discharge_current_burst
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._discharge_current_burst

    @discharge_current_burst.setter
    def discharge_current_burst(self, x: uavcan.si.unit.electric_current.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.electric_current.Scalar_1_0):
            self._discharge_current_burst = x
        else:
            raise ValueError(f'discharge_current_burst: expected uavcan.si.unit.electric_current.Scalar_1_0 got {type(x).__name__}')

    @property
    def charge_current(self) -> uavcan.si.unit.electric_current.Scalar_1_0:
        """
        uavcan.si.unit.electric_current.Scalar.1.0 charge_current
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._charge_current

    @charge_current.setter
    def charge_current(self, x: uavcan.si.unit.electric_current.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.electric_current.Scalar_1_0):
            self._charge_current = x
        else:
            raise ValueError(f'charge_current: expected uavcan.si.unit.electric_current.Scalar_1_0 got {type(x).__name__}')

    @property
    def charge_current_fast(self) -> uavcan.si.unit.electric_current.Scalar_1_0:
        """
        uavcan.si.unit.electric_current.Scalar.1.0 charge_current_fast
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._charge_current_fast

    @charge_current_fast.setter
    def charge_current_fast(self, x: uavcan.si.unit.electric_current.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.electric_current.Scalar_1_0):
            self._charge_current_fast = x
        else:
            raise ValueError(f'charge_current_fast: expected uavcan.si.unit.electric_current.Scalar_1_0 got {type(x).__name__}')

    @property
    def charge_termination_treshold(self) -> uavcan.si.unit.electric_current.Scalar_1_0:
        """
        uavcan.si.unit.electric_current.Scalar.1.0 charge_termination_treshold
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._charge_termination_treshold

    @charge_termination_treshold.setter
    def charge_termination_treshold(self, x: uavcan.si.unit.electric_current.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.electric_current.Scalar_1_0):
            self._charge_termination_treshold = x
        else:
            raise ValueError(f'charge_termination_treshold: expected uavcan.si.unit.electric_current.Scalar_1_0 got {type(x).__name__}')

    @property
    def charge_voltage(self) -> uavcan.si.unit.voltage.Scalar_1_0:
        """
        uavcan.si.unit.voltage.Scalar.1.0 charge_voltage
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._charge_voltage

    @charge_voltage.setter
    def charge_voltage(self, x: uavcan.si.unit.voltage.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.voltage.Scalar_1_0):
            self._charge_voltage = x
        else:
            raise ValueError(f'charge_voltage: expected uavcan.si.unit.voltage.Scalar_1_0 got {type(x).__name__}')

    @property
    def cycle_count(self) -> int:
        """
        saturated uint16 cycle_count
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._cycle_count

    @cycle_count.setter
    def cycle_count(self, x: _ty_.Union[int, _np_.uint16]) -> None:
        """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
        x = int(x)
        if 0 <= x <= 65535:
            self._cycle_count = x
        else:
            raise ValueError(f'cycle_count: value {x} is not in [0, 65535]')

    @property
    def series_cell_count(self) -> int:
        """
        saturated uint8 series_cell_count
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._series_cell_count

    @series_cell_count.setter
    def series_cell_count(self, x: _ty_.Union[int, _np_.uint8]) -> None:
        """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
        x = int(x)
        if 0 <= x <= 255:
            self._series_cell_count = x
        else:
            raise ValueError(f'series_cell_count: value {x} is not in [0, 255]')

    @property
    def state_of_health_pct(self) -> int:
        """
        saturated uint7 state_of_health_pct
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._state_of_health_pct

    @state_of_health_pct.setter
    def state_of_health_pct(self, x: _ty_.Union[int, _np_.uint8]) -> None:
        """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
        x = int(x)
        if 0 <= x <= 127:
            self._state_of_health_pct = x
        else:
            raise ValueError(f'state_of_health_pct: value {x} is not in [0, 127]')

    @property
    def technology(self) -> reg.drone.service.battery.Technology_0_1:
        """
        reg.drone.service.battery.Technology.0.1 technology
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._technology

    @technology.setter
    def technology(self, x: reg.drone.service.battery.Technology_0_1) -> None:
        if isinstance(x, reg.drone.service.battery.Technology_0_1):
            self._technology = x
        else:
            raise ValueError(f'technology: expected reg.drone.service.battery.Technology_0_1 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: Parameters_0_1._SerializerTypeVar_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.add_aligned_u64(self.unique_id)
        _ser_.pad_to_alignment(8)
        self.mass._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.design_capacity._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert len(self.design_cell_voltage_min_max) == 2, 'self.design_cell_voltage_min_max: uavcan.si.unit.voltage.Scalar.1.0[2]'
        # Element offset: concat(pad(8,concat(pad(8,concat(pad(8,concat(pad(1,pad(8,{0})),{64})),pad(8,{32}))),pad(8,{32}))),repeat(<=1,pad(8,{32})))
        for _elem0_ in self.design_cell_voltage_min_max:
            _ser_.pad_to_alignment(8)
            _elem0_._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        _ser_.pad_to_alignment(8)
        self.discharge_current._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.discharge_current_burst._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.charge_current._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.charge_current_fast._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.charge_termination_treshold._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.charge_voltage._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.add_aligned_u16(max(min(self.cycle_count, 65535), 0))
        _ser_.skip_bits(8)
        _ser_.add_aligned_u8(max(min(self.series_cell_count, 255), 0))
        _ser_.add_aligned_unsigned(max(min(self.state_of_health_pct, 127), 0), 7)
        _ser_.skip_bits(1)
        _ser_.pad_to_alignment(8)
        self.technology._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 432 <= (_ser_.current_bit_length - _base_offset_) <= 432, \
            'Bad serialization of reg.drone.service.battery.Parameters.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: Parameters_0_1._DeserializerTypeVar_) -> Parameters_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "unique_id"
        _f0_ = _des_.fetch_aligned_u64()
        # Temporary _f1_ holds the value of "mass"
        _des_.pad_to_alignment(8)
        _f1_ = uavcan.si.unit.mass.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f2_ holds the value of "design_capacity"
        _des_.pad_to_alignment(8)
        _f2_ = uavcan.si.unit.electric_charge.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f3_ holds the value of "design_cell_voltage_min_max"
        _des_.pad_to_alignment(8)
        _f3_ = _np_.empty(2, object)
        for _i0_ in range(2):
            _des_.pad_to_alignment(8)
            _e0_ = uavcan.si.unit.voltage.Scalar_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            _f3_[_i0_] = _e0_
        assert len(_f3_) == 2, 'uavcan.si.unit.voltage.Scalar.1.0[2]'
        _des_.pad_to_alignment(8)
        # Temporary _f4_ holds the value of "discharge_current"
        _des_.pad_to_alignment(8)
        _f4_ = uavcan.si.unit.electric_current.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f5_ holds the value of "discharge_current_burst"
        _des_.pad_to_alignment(8)
        _f5_ = uavcan.si.unit.electric_current.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f6_ holds the value of "charge_current"
        _des_.pad_to_alignment(8)
        _f6_ = uavcan.si.unit.electric_current.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f7_ holds the value of "charge_current_fast"
        _des_.pad_to_alignment(8)
        _f7_ = uavcan.si.unit.electric_current.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f8_ holds the value of "charge_termination_treshold"
        _des_.pad_to_alignment(8)
        _f8_ = uavcan.si.unit.electric_current.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f9_ holds the value of "charge_voltage"
        _des_.pad_to_alignment(8)
        _f9_ = uavcan.si.unit.voltage.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f10_ holds the value of "cycle_count"
        _f10_ = _des_.fetch_aligned_u16()
        _des_.skip_bits(8)
        # Temporary _f11_ holds the value of "series_cell_count"
        _f11_ = _des_.fetch_aligned_u8()
        # Temporary _f12_ holds the value of "state_of_health_pct"
        _f12_ = _des_.fetch_aligned_unsigned(7)
        _des_.skip_bits(1)
        # Temporary _f13_ holds the value of "technology"
        _des_.pad_to_alignment(8)
        _f13_ = reg.drone.service.battery.Technology_0_1._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = Parameters_0_1(
            unique_id=_f0_,
            mass=_f1_,
            design_capacity=_f2_,
            design_cell_voltage_min_max=_f3_,
            discharge_current=_f4_,
            discharge_current_burst=_f5_,
            charge_current=_f6_,
            charge_current_fast=_f7_,
            charge_termination_treshold=_f8_,
            charge_voltage=_f9_,
            cycle_count=_f10_,
            series_cell_count=_f11_,
            state_of_health_pct=_f12_,
            technology=_f13_)
        _des_.pad_to_alignment(8)
        assert 432 <= (_des_.consumed_bit_length - _base_offset_) <= 432, \
            'Bad deserialization of reg.drone.service.battery.Parameters.0.1'
        assert isinstance(self, Parameters_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'unique_id=%s' % self.unique_id,
            'mass=%s' % self.mass,
            'design_capacity=%s' % self.design_capacity,
            'design_cell_voltage_min_max=%s' % _np_.array2string(self.design_cell_voltage_min_max, separator=',', edgeitems=10, threshold=1024, max_line_width=10240000),
            'discharge_current=%s' % self.discharge_current,
            'discharge_current_burst=%s' % self.discharge_current_burst,
            'charge_current=%s' % self.charge_current,
            'charge_current_fast=%s' % self.charge_current_fast,
            'charge_termination_treshold=%s' % self.charge_termination_treshold,
            'charge_voltage=%s' % self.charge_voltage,
            'cycle_count=%s' % self.cycle_count,
            'series_cell_count=%s' % self.series_cell_count,
            'state_of_health_pct=%s' % self.state_of_health_pct,
            'technology=%s' % self.technology,
        ])
        return f'reg.drone.service.battery.Parameters.0.1({_o_0_})'

    _EXTENT_BYTES_ = 63

    _MODEL_: _pydsdl_.DelimitedType = _dsdl_.CompositeObject._restore_constant_(
        'ABzY8D1%gC0{`t>U2I&(b>>o}I9gKwvLsuvJ(ewnvdQI-D2a{}YblB{g(a7a$jGWv;p*<av%HtQKb!kQaa|ZtfHsiPEwVtih0!Oc'
        'XcHAR3Zp1c1L=cm1cgzwMT_>q4|y<}0tt|(qA1{pKJ=WqXLc`_OIcLoAVnoWXD;vjoqJ}!GiSb;z1#Eq(-*tszuNPasu`M2P76g~'
        '>yG`FUUEcEGkmw=hjt_ywY`^xW4rKZE>|m}@x8{GZ#Uj<4AypQw&#hUVRhB^E=56XL~$TC7wOeJ-GwGz3dBmz417=Ipqq8u5V?{b'
        'MIxx?7WDv%z+>2`F>M`E+xM`|zU%b-y+)y{koivI+l^Yk2DJja6h|U#+=33a(Y{%#QR}^83&(7!l+{c<(zOWn+^%{h!0)x!p~T^D'
        'c%i-G3G=EKi4_rS{=R;#WJj7Kyp_mm6!Orxp@)&?`le`DPuGqvs)n#yZW{9DF$=yZ^E-`ejoJ|{jC9Y`12f&wy|`p$YkOkP{#GnB'
        '+icW&G}AX4H~u}-)iuSTN@RzTZRn0u<w+^-#coLiJhJqN8@k6!g2$mSdE|4`E|*0hyvWug0VV8^iw)g~I1K?W2foYw$O3!kvPB_G'
        's8{v_?)WP!wztA7aR75cggJh-4E05`Vi;E{eh`Ix>C)0r((=0QfHtmPMGbHg!62Ai5Bc=9>GKnB&Tzk+9h}#_xU9?h5)@(d`78Xg'
        'z*#|mr1CGL&adz#IX*@Ck!Nz*<yKdr1!lm`Y;RqMLSBU5j9S_zesffXF6G~WKxOfRJQxHpoFl@J+YyJhz+yHIaG*Q9q6d+xqh@LL'
        'y6{Xt2<4Z7VYv<;=i%T*Jb)1d1JVef;jre!D0lrZ;y8QkG7J`!gfR|ffpys$X^5E-O!StW8!!Q$N~V}~-0GvJZ0(s?Ux$Wrp`C+a'
        'k8-XahPfq}2Rfi|z}i>H6uJ;6*1=niR0B`f_FQp%J=!#Pt>+5ddfs}W(1kP6dg&faURMWQqZnprZBIFX0RXKKmRIN*D%ZYzc4BmV'
        'a{TPX`SWKd&y7z`o_lq2Z0y45#MtE7iOGp`W9MHTKQ}Qk+Q4SzL}qI?%p^d0!#Z8-f_HlDa0<s-shW6+w;R?)YcvE<nW7R1Fp4l6'
        '@6`5bWqU)I8V(+Up;$Ypg?=0u0x}$-Rdj$%O&^Ke%1BjTi=$zL^zd7*H!;3G>Woz4l4Bbhc%az9CR_Lqhrxg_yd#NOM?!l9%{qc+'
        '9ZAfZ8_SL6l5Fq=nx%)(A7V)(Kh}81I&I|vpd|+^bz1q87Mh`8)c$v)HgL&~=H%Z?@F$H)ZI|X(8a2LMBVpAo`S2~E$-HoV@K!h|'
        '3l$OQksqWTvtilb^Q?v1{zct1VajhQWG!QEF?Qf1tL?eaf&^FNyN$sDuZJb@%$1~}MuEj8_*~ca8U>CI`UXDqq0<8cW7~xc*6XSl'
        'x+&d-X?MNQLx1<u-@7U8!?dSfV3fZH)82X^OZoknX6uCkOj*6K7t`JK!al0EpUNGe`Uf%HUoRZObYH!27}LG=!Vydd>V>B;?XMS('
        'QoF}6-BT|dr}m%5w69)xhWa@{`h1D{dlu7O^}=)1@AH^u>IF{yzmV9iaFWs&DSe63Q<R>j^vjeEQhJ8cmnnUP(jiKRDa}zjLg^@_'
        'W0a0ldX~}&O3zVxp3)1HPEz_RrC*`+HA=rq>DMTIozjbx<|&<}^aiCCr5lvqqx4-$?^F6Ar5{uJ38g=$^s^+LXBm1pt{w)}!=!qc'
        'RS!4RgQXre)WbdX@UD8euO2>B4<D<CPt?QD)x&4>5QFO!8x`G?;R?Mgg(d0zdeEDo=lf_GR)xrqV1>a~Z7a+WtUrbmBgEwEif*jw'
        'xcUxp;Rqvw*vU4+Az0hNo8ennbU3bjdc0vfHh>sbGT}lAy9{}-V$COOu#5t5%>kEc+D4>0ShGFhf&(#dy`u<B>9j5^+kikQThxo#'
        'UhJ)T{vB`Ib?H>wx|C=PPS>#XU`0H_5_NXdqI3b4BWu!n?J*XcKEsb4-z_!JEyGe{O~JDAFV^3O*7Q5p<)SrHbAE{{McapVSTw9R'
        '<N{&MS_S!uR?+%;(*s{`KHW?*Zz+dsY3OII+h7hI{+FJ3)hAx{|C?8}9<;gA{ieWZ8unP=9U-tsuljZLst|+NZtRkGO|YnZ89Gw%'
        'mJuHt9X-XD{MjKMR)hgjH~7U;RhDs6`;pB~u6AOZ4Q3GNRoK5>!O%1b<fib|=I!BL4IG4v(W2aLrab1eZ60&ocOv~)>nVG%&$OFd'
        'U54%D>O6>+vowE+&XT_Ii*=I9**&haeBvaZILZIJPO`SA<s1v$o$<6#J9JG{L}Yi~Ja%hqSao^zH^31{bmakE`A0xkrVU*^gsvV!'
        'SBB7)A$0W+y7myddI((ugf2$t>S;sQUP4!v(A7ui>LGMx2wg`AU55x=2MAsJ2wek&t}LO85xRC0x_Ss*-EHW4p3wCiq3c;f*Ov%g'
        'CkS275W1cwbR8#j9V2udC3HPS=sH5^I!x#~MCdw5=sG~?+E3`(N9fv1=o%n&^%J_Xgswe=E=K6;BXsR1boCOtdI(*+2wmNTt_-28'
        'i_n!Pbma+Mc|up7(3K~2<q2JRLRX&9l_zxN30-+YS6-njuh5lO=*lZ}<rTW}3SD`HuDn85UZE?m(3Mx{$}4o`6}s{YU3rDByh2xA'
        'p)21CK~AU;L^zH{3mS4Ek_Lfr<o9GaVtX<i85FQbgD}Lj!z3m-BX@04Dq>MZR6e%Lson75fl4+N)8zQfhVE7z@fH4C<GINpK9L)L'
        'n_u5<zjk`t{aPF#x%I0ILw1ASA`qJbkqg}rh>Uip0}=NN*|jB~`()epBqDhdk$hp>wu4RorvOJ_Z@H7zmjUch^w^f7S}6`ftWY~P'
        '6>&!Zpe37ij)%hVJ+tkwL^ZVU5j#BG)>~N*w=aBx3WG}l7ca?oEeb?v`AD{(uAQ9m%wfMgEQ=w}My-PDrc!OnzLD9aEctzC>c#=c'
        'S#IrSu`$Z!gPtF8aGArnR>-q3!Pi8U4}$H6&(P*K#pykC5osP*;WnAh)$lls2cnE#5|5=|c?xaU1`nBTRvsE+%_SGl%P!H8;AL>W'
        'd@1QNIo8T$uRtH3?+phc(GIuJ#CzJX${~w+l1%XO$xW(Te(adYVixsc8~b>oxd0uY1xQY|exqtQFrI!aN4@qQnum_&n(ORvbDD8k'
        'Jk0T%BJh#wOdoH8Av|#>$B{|3JtKh0Cy+@9pl#a~x$K+rv=z?*?Ff&u@Kms42iTO2>obx8(kjEIDBGS$X2jvz0G-opKCHHm*PiLj'
        'Kdk$BEX=M$lBOKM8VpvUEUa9oYqQq`9#Sd#*AGJ*4c}y{!LEjmXPK>`xMN2ae|`MiIT?uHIk6o^+Zvvw4Sz6{O(c;~)BJ;N=9jI4'
        '#XOi>pqTCPq}sN9^d)_~Bl|dvN8dv8%bF#0C$hAPA$!rj33xETw6`Q0ARyYpu7d?i0({3xjEBB>)-C+<Yj}2xftH-iqkJ&-;t&md'
        '2G5WoxB{?=J7-Y2)gOTmXae_v`U5n~D1&cy8mVyWA-5lv0TQ0?_$$>U*rJOL7;FuGzRi1+Q#$JUaE(pVnRIFfZCiI?d3NR+TJM@X'
        'm}n{@r#-lsmfwI;N^T9nK;m{0LCqH(35PH)xpo8-zY+tC1Mw}eFU%P0R_$3eb78`P`@<Qx>1GAHCR@^-=H$Hv0c0i#4RPsM{kN3K'
        'xBCn>cU4<jn4TNQFL`ke=C2*Q!ytXHiq6yV1KR|rIcE<;F=zY?bhG-4=I~*c-D5lKb2s#PY5E5CII(SyukaE~DuDQAC7@nM6~=a^'
        'LLaCwUtEx1eO2iIj(tV<0Q9iq@HbSC^WMVv8Q5s#R&qn!Ns0mlVNel`tyiyJ@2J@L&J^ptS=17>*iG=6!&7$9q1EvnTD*5^j#?d<'
        'a$>M5eC;+Z@6eEYL0>eaR-B!fp2HqyrQTa@Im~s}^*w1lHKKGh=TsxGwZ5kFx3I3E2PNO@WX-dqkEz|wB2DpyZMDO$AEFs}%=Ica'
        '<EZ+%O775v{YuHg!Yr!z#<nU}Aff?B02Z{W;14%CDylncu+Dj+qiW+jN9x@40&4ZzTyyG|VC~=p5W~kob*fyRaN<R!)fkqElZ1+4'
        'K=sKEn(Ttb;W1RXvWTj1rHUQktslz|D;8dJ0<>NciwhH-`y1PNf5rJ}?C+H7&$Ep+fyd8kXwtUm*y&@~yEr}7sZ;7om+-~++jn~Q'
        'F)TYT2l<%lwDpPGcQdiGZhCN~!A_1Se;dY5ISz2xmO2mFxt;Yekjz$Xap4=&5=jel_O!n+jtg+bj|~e0IhSMX?gvAB>(oupTBzYv'
        'VYxnuq0h-Vd(l6c>!jpP7r%jI9=DXdM6>qMwNw?9hMo1=;e78c!ip#rI#QG~ZWuNZuzx~Nv&{_H@hSveOkc(>_E8sxZn|Laj*UNt'
        '{x^%*ct16cZn|U3<2!Hp%1pXt^gA6}-XZdO7cXg3(#7nV6S~QD19l}H+TH20Hz3>9mS(2rW~99jPC239nn6o*Qysh6p~-t@F3(Br'
        'Uz$l4A$hab;HDqL9$?tftFUXK^Ax{Bu(4}AwFn4gE(cdXMe6b=D1L_Grzrjl#ebma+6Cgj@u?r5`cNE2aR|i=D4s<zgkliI1r%pd'
        'Tte|Wig^@QQQSbWjKV;nq3}?wqNt*XQT#TFyC}Yk;&)N}A&Ngh@h2$0kKzLq@1yt;ioZhfw<tbB@y{s!0mV;He1hU<D1HheZc?>t'
        '{~M|n@<!xVX@s^)BeYc-X>FBqqq(t7MC}bL)77OI2*VOC>{{Uo8<vbaUAuLM6Q`8RE|lcXIJqt@H-pKpN8X{ry<dPgP($Qy=<ZW`'
        'gQWJ&$<<-p^VmUh)w(2-NvfC>4|`26_qwU;Sfy%<)(NX2-rK_3p^Sy(zE!VO0v|R@7#6gOMzHx3@cr4VTZjrDZ+(HXiMy4bK7<NV'
        'x9~M(5s;S2MQGWA;oybi2&^9&mb@B<Hgmv!P!#QwwP8nz*oF?|juD*o4oGp9CdHYh!~aJo#do!l;+Zy5oDnI`h!kgSq&RCkNMuBc'
        'Ga|(qk>ZR<aYm##BT}3ZDb9!#XKkc7BT}3ZDbCss5*d-=j7V`tq&Oo|oDnI`h!kf;iZdd`8Ij_QNO4A_I3rS=5h>1y6lX+=Ga|(q'
        'k>ZR<aYm##BT}3ZDb9!#XGDrKBE=bz;*3af)^?D{h!kf;iZdd`8Ij_QNO4A_I3rS=5h>1y6lX+=Ga|(qk>ZR<aYm##BT}3ZDb9!#'
        'XGDrKBE^{^#hD_-nIgrRBE^{^#hD_-nIgrRBE^{^#hD_-nIgrRBE^{^#hD_-nIgrRBE^{^#aW9K&qgWc=XA|qPQf|N#ccH;j#w9g'
        'zS81z6QVIdWE++bczy&A(ohSQb;>$wePj);ehs<kAFrOq#pxnm1o}Qc4WjsC6n})`K8hcp_%jrLisH{vypQ59P<(*mLll3B;$sv)'
        'M)8j*{tm^B9uWW9E!T{DU+9|A`f<_LHRBiXkqLLL?A~OaxhujDuVeA6(#7KsIh?Beg@~tq9HYmP@1jD@>P;)-lH=;KwC))~xp-O>'
        'sO_X(6I?#TP31@gk3^>P!KF(}tz+c*sq1sLx7PYW4g@f9vkT}^@}ZI?3?Y&Ug61(mN)a7aKVjo4*!oQid|>GKckn2~OKu^D{t#ag'
        '9!x#QsSYJ)1~@dKTsF#*`SXlwmN<K45Mi=f_KKDKEXm`exp6-G)=*P<n4Erqzt3sW{G`Uh;_}sn;?x|fu{5{vCVa<~<D^dpQ0L~t'
        'OTXj^m7(xwQIaV(lV3I6u|x6s%U1e^%v008hrd7ZI{v}}Z`t4vECS)-kI)|8+G@FnV#ZY)o}QF{QvTPWd^$+Wr-QWSZ7=IV5nfyq'
        'A-=s0Z*RBWs={rrKS>JTg|~ON7T)}N^>4ucCgmSM#)GZpH@{x}YPTx?DP(-QwfyGSt@86-8B0geUSmr}st(62-l0x=MygI8v+^D4'
        'v}dI1+{Uci9qP1a$oqInox7NIcT=5A+%Y3P$_HSSllpZmR_{=MOGbMrpVWUBi@n>S{+5i+_20u{?{%oZB_mzGuUY?xSnP)#>Tk(N'
        '*UvQT-^XJ2JJ`HEWA#6GDVu+QSs!$$)1HyUcUHeOU>!(~@s3)95Ln5WYOone{h%2?z2A(QWWe;-&45Y9O8?YNvC^+oxVHLDcqOB#'
        ')!&4tTAwC1BD`h+0dMW7X43D)13acRAxUn(pV)L|?8StI>9i<!aA8|6TBTR(W7qH$_hFY>cWZ0O4;3$V*q=)0(FLRUnH)v6#|-6g'
        'CLV`F?(y!exmY>(Kc31*b51`100'
    )
    assert isinstance(_MODEL_, _pydsdl_.DelimitedType)
