# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/silver/zubax/sapog/firmware/tools/testing_uavcan/public_regulated_data_types/uavcan/primitive/array/Real16.1.0.uavcan
#
# Generated at:  2021-09-29 15:16:17.704296 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     uavcan.primitive.array.Real16
# Version:       1.0
#
# pylint: skip-file

from __future__ import annotations
import numpy as _np_
import typing as _ty_
import pydsdl as _pydsdl_
import pyuavcan.dsdl as _dsdl_


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Real16_1_0(_dsdl_.CompositeObject):
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 value: _ty_.Optional[_ty_.Union[_np_.ndarray, _ty_.List[float]]] = None) -> None:
        """
        uavcan.primitive.array.Real16.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param value: saturated float16[<=128] value
        """
        self._value: _np_.ndarray

        if value is None:
            self.value = _np_.array([], _np_.float16)
        else:
            if isinstance(value, _np_.ndarray) and value.dtype == _np_.float16 and value.ndim == 1 and value.size <= 128:
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._value = value
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                value = _np_.array(value, _np_.float16).flatten()
                if not value.size <= 128:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'value: invalid array length: not {value.size} <= 128')
                self._value = value
            assert isinstance(self._value, _np_.ndarray)
            assert self._value.dtype == _np_.float16
            assert self._value.ndim == 1
            assert len(self._value) <= 128

    @property
    def value(self) -> _np_.ndarray:
        """
        saturated float16[<=128] value
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._value

    @value.setter
    def value(self, x: _ty_.Union[_np_.ndarray, _ty_.List[float]]) -> None:
        if isinstance(x, _np_.ndarray) and x.dtype == _np_.float16 and x.ndim == 1 and x.size <= 128:
            # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
            self._value = x
        else:
            # Last resort, slow construction of a new array. New memory may be allocated.
            x = _np_.array(x, _np_.float16).flatten()
            if not x.size <= 128:  # Length cannot be checked before casting and flattening
                raise ValueError(f'value: invalid array length: not {x.size} <= 128')
            self._value = x
        assert isinstance(self._value, _np_.ndarray)
        assert self._value.dtype == _np_.float16
        assert self._value.ndim == 1
        assert len(self._value) <= 128

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: Real16_1_0._SerializerTypeVar_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        # Variable-length array: length field byte-aligned: True; all elements byte-aligned: True.
        assert len(self.value) <= 128, 'self.value: saturated float16[<=128]'
        _ser_.add_aligned_u8(len(self.value))
        _ser_.add_aligned_array_of_standard_bit_length_primitives(self.value)
        _ser_.pad_to_alignment(8)
        assert 8 <= (_ser_.current_bit_length - _base_offset_) <= 2056, \
            'Bad serialization of uavcan.primitive.array.Real16.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: Real16_1_0._DeserializerTypeVar_) -> Real16_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "value"
        # Length field byte-aligned: True; all elements byte-aligned: True.
        _len0_ = _des_.fetch_aligned_u8()
        assert _len0_ >= 0
        if _len0_ > 128:
            raise _des_.FormatError(f'Variable array length prefix {_len0_} > 128')
        _f0_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.float16, _len0_)
        assert len(_f0_) <= 128, 'saturated float16[<=128]'
        self = Real16_1_0(
            value=_f0_)
        _des_.pad_to_alignment(8)
        assert 8 <= (_des_.consumed_bit_length - _base_offset_) <= 2056, \
            'Bad deserialization of uavcan.primitive.array.Real16.1.0'
        assert isinstance(self, Real16_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'value=%s' % _np_.array2string(self.value, separator=',', edgeitems=10, threshold=1024, max_line_width=10240000),
        ])
        return f'uavcan.primitive.array.Real16.1.0({_o_0_})'

    _EXTENT_BYTES_ = 257

    _MODEL_: _pydsdl_.StructureType = _dsdl_.CompositeObject._restore_constant_(
        'ABzY8L4#Cb0{`t<O>7fq8ut7f!jB>Rq)^I~0yPC}LxH+LX}Z;-RBs;|(cLP$t7<Z~hs<dGGnyG^ovtdShh3%8NIO!eQVu=jw8}BZ'
        '9COSu#~ib_9COUE@7N9@4FLiqXm=A?@qFL=_k7Ry`E#DU<MPk{)>G}D@T@yl@hjDw;ai?#R-Nz6Qq{^C<wnhI_)cKO;lZy1uUQV7'
        'p7n<@*NT6NFZ~dIA7?|wsGBvmpJ|$-WwV}hJ*Vab&Zw0$J<lA=J+#c~wOetRHbyPacN+EBPKDYx-RGZT5-9c0_=h;`G0Y(FoKiEe'
        '{P^2=D@c!>;!wHoSk=lpl>J7<3``?P@P((h2v0!8;mL1Ip5>V@t@=n{f0oQ{T-QOvs#-Ox9(40<0q5~@<8a^oYQqdRX6Z3XPGD5q'
        'MPkY@#IorJMy*k?V*6BhVsI@y3Cn%XHY6sdCH0T^VH_Sa{J^YNOt11}q6yAZGe_!9(5xhdA9-duU^;!K`F{7AbA-yRn>PzL;v`eE'
        '6z=2Nu32`1v6#lgqupf2qlCoHA{kNdAM3s|QnxB!)B|h8@-{5TK1*p^x6hG~q_i(ga8}tURk`lPHG0-zGE>2C$8mVzcTUhD{c9d}'
        'Gl!DVaN|(lDv3W<D>bT4ISzYa)f!BGvc#`k%QJ(9w@$Zelx>HPgnc(W{&}NbHUq2vRM&)z#M86teAcq;fA~SOS~b0~O`fVTYF3+8'
        '{I57m>BukH_qt?!#!)99n)MOuq2*eEvlXPj@?N!=at`>SJ!yZL<jQcaHh(pz&fA?lup3h8P)p87vuY;sBqYA6h{W!@)PCnrjTn*K'
        'ol_pqkwkJtYG*7a&)NnXDWpb}?#AugWFw8&Nc$hh^9+xBp6W;YXn#ZpI<|CD>)@7t)I$d%I<z4#&+^>iXU5P$Iuuc+i}%QLed#ds'
        'N=G-<VGGaqzEC_Jp`#HU>-frSKaj*8f8ki_rDGADcq#_AvhC!ya?x=*5m8?!CX?*PTicGOlhhZ{sVy<F2is4-R9<?EPDS+g2EN$J'
        '`Ods_J~~ZrNA%7!@v;~DoPDJlbcWuENbhnR(Yvpljn0xD(Ya0@{aM(P%J03Fdh{-xi|G7X%_sICVd%nZt3mJ4`G_t)cUL$<XK(g>'
        '|Fzbp3v@A}?Akih9LcBb(rd3l?^8CS4_<hk9KrsVcLWDrq7Ndvvc9+HIcN6C{k^(lb?Gu)i72-%9yp3)@;i!&u2L?d!rG0<pSNo}'
        'UXSuri0JyZx!_2S`*2tA(KWgr(T&Y#<qGF6teuyeyM~26q#F_4dMVC0nqxoORjhQAZbejFzhAO#-uRCBc-L{zM^udH_Dgfe894sV'
        '8^KK<)9r}vZha1KaE)Se7C(7o_~;JZjp*Jh@yl5_$ER;}4fF}!i>UwcUC6ghljWh+a?N^MVz(_wiAc#vsjM$3gN%rbjEqV;bP>7?'
        'U8MpFA__7JD)pmZM8AxFl?E{=Vo=7QO2ZfyF)U+PB^Ry;SB9(7IL1Yc%NSQFLL?%R5veqVDG^gLrc|22jEET-Gb+ttPQ;vyIh7W$'
        'AYwtrf=WwR60sy>Nu?F6h**)a!Z-z_B%~CiG-L#1BxDq1H0T0!3AzGZLqR}6LP0@6L%)E23H=KCH4F+ElrX4ZP{Xi*VF|+uhBdeX'
        'TnVlMSHrk~aS7uJ#x+C&A_<X#NW+wXDG5^wrZmh5n2|7}U`E57fH?_s3g$E{2w0G?pkP76l7J-%OA3}WtO!_<u%ci^i<%{iwc-#9'
        '=072ww*UNJqvg`cU-3Jv<<fgvuFZ31Ps{CymP;pyU#phWpZ6`X16oesxCj5UT262O|LFfq%Oz_*-`?FlEw`rS_*0v3zo+GXqvbZ9'
        'l|3!DT`kwSU$Sh=>}k1I&~lycqdhIR8(OY?7xJz*?O)nMq(!7vRuV|dSXIy`qEDqh^zlfeEV3f9GO{WaQIt^>QB-LF10n`w45&1O'
        'ArV6|hE%d)i?C(bDq8#!sfCtI6POS&A!9<NNlc2ElrgE&G^RyN%a~Sa7PBH|Wz4EHk9iUEGUioU#G;5r8H*|{V_C$qjAa$83`(U{'
        'tTJW+X$ffsX$^e>`Xux*cnw*83CK#wDkuslN+|M!h5-Qs5(X3uXc!VOBw<LwkOo_TEx}e`YiJ2*NoXl(X_yc&Az?zngoa50lM*Hs'
        'Olp`GFfCzP!L){10kaZj70haw7cehjUctPEMFEQv78NXNSe39WV3~g_SmvR?0xs##*-EH%`hTHpR2t<tOvTNT8TLNWtu{(yohJDA'
        'vAtv;@xvaYV!57`v>z++kKrNXk<+p&hTHH0!>Pm%!Xt*?XnJLf4OPo<&A^Vszvt~n&C2^ub=30m-*J&v-Z$OGNdA%I)&6FBRz7Gn'
        's(zj;22Op%=rr8(ZnIQ%%7$l+G^<I$^(MHVUvpXOGUwav?|i2xpSzYT<T@TPug5lhM&czMZ{PApow61GX#Xe7{k~<EgX);>B}?+z'
        'oHV|5r_&zxZ|i@#dcAO?ctyXQynP$nH|=7l%Xw!*r}XfkS*bAWO&wCUej28^blV(Ly17v{+rK>MY(?%@DMhXau^<2d'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
