# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/silver/zubax/sapog/firmware/tools/testing_uavcan/public_regulated_data_types/uavcan/pnp/cluster/390.AppendEntries.1.0.uavcan
#
# Generated at:  2021-09-29 15:16:17.865418 UTC
# Is deprecated: no
# Fixed port ID: 390
# Full name:     uavcan.pnp.cluster.AppendEntries
# Version:       1.0
#
# pylint: skip-file

from __future__ import annotations
import numpy as _np_
import typing as _ty_
import pydsdl as _pydsdl_
import pyuavcan.dsdl as _dsdl_
import uavcan.pnp.cluster


# noinspection PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class AppendEntries_1_0(_dsdl_.FixedPortServiceObject):
    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Request(_dsdl_.CompositeObject):
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        DEFAULT_MIN_ELECTION_TIMEOUT: int = 2
        DEFAULT_MAX_ELECTION_TIMEOUT: int = 4

        def __init__(self,
                     term:           _ty_.Optional[_ty_.Union[int, _np_.uint32]] = None,
                     prev_log_term:  _ty_.Optional[_ty_.Union[int, _np_.uint32]] = None,
                     prev_log_index: _ty_.Optional[_ty_.Union[int, _np_.uint16]] = None,
                     leader_commit:  _ty_.Optional[_ty_.Union[int, _np_.uint16]] = None,
                     entries:        _ty_.Optional[_ty_.Union[_np_.ndarray, _ty_.List[uavcan.pnp.cluster.Entry_1_0]]] = None) -> None:
            """
            uavcan.pnp.cluster.AppendEntries.Request.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param term:           saturated uint32 term
            :param prev_log_term:  saturated uint32 prev_log_term
            :param prev_log_index: saturated uint16 prev_log_index
            :param leader_commit:  saturated uint16 leader_commit
            :param entries:        uavcan.pnp.cluster.Entry.1.0[<=1] entries
            """
            self._term:           int
            self._prev_log_term:  int
            self._prev_log_index: int
            self._leader_commit:  int
            self._entries:        _np_.ndarray

            self.term = term if term is not None else 0

            self.prev_log_term = prev_log_term if prev_log_term is not None else 0

            self.prev_log_index = prev_log_index if prev_log_index is not None else 0

            self.leader_commit = leader_commit if leader_commit is not None else 0

            if entries is None:
                self.entries = _np_.array([], object)
            else:
                if isinstance(entries, _np_.ndarray) and entries.dtype == object and entries.ndim == 1 and entries.size <= 1:
                    # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                    self._entries = entries
                else:
                    # Last resort, slow construction of a new array. New memory may be allocated.
                    entries = _np_.array(entries, object).flatten()
                    if not entries.size <= 1:  # Length cannot be checked before casting and flattening
                        raise ValueError(f'entries: invalid array length: not {entries.size} <= 1')
                    self._entries = entries
                assert isinstance(self._entries, _np_.ndarray)
                assert self._entries.dtype == object
                assert self._entries.ndim == 1
                assert len(self._entries) <= 1

        @property
        def term(self) -> int:
            """
            saturated uint32 term
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._term

        @term.setter
        def term(self, x: _ty_.Union[int, _np_.uint32]) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 4294967295:
                self._term = x
            else:
                raise ValueError(f'term: value {x} is not in [0, 4294967295]')

        @property
        def prev_log_term(self) -> int:
            """
            saturated uint32 prev_log_term
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._prev_log_term

        @prev_log_term.setter
        def prev_log_term(self, x: _ty_.Union[int, _np_.uint32]) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 4294967295:
                self._prev_log_term = x
            else:
                raise ValueError(f'prev_log_term: value {x} is not in [0, 4294967295]')

        @property
        def prev_log_index(self) -> int:
            """
            saturated uint16 prev_log_index
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._prev_log_index

        @prev_log_index.setter
        def prev_log_index(self, x: _ty_.Union[int, _np_.uint16]) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 65535:
                self._prev_log_index = x
            else:
                raise ValueError(f'prev_log_index: value {x} is not in [0, 65535]')

        @property
        def leader_commit(self) -> int:
            """
            saturated uint16 leader_commit
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._leader_commit

        @leader_commit.setter
        def leader_commit(self, x: _ty_.Union[int, _np_.uint16]) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 65535:
                self._leader_commit = x
            else:
                raise ValueError(f'leader_commit: value {x} is not in [0, 65535]')

        @property
        def entries(self) -> _np_.ndarray:
            """
            uavcan.pnp.cluster.Entry.1.0[<=1] entries
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._entries

        @entries.setter
        def entries(self, x: _ty_.Union[_np_.ndarray, _ty_.List[uavcan.pnp.cluster.Entry_1_0]]) -> None:
            if isinstance(x, _np_.ndarray) and x.dtype == object and x.ndim == 1 and x.size <= 1:
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._entries = x
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                x = _np_.array(x, object).flatten()
                if not x.size <= 1:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'entries: invalid array length: not {x.size} <= 1')
                self._entries = x
            assert isinstance(self._entries, _np_.ndarray)
            assert self._entries.dtype == object
            assert self._entries.ndim == 1
            assert len(self._entries) <= 1

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: AppendEntries_1_0.Request._SerializerTypeVar_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_aligned_u32(max(min(self.term, 4294967295), 0))
            _ser_.add_aligned_u32(max(min(self.prev_log_term, 4294967295), 0))
            _ser_.add_aligned_u16(max(min(self.prev_log_index, 65535), 0))
            _ser_.add_aligned_u16(max(min(self.leader_commit, 65535), 0))
            _ser_.pad_to_alignment(8)
            # Variable-length array: length field byte-aligned: True; all elements byte-aligned: True.
            assert len(self.entries) <= 1, 'self.entries: uavcan.pnp.cluster.Entry.1.0[<=1]'
            _ser_.add_aligned_u8(len(self.entries))
            for _elem0_ in self.entries:
                _ser_.pad_to_alignment(8)
                _elem0_._serialize_(_ser_)
                assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            _ser_.pad_to_alignment(8)
            assert 104 <= (_ser_.current_bit_length - _base_offset_) <= 280, \
                'Bad serialization of uavcan.pnp.cluster.AppendEntries.Request.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: AppendEntries_1_0.Request._DeserializerTypeVar_) -> AppendEntries_1_0.Request:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f0_ holds the value of "term"
            _f0_ = _des_.fetch_aligned_u32()
            # Temporary _f1_ holds the value of "prev_log_term"
            _f1_ = _des_.fetch_aligned_u32()
            # Temporary _f2_ holds the value of "prev_log_index"
            _f2_ = _des_.fetch_aligned_u16()
            # Temporary _f3_ holds the value of "leader_commit"
            _f3_ = _des_.fetch_aligned_u16()
            # Temporary _f4_ holds the value of "entries"
            _des_.pad_to_alignment(8)
            # Length field byte-aligned: True; all elements byte-aligned: True.
            _len0_ = _des_.fetch_aligned_u8()
            assert _len0_ >= 0
            if _len0_ > 1:
                raise _des_.FormatError(f'Variable array length prefix {_len0_} > 1')
            _f4_ = _np_.empty(_len0_, object)
            for _i0_ in range(_len0_):
                _des_.pad_to_alignment(8)
                _e0_ = uavcan.pnp.cluster.Entry_1_0._deserialize_(_des_)
                assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
                _f4_[_i0_] = _e0_
            assert len(_f4_) <= 1, 'uavcan.pnp.cluster.Entry.1.0[<=1]'
            _des_.pad_to_alignment(8)
            self = AppendEntries_1_0.Request(
                term=_f0_,
                prev_log_term=_f1_,
                prev_log_index=_f2_,
                leader_commit=_f3_,
                entries=_f4_)
            _des_.pad_to_alignment(8)
            assert 104 <= (_des_.consumed_bit_length - _base_offset_) <= 280, \
                'Bad deserialization of uavcan.pnp.cluster.AppendEntries.Request.1.0'
            assert isinstance(self, AppendEntries_1_0.Request)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'term=%s' % self.term,
                'prev_log_term=%s' % self.prev_log_term,
                'prev_log_index=%s' % self.prev_log_index,
                'leader_commit=%s' % self.leader_commit,
                'entries=%s' % _np_.array2string(self.entries, separator=',', edgeitems=10, threshold=1024, max_line_width=10240000),
            ])
            return f'uavcan.pnp.cluster.AppendEntries.Request.1.0({_o_0_})'

        _FIXED_PORT_ID_ = 390
        _EXTENT_BYTES_ = 96

        _MODEL_: _pydsdl_.DelimitedType = _dsdl_.CompositeObject._restore_constant_(
            'ABzY8L4#Cb0{`t>ON<=HdG00mF>G?Frbtmsi4sc`Mb65zvn2KKin1cnd{}hz1wJGKjy$fJuAS~>PxrVV`w(D24v;_!2FL)O06xyq'
            'x6Dzu9Ah{zj35^UNCGFwK|xNw`I!H&`m3g=XIEkbB*;Mm#H#78=U?CV{eN}Uelq*lC*QT?f4x)P9WV95dLtD{z{B8U-V8;((TY3W'
            'I1Mr}=q+9qVbFoB_h6?h2EQ0A|9tSXLA5vE2%<<N1K;W`-p`V}mF0<;EHc-Kcn6xO=6tioqk1>$)>~noW+JIy?si4wU5m0L5NZ9M'
            '_-QWEY|yJTHbs&KafIzId_ehM4BQ#l`isHO2fc$0o<W^vo{4nu5p=T03{0s(Z|-^^LT@}QyW#PSH!>XSUe&t^&N<kG5=S3KY0!>@'
            'cO%L~TO^ZnJlJRkStArtJM#xFgT`At%^IE969fN5@AzHa5LT;Sfp@p?70k%`^TEAA?^q+vc;xZKD>n3L-t_I>EEuXY=*>2~xHafm'
            '19<q1>egTKpQqf5F7r?MFZ*XyoyBe<HXC8wZph01S^wM~)tq9r!=_pgd1CvC>n(<Ydm=%=z%-#+uX<0ci-ct{%Y4D^@%4;#c^96n'
            '#|abL-H=B-gGH@ROsDt!9?O^{d}q*m_5%)2;mJ*DpUe1kavc^MA`~4FWoljh1!~#uE$xCn#NE!oKja_Q!19j(n7-b;vt-q8I8Faj'
            '@7VQVTX=iT!+*EXbH()BI{>ii@>Y=T3|t2g(G1f;@2s}j7&&0Rto(b>JM{e^Q$5~?pVU`xe<SV=dTg&o(w$B-4g)~m(OaSu!;0X1'
            '?!X**7AHj^X!!x~%m35f)AvMIWWny`_B9^E*nJM=p1PffAy0P7g`llX9_C{3SA(is>8DMY`D~*TL<9E|%<yf@EFin`kYlUv3>LNe'
            '?mkNQW4f>J&eHEWO!xQQd3wG;X@%Y&px?IY(mjajLf<_^zZWq**mn<8xu@v4L-mhfdZ6z<P4ACldbsZ%qjJyC^W&I4-FKhGbg}O)'
            '(fboLzUMGq>buWldaUoB#MJ4#FJOA8@4iUoPhmRScNz8n5~eTo-P4#p*LPpW^x3|9hT3@r(<6QNERE|N&8JH3En_;@cVDG(eh1T6'
            '`)&=>YTsSK^laa)V|u3Vu3~z+@1Dn$_1z1YzSws!VtTUgzDDDCo#yifrpNp4n>3#9k{#A)es9sZF3~*S#?<b+-=p!pgXw(V{S%t^'
            'yEM-CX#VeGy4H6e(Rh98cbn>eis>hP_m`CZiqg+1{WYauQ2HgMe^lwM$_!<ebf&5^YdZ73&OFi?UuU*;=2M;drOy0HXFk`NU+c^l'
            'I`gH@{E;#_I2ceD9!bAQ&zeXS5T^rq6o4OX1Rg3>{h|D|a^otC*FmL%l<_c(Taw0avyVj*vtXU&(c>uID(lo(J`a<8M&P#UH?B^J'
            '=GXg(ImKz^Qh4uZ!GkxNJ1R!_*}(r7|DRHDr=9>;1cMab;IrQ0#yYBHqZ=m~PV08>NF$B&q$S`*C>mW3&axM-`f*3Bra=h7!|KP-'
            '$@Xf>yK#GUJxDrRJQ1r|9Ea&D^q2)vyP>AE+RdAwZ;eE>K~12;aa@qDQW2c>>W!=Q3-$AL^$6s!;qw%_PSD$cyV?v|V(=MQ{BN&{'
            '^&k>pXNL8_@^$+Gcn8p}pp$nP*dg$kv<8FKfSE!F1dXsbl3pZ-UrD$FBV<_uON_H-A>RRqWq*LRQWnNr=yiM^u?rX17>ofHb&Kz$'
            ')Hr${Smkm3v~Ev$s<bOw!Fr%jAd7cmXe5Z%<NCmV=s%Kc=>N$7F)gOl>$}|ZU|3V44sU%`;j!X#+Jq3Ut4a^t3aozzz!1Uz@t$fu'
            'Q&Q_0QtR10)Ovx`dY;sJj?{XV)OvqOt!GMV?T}hKq}C3pwL@y{kXk#W)()w)Lu&1iT05lHPD!mDQfr6Q+99=eNUa@GYlqa@A+>f$'
            'tsPQpht%33wRT9Y9a3wD)Y>7nc1W!qQfr6Q+99=eNUa@GYlqa@A+>f$tsPQpht%3BskK9D?T}hKq}C3pwL@y{kXk#W)()w)Lu&1i'
            'T05lH4ym<6YVD9(JEYbQskK9D?T}hKq}GmBYe%cKqt)8cYVByXcC=bMTCE+e){a(dN2|4?)!NZ&?P#@jv|2k_tsSk_PCxg5OBpTE'
            '3n&aE(9hpiBC(4+qZ$kUUy)%y^soEB^KWk4ov|$cA9DZqpZWiG+yD38=Kr4PL8QD&k@BjHl#BA`{|8FlU*3rXyBporLRT0&6S4{@'
            'A500`MXloy9fO$3nNqmiilbCSX^!)5$4QX+ojSV<`-xPrq$pXkjfwrD)GbeBJP6ahRO`P?uBc?sT!|xeF43;REQZ+_%Yw4w-twzk'
            '+xRi8i2Sj^A-7lgqCPUvNB<A*jFd$NvdEMyYI%F2V0K?An4KkAoFiG>N3v*_g4lVI#aWWYeI;3Zie&LH$>Ji(;vtg7gCvVK$>M=h'
            '5W7IKI8U-TN3u9evbdjQaUaRzOeu(EB#Vq>k&!Gil0`<c$Ve6$$s!|JWF(7>WRa09GLl6`vdBmlSt*ERB#Vq>k&!Gil0`<c$Ve6$'
            '$s!|JWF(7>WRa09GLl6`vdBml8Ob6eS!5)OjAW6KEHaWsMzY9A78%JRBUxl5i;QHEkt{MTi%iQR)3V64EHW*NOv@tEvdFY7GA)Zt'
            '%OcaV$h0gnEsIRcBGa<Sv@9|$i;!vh4Ur-lhCqhl6Of@CD_EsiVZIb2SVV^TQj9Q5WSA#1*d;P7lwyPmk-;J|ED{;!i44a}F@jBG'
            'm?bitATk^yGCW0Ou!#(FB{G~OGAt1pj+J7BLqvuOkztm|U=bN!Au^mMGMpkZoFp=wATk^$G8`?%2#Z7po5-+0WSAu~%n%t~Co)_l'
            'GMpze)QJo=BEzdhhANTaERo?1k>PZS3_3=5pUALAWT+AumWT`$BEyi#FeEYzi3~#`!;r`@)MOZHG7L2thMEjRO@^T+!%&l9sL3$Y'
            'WEg5P3^f^snhZlthM^|IP?KS($uQJp7$O<|KoRq|Z1|Q9-?HIL<r+pnhS4{OlV(bB(o88%(%VO?6eleZ87f4EgC#P|m*S+k()O`J'
            'WUz<~PnF`N86v|mBEw-KLxsq&kI3*Gk>Q!r_VFN*VV=k^Q;L&L5*e0=497~_$3sMh3Xx%!$Y2o}mWd2!i3~57;-nXd49^i6o+UCI'
            'BQhKzG8`r{93(PShzxT?hJ8eaOGJh>BEy?RhS!M<7l{n#OL3A#WO$#*utsF45*e0=3>6~7h{!M^GK`1}BO=2{lVPOEFw$fgX)=s7'
            '8Ah56BTa^pCc{XRVWi10(qtHEGK@4CMw$#GO@@&s!$^~1RCEpBvf*1cC^i((AwMoWaA$f?>l2)HJo2QYu*n0Zm)sdVcvK%}ciTDd'
            'vac=fVewdIVoUw(Js!2iSDpOKHy*3An;B^RLugYX*?K}GTT@uJ44N&2XUibkGMKieP;D7pTL#&d!L~JpZp+}?G6=T}#w~+#YYOL<'
            'LAqtIZW**&2Je<Zyk#(N8Pr<__m)AvWw37<^jil1mSKQpIA9qTScV6dVS;72U>P=8h7Z;hBP_!S%do;Sys!*2EW-`Uu){L^una>i'
            '!x77{#4<dw3{xz_70a;2GJLTNV=TiN%do~Wys^g2u_Sj?kWm3Je*Pp8_w?B!8c0d2iMwSf3C0ROvrX<GQU8#6vZ!+Vw9Jmr81bz`'
            '<&UT*hY5`Gor=WGXBzoTNv`>VT_G@5aI{P2-3gUDKwy-8KCg1ewfvf|*%gd>Uo<_OQn?ohj1>gbODcDiz$nN0vgzZDsr!n`ozc;{'
            '`IJ*ZfL2X=%PMzFOSAdXT|t1>Xl5&>-MX3Ms>*$bz*xax;DXA%LSU?5bp4vjogy&G{@+l!69h(Si|?A5t(lR$W$b>**ynAPThQm0'
            'II4G4Zic{Ealc1ktRQILQ@J$_#)|uS;VZFF-#G{V*++i^dii0Tq#0|eFQeU1pWb9aM=-o|a6Jyy!BC4wtSJ~?-^nxKF`izsZN|1_'
            '{i&+&u&Vxit8W)9vsYR5B7@$$DSoYu#CE2xgvd9Ex~Ic}C=<yh4<~wGw(V>6cD=^h!KP3rT2tkr$@BF$SSng^<fS!PXzMFxhaY;c'
            'T)xekdCCGc89evGVW%)4J<?Z;t-`#p4E?Ix>Ps|!jE2s5C(a}FAsX8cGPV`qc^QAKI^!_qt+7F~7{-KOs^twQc)OlMX&R>fob3fE'
            '9cX$ijN9@k^=Pkh1*`EW8=saf?RvQb7X0MZYu7J7y!oJU>&ETIwVT(jJh*Y^cH_Z~Ti5P9e1K;Kl^?0;d<0&&_kzB%A-21TNbx9m'
            ';>J?tp0pqjb<a@ez<R=4_%wz0*C`M0dovdY7!M%wHh#08JpU67_41?LhWh9{G@?gq|G+?@6GZY5RD_~s);G?<rjaKL(1`;}gO5ec'
            '&I;$IxB{IHo|Ssjh$6^)B7v?D@vw}zcnU1g#8+1b4#3E!MzzdV0bEo%g&)=8@Yo8wux!h-T_~a8%F{IO2m~3=<a}<*n^EI7;z*2f'
            '#Su%`SB<5ysgsCvDZc8&X(r3#nFk&Rw|E%ZSSQ+nmw3&o&hF<eA7<|J%>Zx<@Q%CCAWR8N0I+T)f@kt9I*$TCc1Ln3jJa21Jk0z!'
            'Z~IsdsnO}GyHj!|EBc7IZr^D_+j$!9)OKex*}iZnEoTy-ZU``U4f@QOAGBd=>fAe(N7hlCO{@x++=Qv|9lOQzbZn>;83@S90+<W~'
            'w0Ah(Gc@Z3gO8MS02cw`9UM)XLO=3^DC9dz0EB^?Iet$7cyR|-)5A98{4kJZRp4Na0lGf|L$z9QB3EGQqF0?gP*r3j3IlEUnTI?9'
            'A+=MmaOk0Vz#@36rB<{9Y7;1S;1HE<>cG&Af7IlI{1=e#&Ae`yNoRqt_{aU4U-d8eEB>4Q#f`s%V*c93?;zRud;I73_|HGXKjU-4'
            'Kl{HqCw%R#^QAkT6K95>f-r<fEbAK`3O<;A3$+0z>b`@L3It`uqn4od?4l|cPA4<GMhMH2Z3$4OM0k1Rfk^8j;EPm;N=0z#!PT_D'
            '%gEXR%1cXjO_w&rcFRZHr1o^1yBv_p_HSg&ivgp^1K#b1I~raZ$q~?Sx1j-{gd~U^5Z7c4>DbCsgrTNTNBShxj~%15-6U>-+fW@%'
            '9pB;tftCiSBv1hz-i~UbZeP=rH3p=L0+}6og`rBKdtfURmNCa*x=9Sa3h4}TnesLr@OpT6Ms6U9um%9*l`e({gqo>o^Hu@^u<ODq'
            '%&qevff;!LC{SikYTwskv4&D5nUVVAIY~XRPv3~xeZdn@WoQMo@F8C3QMY?>U{_3Ym(9$o*S0eyfppb*`7~?pu&aS+$Lvnj=1DBg'
            '`oq|d*d56<kd;hbD;gs-gD7p<0VT=-A!IqoPQVk0buxcEWHPjzEW|B1;S6|`G73MXHE?a@B>+~X>87Z%cxx+#m{Ba(*cN&&CO}_y'
            ')ZzcQC1XsyH)}_Erzw&eU3Q||X|-_#5GN4MbYtc7G&Gf9S7G__%36xv1>KueS0qr=I3`3%5_e#YQ(VrLjZG{|Iwu0~BWmOE;CyvR'
            'IK`YS72!Hq=YD{CQVd1Z4A3yzMjF?<(2wrT<BE>mOM!ICBdS5ccx)YnW8G$qx52!r!KV@Lf@{gt4KKVUf!0&2*XgRT4mcZ;cN}}$'
            'pXLB~uV%||1AMK1BgrKvF%=0+uwksnw*8@x%#X&@LRpFx_yki|!Y8SuyhKf|oG)6B<uYcwf{)V;63O@g1E;OXCX*?wC<LH_M(46x'
            'u}|)Ksjf41B}I!Y_Ew#MpblhEUjWjc<cY1|Mq~nS0ufcwD#li@^TB1pMbpt(JLj-GQWXsy%}nXS-gv?kAJ`Zl$dT4mFt{#n=E)EZ'
            'S1J;y+FVT}&Aak?U?kccqkaWwU``7Wg(?Ly8>eIR6(W}+u!#p-u(V<&j>t=B<OUei#9NtPleY@T7FEcC#yUKb(Wsn1uop<t(ryHz'
            'C()H`0NBYMA71_dcXLvQH-#Ux&=u#YT2?T~deF`jgFPy7E|u7hv7=NQ1GYXO-!Me5h4M+jeUyPH3wI!L4ZVrcng#B}n`&MV*Qxy-'
            'R1=z#>Sht{0E?Buf-npS>riToD;Z0W*<%m$HmnQizbT#iXtt)b6vp7tbqYEXf>RJOum<f6LbVbRc+@y~EN_Mad}}O55NrkH--|r5'
            '<(`%2S=>RLQ_elhM5mjn9jkQww7w8{q8thxuoV2E5^j0NN@~^?;6{!eghxAJQy4>fY#k$73>&2ga`bjM&U2}ewF%?m#)Io|L*!F<'
            'haE)|P1w6BV_^u*1hy~u_cc0n7`v#ez|UBEpgr6aussXHiJfMU+A6y7s4_;1Du^leiua@Unk)fdpc_x6_{Y0QCb*BsN*rz7HxK0|'
            'Zvyix5{fIb0ZBy&k74|o+FWI0H0fF@3M~zn<Viz?oZQ%Psc$D_Bt4v}^xohD0JI_m$Vr6ZQUl0VJQxF#Z5dE;5AE0)*X#&vIQ4@r'
            ')3Kp;Eu>Mn4@|Y-j2(~KBGN~ff*3#_ms93*lv8js@^5K^XdG>|MI;gkPK#kV&3TUtiR(gc8f!%>DO+yw4AvBeVAC~tiX6yD5UdiB'
            'i90wv#BecI=X*u#HDXr!xDZnpOkq#O45U(d*W=kZZr`QHNvG<=PI*(uRa!<mF+|g`(kvW;oUlD1MdTT@zm9O9uSO?PUS47x9xj~v'
            'TQ75=+~>(|JFIF@7j^X=N9*M>e!l?US7-Nji_U4sEH_1CF^ik%C6y_Yyy&!P(Lt?|!UR!!Vgal8ErG(u2<F1QWwV9aGi)3C!b>_z'
            'ndp=kL1Lrj4f3l(egNe<lECl)E33~e_&G2Pkq*+ysCAn3dQeQY<$-2IIWGUQT37Yh*1Qbx4>Z#Nhb$F;9Y2Wd6^sI<?x3E?cJc)O'
            'aDf&@Ej{8+Zwd=_&8I6AMFG2!wveA&VEtiER7h?q#=F3}eYqGH(yit#<vL*h<4tye(Z2jzgTn)3HvxHQ5-%7>8K8jjTiyzr@JP~D'
            'YBFIV#8FeK%knp}wEV5s_-?ZSr#K9jNdX&~r-OS5Vnq`4I@7i>ItBeP8K#5+8-OqXtts6Ls^(=_HAAPuw+e{j*Vh3`2Kx|Dp+`b|'
            'ia@eZdGRgmj6QbYNBI?yWqN9M0<f({e*?R90A=_;xETF}SDF96mH+yy)&6g9!-H};b>#OR6nbx5NY^brF8_Ips(Tj--JPymdc1qx'
            'pFp9X6zi&s9g~kYUf*w7s=V(<x0Yt6E0mtAqa**If5>;#AG03!tNx0A(O*;F2Jy4tH~)^f@g<hQ?|2*ki618y8Zzd|2DhyJz2gm!'
            '{zyD&`05XW%U2JWe`@0bHt|jG9k7Xe2OIC2ql%61Ll#WOr>-fWnQnuXto>*ueXyHKb4lCcOSa2PtXltXGCD-KCqDoH'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Response(_dsdl_.CompositeObject):
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     term:    _ty_.Optional[_ty_.Union[int, _np_.uint32]] = None,
                     success: _ty_.Optional[bool] = None) -> None:
            """
            uavcan.pnp.cluster.AppendEntries.Response.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param term:    saturated uint32 term
            :param success: saturated bool success
            """
            self._term:    int
            self._success: bool

            self.term = term if term is not None else 0

            self.success = success if success is not None else False

        @property
        def term(self) -> int:
            """
            saturated uint32 term
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._term

        @term.setter
        def term(self, x: _ty_.Union[int, _np_.uint32]) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 4294967295:
                self._term = x
            else:
                raise ValueError(f'term: value {x} is not in [0, 4294967295]')

        @property
        def success(self) -> bool:
            """
            saturated bool success
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._success

        @success.setter
        def success(self, x: bool) -> None:
            self._success = bool(x)  # Cast to bool implements saturation

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: AppendEntries_1_0.Response._SerializerTypeVar_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_aligned_u32(max(min(self.term, 4294967295), 0))
            _ser_.add_unaligned_bit(self.success)
            _ser_.pad_to_alignment(8)
            assert 40 <= (_ser_.current_bit_length - _base_offset_) <= 40, \
                'Bad serialization of uavcan.pnp.cluster.AppendEntries.Response.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: AppendEntries_1_0.Response._DeserializerTypeVar_) -> AppendEntries_1_0.Response:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f5_ holds the value of "term"
            _f5_ = _des_.fetch_aligned_u32()
            # Temporary _f6_ holds the value of "success"
            _f6_ = _des_.fetch_unaligned_bit()
            self = AppendEntries_1_0.Response(
                term=_f5_,
                success=_f6_)
            _des_.pad_to_alignment(8)
            assert 40 <= (_des_.consumed_bit_length - _base_offset_) <= 40, \
                'Bad deserialization of uavcan.pnp.cluster.AppendEntries.Response.1.0'
            assert isinstance(self, AppendEntries_1_0.Response)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'term=%s' % self.term,
                'success=%s' % self.success,
            ])
            return f'uavcan.pnp.cluster.AppendEntries.Response.1.0({_o_0_})'

        _FIXED_PORT_ID_ = 390
        _EXTENT_BYTES_ = 48

        _MODEL_: _pydsdl_.DelimitedType = _dsdl_.CompositeObject._restore_constant_(
            'ABzY8L4#Cb0{?YXZHpX55Z=YR+<BK6Ly}Vw%m(AR`7(1FUr;b;&ImHz8a75GFEl+fwOfrd-A#ATdK(ZDLCHab2Wh|i1N{+J&)myi'
            'l3N(Ir@HE?s^_ViCrkhQx7=%g{)(QLwyY9n!3bW7$2_kfVTG!-vcf^|=e~tX)O0L=nrjHp!}X`(_b~Kln2-`oz@9&M*O{hpje(Oc'
            '%S`f`Ag(ujR&beUsgt5=tOJvLqczC#wsb~-O~zogl9qf|*$j*oN=D$7pAXK@L)OoFe}$*PuQTo_C~q9t@QAXU(!!Bf@XOx`sLJEI'
            ')>z3MXD$|dTDUf`X)z;@i}$1zQwinw(!mtW$tKrXE*z^sP9279K;Q+pj@7D!fbaN?JBL6qEZL^Jop?nZ_5KXw;4d-jxGcFT7lEEN'
            'Ij;F7VyX^)iIu7dz8A=Nxl4<06ZZNor7Ga^L_zpo*2gROK3>~vF;;9-6ku(@O+OsN1kAvxfkPOK`NR!0*JPO}Gk{%PamgL=olqw5'
            '7Z;dj`MeV|X7~U%Fu`F%y_cX36r83b?D;p?MC?Mzv@(u~GK~BMW>sSfpo<Ea=G2-0BSlq1YDGm#r;nSQ@1~Y(HBBeN)W2~9siVGZ'
            'N@<;tQ`SvSs++tL1v4;hs+jOtM4KMENSz)GSbF1&trv#uqhu@T97$7#+)_aXq>IYWL;>L$ZsLc;c3#=wHxK9HSQT<~FTMwV_Lguz'
            'wC{K6^*{#y8dEy>!D%3NUgwJ1p-Oh3Ry1{y_a8|M?vz>FvH}IoF5dL#@9?rDK3;OdZT$M^bkkqnRx&CgUkT}7?+~f+xIGJzw-+$Z'
            'kD99DX8uz288+ip1L5y5%m({5r+w93S+t=|PUO`>#x<Y=-;IZrxC*3Lj9z0jWL&l@J)-Hn*Mj0N5v@;XU~_zsUB!p=JfaI0o$hC='
            'O*9Y5JUlYnJWe;R<5_$YFT_qZa0s}yIG_0O9^M$?C-^CT)@i#!1rReX>^$lF4VvEW(`Fa~FX^xSB;dP8n>3(Jx|;RlqT;o<lb_?4'
            'UCm!DFqd_vQLJLIrAW{TY2F%hIfXH3aN;z*f9;6dqJTxL)%~{P2P1q)wMQDV)oAbS+m?@(x_J5TD=uSb@;_<}S~>Rx000'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    def __repr__(self) -> str:
        return 'uavcan.pnp.cluster.AppendEntries.1.0()'


    _FIXED_PORT_ID_ = 390
    _MODEL_: _pydsdl_.ServiceType = _dsdl_.CompositeObject._restore_constant_(
        'ABzY8L4#Cb0{`t>ON<*wdTvVdpjxk%CCjoU*=1RlIWmVM$uHSnXDv(eTHDqmdU%~|47$iJvU}9*=5{w{GzJ#%2FSt+2!w%|V2?cR'
        'Ej;>`>mC9mFcyI?36KPvYz`abwAf?*zv{1Iv&oTVAz9>L0h%gy*So&&`~Q0Mrwf1e<vW)A*MFwF<)vO&tEVCfco=-b8=<Jxn{lTb'
        'r$Hu${oS`jvJo`J?X9jDem-3J$?(U+N`G%X5kKmQG^=O$+_(CBFNrYdKo)O0<x)L}B9X`>x3Z+y%z8<ou*G`BJ5W`n$2Xchs&%7o'
        'tr_;xOeD1n-L8nd%TbmDBCXw2l@9ym`i4l-Adaxy<qs(S`Oq!7)=!5&fo9iv26-C2Or*n)pptERYEljRi|+;^^d`-+>mJXz>fm<S'
        'y9xF=*nkuV??h?Pj)Zq5%0ycv(|z1sZv<IA6j3|#hc1J{n;b^36MHavPxlYs&;?<(+C_MG6<<M*tUnvx9QF^@(~L(RPrQ6VpY<C4'
        '{{8|CRA<;<sC#j9*tdr8@F`WTf81vjd(LJ4Nx$N+s62bSiP)%zal0-v`!D*{ZL&G}Z2L^MAo9e$ht9V*6x<UD0t>nc+4_~6q9qcR'
        '#Vqp$yUAM_>+&u<X~hW>_qrjEcm|VNo9a&g=r+@sBz$Ywf8qlUPvOb?a(ph}(;{$1C^{n2z}-V7@9!U(gFeLF*3duTAJo9|4+EIK'
        'es~vXR3EXM{&)L_-VN>vZ@Yf@mvS|iP0jsX0IM!<2HDoobpR2KFdg<!=`oui2Zk>z{vP)Cyc1-q##``{>gw;T$K7F{ZC6OT)oH|G'
        '0LVLdRdiyQ5$w-(=p)bKBrgO_KLCFDy#Lru(G^)RKi!V{U1+=Cf^_?@^}>)RTg60B)&>uIV)z%sid!C}4e0qoy%R)3_fw4Udl*?p'
        'cJ)GzrMe|dY7N{S6z;@u$G}~n--{UT9JovLe3`;Bz28N@ZB?ba8^h&+yN7=7#c=n)-AC#6({qRNAHZ<ez<rF~AH;Cqz&%9i9;fGr'
        'F??*`K7rxhfqR7BKS}L-3d17<_b7&k2JSHooq>BC!#xA{X-fYLh6@9iQT@+iczocV!0@So`y7T(4BV4c&hr=^7`UgXT`y37DpcMI'
        'hKmFDG_~_Z3{MZ-Du$JTyNcndfm_4y<iK6S@WjA9gCQHZXEA(w;GV<q*uZ^>+VL{==M@YO58PL&J+IL?oTvW1PVIVw`uQe?_Q3rP'
        'weKwqmj>=1P`|%R?R=a1{~m_t2kwW|UZ3i{NBKX)@Y8|&GYWrB;TIJCg2JyT{56HYQ{mNei6TdIq@p9|b>uxA`A|oE9l56?pXtcY'
        'bmZqc@`aB4LPx&Rkzeb`?<mp(0|V;9BWV}uSp$gz;<T$51z<<(frkoJyCZ+CUb)2L7N}H^G9HF;Q_}cN_K8Sh7PMF|x*NrtMV*?+'
        '=RT6p2+UUP%B306{CXR)s5q@m3hy7xS@3#eOZf;t9{T_4|8olF)DvKeppn8G-tX_Lw@@wX-8jjxTi5yr>S^3dngU*gqTc0TEc@Y_'
        'A9uuB8ie3HtbGEN+*?a|H*T-Bf~2#_6S0=XahR?_jad-2>#9p@-ChIq4LqJUs0ma!@e9&5N`k#!yK<>^wsxkb9)TRzeV#(q30j*}'
        'c~QgrFyeoENwk7Uz&JC^2P0pzZ-aFJ-3mIr4uf$BJSInj!E8WJ!3BasSR6?!(t}?~xCJd_Sprjxy=Ecb0)u6LfVol@#+zt$d>*m0'
        '=gu=|15D~B-%6=)v_3G)ll*DTp0ZSFS2TlGpim%_cVZ|ch+1)N=>M_*k(@*SW4}q0DfRjW_dICUjHtugj>^zgd`=tS!gW>Zp<9Oe'
        'PXG)l{Li*k>rz3jOQhBd+o<(2sr3@6^&+YD0;%=Rf?AgfYVD9(JEYbQskK9D?T}hKq}C3pwL@y{kXk#W)=ojK9a3wD)Y>7nc1W!q'
        'Qfr6Q+99=eNUa@GYlqa@A+>f$tsPQpht%33wRT9Y9a3wD)Y>7nc1W!qQfr6Q+99=eNUa@GYlqa@DX6tWYVD9(JEYbQskK9D?T}hK'
        'q}C3pwL@y{kXk#W)()w)Lu&1iT05lH4ym<6YVD9(JEYc*R%=JAwWHPA(Q55zwRW^xJ6f$Bt=5iKYe%cKqt)8cYVByXcC=bMTCE+e'
        '*3O{ke@PK7(aR_dB+y5%DUp~X&#1=2|2JgVb>H=W>Hp#Soswnw|Jd_?b>IK@YyN-qH~#NL4?N{H@|4%4r<|8R|36Xc{``6**p29h'
        '7P?&9nUGmP`JhW!E@~YI?-;~P_LSV^W*ns=N_*JvcANy6->I=1u%1W-OY)K>%a~d(O5O5A#)B~3PPP8q#PUk^_{BIv;}XqvX3@<?'
        'Ulx=d*Om`1ZM_LIB7dy6Ahuolygo9}NB_5ONy;JvS!7BUwY)u)GrObU%r1~DE|M(nAX&5vPV5rN;sVLyj)E-iCt2J_vbdLIaSzGj'
        'ZjwctWN}x)iCrdHTq0RqBw1V_S=>poxPxS|RB&P$$s!|JWF(7>WRa09GLl6`vdBml8Ob6eS!5)OjAW6KEHaWsR&Zh&$s!|JWF(7>'
        'WRa09GLl6`vdBml8Ob6eS!5)OjAW6KEHaWsMzY9A78%JRBUxl5i;QHEkt{NjMMkp7NER8%A|qL3B#TVTBGa<Sv@9|$i%iQR)3V64'
        'EHW*NOv@tEvdFY7GA)Zt%OcaV$h0gnEsIRcB19U#CsHKC2*@yc2r?9X1*_mIEERkNi^#B4@DUb>3`;}?yFiBJf{#!pGFU{0y+np3'
        'BE#W=k6;rS7KjW_5*ZE=8TJzyY$C&Afegop3`d9zhYCKz9wI}T$gn_Uu!s!L6B$kr8J;0B93wJ3Nn|)oWH?yx5%v-pY$C%lkzs+z'
        'P$DwCOk_AmWH>`)s1X^eM26Euh6<746p`U1k>Nyv4BAI{kH~PI$WS3N93e84i3}qm!-&W*A~KAK3?m}LNRwft$uQDn7-=$$G#N&k'
        '3?og3ktV}PlVPOEFw$fgX)=s78Ah56BTa^pCc{XRVT5G(EqTn}vf*1ce9MO4DAO<oGK?R=PbwAsq*B38(#uDy;3q8;8OlV4-32l%'
        '75t>d!t$|9WUz<~`wM<jiO6t>$gq#dP$n|$ATm5fWO%%=eB4cBSRyi%3VzZtBEu0P!=b|RaSxH9Ok`LfGFU{06(YkaBExe9Kj}D;'
        ';VB}+6GVnXM1})IhJ8ea-9&~mkztX@u!G3(29e=Bk>OP$!^=d5b3}$S1wY9mGQ3A*I8S7#5E+gT8OlV4F_B?RWEc|}#zcm(Cc{{h'
        'VXVn8)?^rKGK@7D#+nRcO@^^1!&sAHtjRFeWEg8Qj5Qg?nhax2hOs8YIBy!hWy7~@P;AJdLvAkokz49NrcZEMc;rb(Vbcdnr`!@A'
        'JgUvvc`N5R>)QMp7LR47mefz&<WXBZ=;UXqepj8{l%VuKfifkMt%pRiHG^f#pxH8bwhW>zgK299)t14vWsq$dY+EzvwhX>4gK*1W'
        '+%hP)W^is9q+15-mO;B^@NOBzTL$x%LA_;gZyDrU2K$ylzh&@m83tH}1D0WdWq4p2CRm0GmSKZs_+ZU2!ZMt&3@a?d3(GLWGTg8X'
        'J1oNw%P_<;9I*^bEW;DaFvT)lu?$-*!xzgi#xk6-3~MaI8*9QGOL9j!8D#+D7Z2lc&z>#f04ZrTez!~|!C1y;wu$W~>hCd6_Nv$p'
        'Ewhs|Mtti~`UC38J_4hBr#x}9O(UNv$u&FJWddUvTYJR3ds4-A5g28iM^)^wmS3}*T}H3>X;Z^9Dt4T}SVllSt6~QUjIy22nL19I'
        'yw9uHN$stht(-Cfv|`FzQL#f>n$1pk839_Qo~@d4Yo?EDD)u6Qv5d~ZSrvPpz*t7_`Xv>6hQKK6e?`TfBrwXcc+K?eylKhnX58N}'
        '<MXD9E$eejY}H#TRw6K#-R}?>%Lv-HRqVV5W7+*8w@WP4KIhPX@x#9Xz5GF(q#0|fozZTnPj9lIBN*N}csCB!!BCS&tRWa)^XX;6'
        'V?2Gswi(-$`De1e#VUIHR^KjIVW(N;9D~}sDel%r;$Eh%gvd8^Ifw;OCXx*vPSw6*+m~zYT9vhf4WUl7X3|5EXKJsoR5atrORF-`'
        '<^y_%8@(4VTw{%1$^z9HJomz8r_dnX($o1;p<kGWe${NX6OEhEP#N#Uy-00DWBEbGHUm5_<9AhM9J;(Y8PF_-HsMaSyx|0ITRlik'
        '&D7i3UXap(rpLm#Ess)<^vf498;`QdY1#3)mpfp>k6pU_?u9$=->zT1a;<*({mU0`U%7s*e*4PR%h&JR#<PO*4^?+Q0xR4<uCHu}'
        'd)-8&coaN!W2t;ojvx<p&5&nTE8$Iin!@{cDGu-ZrE^2{2M~Gdf4`F~|3fwP!iV#k`r#QUM7P%do`FIqh~y!t2u0J(Z`^}1jXarv'
        'P8?Vod?KoLmOD4a8R&HItkj!D6hYn-2~>rMhiSygQ(%E29-JLG04<wo)e2h!a8c?MepK?!W2@}!iY?D}A%%h~Pt#sUAjo(o`}4lM'
        '88s;*j>H649I=FTRaqLFJc)QA#aEp;&18B!^T6ZaCJ#d!^F&+l60bSc*sWgEho1X<BLLh2yyGqu2wj3909ZE@!83Ul-HQT1c1Ln3'
        'jJa23Jk0#K*Y+_TQlryVcc)}eR`n5a&A#4%vU_Q`Rh`df8vER#wCqWMx*=e=t59dg{Gbh8Q|I2PJhG1BY-(1x<R)~DZ`n=WOD6-B'
        'A_D<ASpc13fc6f@dxmDdpz)EC4&Wj{yo0StQ>aIt5QTh834kzgGso`<059&qY<gIR>>oO^tO6XYGC=o7Fi_2AoX8oNx#(46w^bHd'
        'h{8Y{e)dA1fRNfLjBx1T@W6=Rsg|124ya9_*nv${V^af$u79P;2l0P`c)#?rVJ4jgp7xLWXZ=<GRsWp-rvKXd-$63}t@U3*u>KGD'
        '=U4dWU*ON=obXS7Kj(xmy?&-}r*rDe@G}sG@PK7K(xKq(*|(4zV506jD5*eDMm%Z?D$mZVa_)38!)t^vE!n03WlDtCi#!l%odj%='
        's!*v2PCb~KCRiDnJ3x79%BtzohPc=C5jUwlTjrbtQd$0$jCnC&6nVhA-Ed38OCvb~8qRAP5K2gb*a2}(=8%T1*hOe+3VEbWLjBk>'
        'O5081CYTLX(aiBJP7r8mfJy=x(BN&UB5L+!-B~k$lu;nFBQMufNpug!3Wa6DG3ag*gRMe3gIuP(O$WRl-kp&PNFuBOz+|TL?g61@'
        'rrW%kfB?*$ScSP34-)8+7k~m~_O$kW9Tux7RgxL0Kk1Xy1N+34h}{xA0ab=lKnw5SbslxQ7aMlb6nDY&taABYrX-NAI<K5yjV*R5'
        '5bc;<kJ>zm<*<G~_9J#(G7V%UQ`d?n2+hDtn>9d*GC&Af4zd&Q1bm&$pEQ{UT6Pxv7VK~aJW3h4pK>&CZsa8ZR-x{usIqu#D+QlX'
        'tW?=1S}rC)U$)fY|D+@{n0Rm2j(VMjNUC(%iEgJ=CmukYfIHKTmCe)8RDxZB>BlQ;DOwjaZ&F>6Kn-J<5G6_6fjLfbI-52Yu_Ec5'
        '2*8i1PTGV0)h^)-bFx%~Ef}3!0qRNK6;VCFfze~6aXp8AbZ;JKbYfm|q*E4AH455eYbPA@He$RD=FK!djd&MKOQvpk;VlUqJvDos'
        'u5#;uvk_UxiM9Pv4*>5~ZRu`+t<`TNxnw71Jb@`TO!U~cf8ZnYqY1T8mSP1y!PJ%TX(}lzQI#|2i{@Q9joDoAak@bw86TkIv>Dkn'
        'WC|+^0jQwS3t2T^C-=Nm=b5>ZqD2;Kt4u*qJ2I#*0BKM1#8z-4GJ!P#k19VZW~^Z4gVThQroFLtkHhpxRWx)oJ*5kKlMa)AV55H^'
        'TUu4lU`yW2lP((0R3uQfx#~#T>&okak!W-D`W2voIZZ?qsuaj<oKDb}^IY=4CLV0U)QZ(OA}gVh8=y}UZ)Sc~-YT4os6rML*5Q%#'
        'MrHqjy+DelHY4CYiLPV=z)se9=fVfLnv*)bA^f0;rnr}?X@vo41?^s9utzCgNF}yotSHrk0ZSi{Z)hTng|bP&eUyPH3%9^?4ZW$>'
        'nhEa28>(O6*Qxa#WD}Z_>ShtH0P~q)1fdz=)}hqqXEK%`vnLkjO_&$Zf0H`(ao8Giq|gV4s#DOB5R8J5jx}g!5UQDoz@o;<U3oJU'
        ';9F%ef?zWs`<~~KE!V8Pm&F~_Ic40lOmw=LTCqyQPxA|oC(5DF4ol7+D&dxQtfXdb0&Zm6L3p$gHi^-t$I{WGMYmCkAV+J5?R+6M'
        'vNkoixbWb*-QfA;-eE=2R1x+(Wz039k-+i=zpv4*!^A{g0)EEQ0&QcafbCfjPOUV9)K=b&N14%6R8CC3R=gj*U1tgS0?l|T#Xp`S'
        'nP5KdDsi-R-8__wyeZ7DN+_<%0wfi|J%;vYYH^iK(4=!IFSO8Hk|zxnGIA5crS?u}kaTk@(t3jp0MLpMASV%qQw<<n^`H$%wiQ6d'
        'O&rJ0Bxgrp!Koi~nf48}X(5fmbzrImXJUBN5|K7ta$*2=Tu7PEQBJ|k$Zu(aXyR?PMI;h%PV;U#^?92Mi7g=)jn(`psj=MT8O$j('
        '!KQ2Q<T=nFfwM|PChlPK5W{(2op0x@SBY8a-JDOI8wz{IXCRg8bv>R<{PsCDP8(GpR>~XNuhKHoiNTwWm1bcRWQXl3DI&|D?RA9f'
        'eAPOM^5PU@^KjzSw_fH#xzCe%E38UT6E(GuqxEtH_b<Tq)!5B>-Z`z9<)UaJW^n_pq#DYkmp9rp>7dp~VS=bVHGvh}OCYx~g1&HX'
        '#Vnz=b=xMk@D1&yOjXMBAhB`e4e~2OZh&&_NuYaxnbkH6ZU=@T(m@&-HBZx450a^}JkX4&htt2J=2bnmH7^7FkTVUi$x`uKxFNEg'
        'GYXWtj(Q@?=_UB#0!@mVdc>Vx6z1}ptt%8o0jrU=klQUV|IjB&B$pJERbb7&koODeR`aGZ9kBlKrYk^iU+&gm^I)(WfIJ)$FPL~4'
        'pn!5OZ<S41Bso^9GhxofQC+IZ^jEU9xL0dzw^@Lb9|qH;fQ`)4&b<V&A_-cZ*|9M?1@$rMri20u05<?fQ<@i4%?mJVhEBP?3h?4v'
        'Er622J~&ipkr1CEkStVId=o39%?{j@Uj<pFr)DJp%WAYYuv!ODhTq^~^g~`{{{NQ#>#tV(UtWU;#dPY(?`=r*_9T(cTX<ajyhY``'
        '0f}zR<}Ey)pZ8-(^l?6~y4W%Oc>VRAmZj4BetPvtX*NUQxjH)X9shv;xcZp&sK4r;^I!AdQhS5AE%@mBi0i+>G`Nqq{$IE`xm=e%'
        'Pd2=2?d%_}d-RcbQuoyd!Nscw%s;vQDi-mm_YT<9y@T~j=BQ%*dk}@8Yt39!z+t)uqh#&GQPKyysT?jjw)m3Gc_}|U-B;K0M4eft'
        '%I)0OaVrn;X}c<9IGLD-{>r%U4ffOh-S5OP2wXJ%&G2(>N#(w;P7g_ZzUgPm3LNXV7hvvh;GZAjpF0b4QQ%kqx7FoQ*jzHKdKMBr'
        'J4=!ZJgyWtvVIM^WM)Hk6?^#&`@en$-dz2(w0;(g`~4yP%ma}AY3Tt-AC=}K9U#NL4#soQTSl;vA)G<$`uA~I_V>$)A%ILlqx?CJ'
        '?O)=bzs5g9Gs;(gS~BB&pVX$;sQnMTNbTg^LI3~'
    )
    assert isinstance(_MODEL_, _pydsdl_.ServiceType)
