# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /tmp/yakut-dsdl-zmn42v0l/public_regulated_data_types-master/reg/drone/physics/dynamics/translation/Linear.0.1.uavcan
#
# Generated at:  2021-09-29 15:15:52.557315 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     reg.drone.physics.dynamics.translation.Linear
# Version:       0.1
#
# pylint: skip-file

from __future__ import annotations
import numpy as _np_
import typing as _ty_
import pydsdl as _pydsdl_
import pyuavcan.dsdl as _dsdl_
import reg.drone.physics.kinematics.translation
import uavcan.si.unit.force


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Linear_0_1(_dsdl_.CompositeObject):
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 kinematics: _ty_.Optional[reg.drone.physics.kinematics.translation.Linear_0_1] = None,
                 force:      _ty_.Optional[uavcan.si.unit.force.Scalar_1_0] = None) -> None:
        """
        reg.drone.physics.dynamics.translation.Linear.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param kinematics: reg.drone.physics.kinematics.translation.Linear.0.1 kinematics
        :param force:      uavcan.si.unit.force.Scalar.1.0 force
        """
        self._kinematics: reg.drone.physics.kinematics.translation.Linear_0_1
        self._force:      uavcan.si.unit.force.Scalar_1_0

        if kinematics is None:
            self.kinematics = reg.drone.physics.kinematics.translation.Linear_0_1()
        elif isinstance(kinematics, reg.drone.physics.kinematics.translation.Linear_0_1):
            self.kinematics = kinematics
        else:
            raise ValueError(f'kinematics: expected reg.drone.physics.kinematics.translation.Linear_0_1 '
                             f'got {type(kinematics).__name__}')

        if force is None:
            self.force = uavcan.si.unit.force.Scalar_1_0()
        elif isinstance(force, uavcan.si.unit.force.Scalar_1_0):
            self.force = force
        else:
            raise ValueError(f'force: expected uavcan.si.unit.force.Scalar_1_0 '
                             f'got {type(force).__name__}')

    @property
    def kinematics(self) -> reg.drone.physics.kinematics.translation.Linear_0_1:
        """
        reg.drone.physics.kinematics.translation.Linear.0.1 kinematics
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._kinematics

    @kinematics.setter
    def kinematics(self, x: reg.drone.physics.kinematics.translation.Linear_0_1) -> None:
        if isinstance(x, reg.drone.physics.kinematics.translation.Linear_0_1):
            self._kinematics = x
        else:
            raise ValueError(f'kinematics: expected reg.drone.physics.kinematics.translation.Linear_0_1 got {type(x).__name__}')

    @property
    def force(self) -> uavcan.si.unit.force.Scalar_1_0:
        """
        uavcan.si.unit.force.Scalar.1.0 force
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._force

    @force.setter
    def force(self, x: uavcan.si.unit.force.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.force.Scalar_1_0):
            self._force = x
        else:
            raise ValueError(f'force: expected uavcan.si.unit.force.Scalar_1_0 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: Linear_0_1._SerializerTypeVar_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.kinematics._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.force._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 128 <= (_ser_.current_bit_length - _base_offset_) <= 128, \
            'Bad serialization of reg.drone.physics.dynamics.translation.Linear.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: Linear_0_1._DeserializerTypeVar_) -> Linear_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "kinematics"
        _des_.pad_to_alignment(8)
        _f0_ = reg.drone.physics.kinematics.translation.Linear_0_1._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "force"
        _des_.pad_to_alignment(8)
        _f1_ = uavcan.si.unit.force.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = Linear_0_1(
            kinematics=_f0_,
            force=_f1_)
        _des_.pad_to_alignment(8)
        assert 128 <= (_des_.consumed_bit_length - _base_offset_) <= 128, \
            'Bad deserialization of reg.drone.physics.dynamics.translation.Linear.0.1'
        assert isinstance(self, Linear_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'kinematics=%s' % self.kinematics,
            'force=%s' % self.force,
        ])
        return f'reg.drone.physics.dynamics.translation.Linear.0.1({_o_0_})'

    _EXTENT_BYTES_ = 16

    _MODEL_: _pydsdl_.StructureType = _dsdl_.CompositeObject._restore_constant_(
        'ABzY8D1%gC0{^{MTW{P%6i%UOE)Atsxkwa&RiTn1#okRe=>`D`6b006wh=)U7ZrDGPxg#r&sd)ECR?bKN`P8niAo(Lo_IszC-4A|'
        'yz#;#e}yN`*z4WRCfjg{veHW9Gc)I$?|kQ*ncb7${WUX||FW0kP9THOb|p<13E3Uuh17O^5ye6>MRoSnhDuUjr3wA86I1<2U%sdB'
        '>e+1E<s`!SxrDatAQ7C}F?1yJr5$u|$_!LOxD1J6g4@>_rzFwYq}!&6M2m*8Y~p5j{75&(8YjNi_jGpJB}ygCOBI#+7DgJ8V{ett'
        '##b2)gMMz)Za@@ql}Q+$D2y<kIr~%H!mJ`p@Ze-&0;bBmU<Px6vt4KB2i(4xlD1E{Et#EirtFaNmI8ajCt>O1L}RS<(RVQlSe&qk'
        'Db_|{Q>&pMYH#6ByB<?+5kxmE1nU#2+(-ln_Lc0p^>Vw}W?#j*H8W)@{FVMdXV17&5gw2v7<6<W{Y0dN`KN&iyqOT+ltLn7tKBjB'
        '$X;EjRp#sS3$>-Ch5F)ry}r0yuU4;AYSsEetzKKKE-lY5)@l`PVx=CIXFQ^cBJn5PK=?WvLo3P750LD7ouZfSYPbRyB_a%HoKT-A'
        '8t4bv8F!QI(7=sFqFff}W_He%B29dX6CrhDg865@qoUa9kgZhBnX1m+iFj?kT?w5y^+M*mNPZd`m;L6Da}kz@CQiYiBbj3ubc&id'
        '1%r0guGqx_jd=r+7%`z-8QR*+r}_cZVHxpxAy(^BNov2ixKIs$>uly7rmpAT8~E9!H+#|*vCgbfPGl$Y1fs!A)@UTKWehPlVww;o'
        'l75q%a(!SZ33xwydYuFT<E?#*V9m@n(-1*+hG)@3n}jLV-|E?h^-y{!+_-S08<VMra3jV||KWh_n8AeUK`gP^J?+w+81-bjrkQ%u'
        '%UfYGKU8w<W5v*Pkepr`l2e<8!e^>;xS-%tcXYX7!E0cHa~~?O@E>~iY~Hgj)&$G$3m$Y6Ch$5oDTkJXHy*&7O?WG#N7#2I)B`#X'
        'R`M=`x8dC!B)kXLdNkhXjW&wOn<Z=Tks%8{#)5o;|4(u5)&L)6z{l}%aflD%`!qDoVh+k<<mAFIC!^^32EOdm!;X-iLFC6p(ad1b'
        'E=+1*&cbK#0(=fGd=FowJ-qGzgBRzV{C;%0_oLIlADw~w(JAgngkIePK6`#mv}uHAqeVi&TNdFK*<sSwhZW`8z>)OqRl&{K&ksD?'
        'vZ>-|!xPxN4i545V-fVHQ7aoGst=M%V_iY(O5a*89x^{H7T-qe?fr}Qn!CJC_bdB2@m&}a-=@H8?>JR=iqmb?>%2l>zr$~Rfq6$L'
        'upHfSDQi5BhQP8jP13a3rj_z7F1ESuDeM<G2Y<q^eRZj$Raf~?{zuySc|E^8+tkVvx0tkiF&8j=C}BKnn<=p3a!Gm7_OFyZ$M*Dk'
        'BHAp#ZKe&e2`zjR;#16uNC%}Gifu~)MgLr;5lt*5EL@yoRG%h_Fm3@00?Ny6GWEeCGT($~r6o4=F}_}de<S|G<od%1QNbUD0(a56'
        'yI+BO&4z#bZx-s5;{^=>00'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
