#
# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2021-09-29 15:15:51.571393 UTC
# Namespace:     uavcan.si.sample.electric_charge
#

from uavcan.si.sample.electric_charge.Scalar_1_0 import Scalar_1_0 as Scalar_1_0
