# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /tmp/yakut-dsdl-zmn42v0l/public_regulated_data_types-master/reg/drone/physics/time/TAI64VarTs.0.1.uavcan
#
# Generated at:  2021-09-29 15:15:52.533187 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     reg.drone.physics.time.TAI64VarTs
# Version:       0.1
#
# pylint: skip-file

from __future__ import annotations
import numpy as _np_
import typing as _ty_
import pydsdl as _pydsdl_
import pyuavcan.dsdl as _dsdl_
import reg.drone.physics.time
import uavcan.time


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class TAI64VarTs_0_1(_dsdl_.CompositeObject):
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 timestamp: _ty_.Optional[uavcan.time.SynchronizedTimestamp_1_0] = None,
                 value:     _ty_.Optional[reg.drone.physics.time.TAI64Var_0_1] = None) -> None:
        """
        reg.drone.physics.time.TAI64VarTs.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param timestamp: uavcan.time.SynchronizedTimestamp.1.0 timestamp
        :param value:     reg.drone.physics.time.TAI64Var.0.1 value
        """
        self._timestamp: uavcan.time.SynchronizedTimestamp_1_0
        self._value:     reg.drone.physics.time.TAI64Var_0_1

        if timestamp is None:
            self.timestamp = uavcan.time.SynchronizedTimestamp_1_0()
        elif isinstance(timestamp, uavcan.time.SynchronizedTimestamp_1_0):
            self.timestamp = timestamp
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 '
                             f'got {type(timestamp).__name__}')

        if value is None:
            self.value = reg.drone.physics.time.TAI64Var_0_1()
        elif isinstance(value, reg.drone.physics.time.TAI64Var_0_1):
            self.value = value
        else:
            raise ValueError(f'value: expected reg.drone.physics.time.TAI64Var_0_1 '
                             f'got {type(value).__name__}')

    @property
    def timestamp(self) -> uavcan.time.SynchronizedTimestamp_1_0:
        """
        uavcan.time.SynchronizedTimestamp.1.0 timestamp
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, x: uavcan.time.SynchronizedTimestamp_1_0) -> None:
        if isinstance(x, uavcan.time.SynchronizedTimestamp_1_0):
            self._timestamp = x
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 got {type(x).__name__}')

    @property
    def value(self) -> reg.drone.physics.time.TAI64Var_0_1:
        """
        reg.drone.physics.time.TAI64Var.0.1 value
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._value

    @value.setter
    def value(self, x: reg.drone.physics.time.TAI64Var_0_1) -> None:
        if isinstance(x, reg.drone.physics.time.TAI64Var_0_1):
            self._value = x
        else:
            raise ValueError(f'value: expected reg.drone.physics.time.TAI64Var_0_1 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: TAI64VarTs_0_1._SerializerTypeVar_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.timestamp._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.value._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 152 <= (_ser_.current_bit_length - _base_offset_) <= 152, \
            'Bad serialization of reg.drone.physics.time.TAI64VarTs.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: TAI64VarTs_0_1._DeserializerTypeVar_) -> TAI64VarTs_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "timestamp"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.time.SynchronizedTimestamp_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "value"
        _des_.pad_to_alignment(8)
        _f1_ = reg.drone.physics.time.TAI64Var_0_1._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = TAI64VarTs_0_1(
            timestamp=_f0_,
            value=_f1_)
        _des_.pad_to_alignment(8)
        assert 152 <= (_des_.consumed_bit_length - _base_offset_) <= 152, \
            'Bad deserialization of reg.drone.physics.time.TAI64VarTs.0.1'
        assert isinstance(self, TAI64VarTs_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'timestamp=%s' % self.timestamp,
            'value=%s' % self.value,
        ])
        return f'reg.drone.physics.time.TAI64VarTs.0.1({_o_0_})'

    _EXTENT_BYTES_ = 19

    _MODEL_: _pydsdl_.StructureType = _dsdl_.CompositeObject._restore_constant_(
        'ABzY8D1%gC0{^vG+iw-e89xRLwz-E(NJ7GpreL=|d+g&22hy~-Bs6G)p<oge1k0S=v1h{GGBa!YAVq2(S_NsPu9R)XpO8NxQeUd3'
        '4@m7}AELhXElQs&Me0kxZ+7;aV=j%ND3;-yoy+%q^Id=A-|YCqpAI+7Pktip1u6&~PcbQIDDKm4$Q;j4qBK!Lvoha%UCYeZnPe-y'
        'l$D>BQy-Tfm6Q3X7t;vVPfE7t1Tu-4lk%PtzH+pPn6t8UX>tBtDpypQk9q4%Dv`t`Z{)k)wc}4qx8aWbuKc*ncY9Q8DY}_vs=N){'
        'pP^TOSDBAq6f6t|`b>BM)zs6dB;Qs|^3nWcM%R5BS2|tq#XbjB#eEj6z=YB?N=v?rkGmso12y4$KsrBQj~{xL9;p<O&|)3*ICLXc'
        'Vl8IDrC75yCbwE?x7QWg3t7CTdFggQOP?z3MM(f!9?y?ntr_7l=K`!<#w9S#$ZyMQWq#NL9piw?V3^T^tP5A$9SL71iup+#l=%)X'
        'Nc{5V*V`J670yVUMO`LIvPy<_DWW;mgwu6KQmPaSh!U~Sh)N<xs00y`${vZ}GuA}Ju;1*|&IB^G^T0HbVhxrjg~Oa_vkMJOx>T_#'
        'A`}VOssNjil*uMd(@^+SgU=m;Z2U}0<kLTbk}}06z)_^jh-4pT;2Su;DwAlyUG?2(n2`t+V{)1(#>^%^0lq4Qi;8#+X63qoyBSr4'
        'kv;*p0Oi(cm@(8+CnRR;XeRh?HB2@t{rc+*i%l>I*$@Hf$$Sbro|~8;q)FO$78bW!7PixFl4;UzcNR#GQK_cM1{XfZr4&4;dk$G5'
        'i}Qx(&{@zsgV>Q|Bgw)51c3xXvN&cwQ;JFv_9_)15QxyKuPvAjj)Au5kp+;dd6FsIWyHgBkO2!qK^ib-n*!_=YlvgwOQD2vs>@sm'
        'Ar^$+ys)%PCgVhti*HU5h=dqyDM6l3B?Lv5qP@<LZV!?aC8o3&Ce-*C90kR|F^aF$t|AetzXqEXr(uX5#&BB;S<`H<M69xbp&|wo'
        'RgCJsA0Q}BYYYptfyC7q97Di}$|)fc_T^(2k{HuO_w$Y);;-1zNw>pa<*&I7%qM=jN}XLdmfhtm?=6>nDnIo;lgZ<vO}v5M&>HvR'
        'WFvOUe5Yp=D)X1?qQEv&2skWeTS~&%H4~pSto7jw`8ZtJ$5||g7ws6<^O2bnHB;TJ%ko1*b<pefsuGL0nB*_=Io`~mpacwrLOQXa'
        'e30++R>dX@Jam*Nf^s=O=&2-=K7)mjc`1c*k@J?0(pHb&%XAYpZ{CmM`S$uu*h;f5<faETJPVQKpopqwm0qo?fVR*gt)~`HXV#f<'
        's$EbHJx&#f#RT_k3YHJR%zs<1QW^yi6oByn8J<YUcQhkLCZsKel++uEyw@}_uZAQVuNaXK3z~1qAz+Y%S(W7`$p>=agNro|Sp;@V'
        'A}C>j6^s$tO@I^BpSsSPEL(>?iEOHr`C?TJMKZL2d(6RV+YP~!r|L);6lb`!e*C-4_xw`mcg**7)(_KsyO*S8PM*a?^`dS9?g6V_'
        'W>I3x-WA9<suMYAGCMt=LxPw5YQFy}4Y2w>v5DWn)#WS<p};@B$`^iLPP&~!b)i+K6^GIt%ervSNW|E<U_du<unU_P1Pd~CNAO&u'
        'aJN~y9qG2h-C@5+k&YDZPCLKL&W~9-Zs#YE?kwEhcK;rvV}-jH>5jtPXZP<%y1Q@>*!6=*M+^5k%jXc%=L+{Q(gTHi1nIuQJ&JTs'
        ';XaRaqHvGd^DkJrFIqV-Sw6?DyqA%_RJgAoeX(#)Abp{53DRSQdlKpMh5IVfqlNn;q(=((HKd0N_s2*N749jk*J-2&3wP4$H-&V6'
        ';r_(x`BS8O3wPS;+qCy}tlll8<Apn8^`Aw$t8m-)9&^?n^Y%W*uiFcE(cbHfwQtAX?`-9F_nf7#TlzCg->~%Omj1%h^OnAC=}k+y'
        'rJI(1V(CLmKeP06OCMSKrKMk4`b|YIkB!*Dv3f9B4?6YW?Rs#t9`JgwSr0y`2M_DPXZ7Iodhn<od|3~^st4cLK?e8@YCd!dEZ%mm'
        'i=`WS%D5gN%Bj48t*MVAhXCn`Z^6qI9JRpsF*rKJ=J@|(^8}9}7RU30*Pn@3p<AAZZrSFiKQVXOsi|0;kMTn1Z^bmW)%G@7?vE8='
        'Ax#HRa`x<*ndZza{I1N*oHM`g6VM8KHRVfCZ2rmrq4<Rd{LN+lR_=eF)&y%UV}q8pLDi*<4WK8@)?JDJ3OdluKW=X{uGdxG>{+h*'
        'd`P=2B$Hh0RGn+JeChO3M<=aNbm9IjV*`ilD4cT0ud_t60WPh2tpSC=v1%g9^p+JCrHU-+BocsT30hmm78g{AxrV`FcnNwG4Vx9*'
        'wYnm#x)QTWK-KMr5H?kYS&+#J6az3jJA1ahI5&Id%nV{Pkpu>=;Vwx7QEl6Tl|cYNJA-==k{PfJh)ZuURy_frArlUkmnf5jfSJQS'
        '&ov3~H9&2_Fm?`5r^q4#JtlIjX=tbtVjHT#q!k8)1Cjv-WDq+JxtK{fE=eGipBZ3<8_X$V8VCfjE_4qK09acALO|Wo5q^?d@o1dH'
        '&+w^Y0Pa%dZ0lyk>9Mgn1b_dMGp6mg@4z;rjzlN|HlcuWr4~MfpsbB=R0efSz7d;7L{$gzQDMRXf0{<MA-{DQyqaR<%{Bo70we*E'
        'ZP=$solRW^(Nn!=2D?Ed<`uG<w!8@uU>Us5;0}<0VWt3s*0*Vc96R+oyxG2kUdlXjfI+PnUDXDCe`mD}mnSrv8))WCl>8EZr$QoE'
        '__aP@d9OdZH3U=615Du_q7!}>suhKQ-H*x|QYilC<$g&XtpGcp;$Lj3#>eyVi|};OkJmn8Yaf*Ph_1n-F~ev28~N$E`I&a7JvYC&'
        'IM-QdcRCAaJF~NAX69!*bMu|~h1tck?S=XI3dtME`yhl82@eJ-C`2|E&_}l_Q{HLco_GsaNxeF4@Mq--^<f6sIhd|9$y5SpD<XpQ'
        'awaat<}usDw;jHz+2e1PdMh{#q6nWaJ*Ej=ry?|ex|mpk$+&6$x`XbpZ`~)ku`Md1L$lbvgy5xug?y5K&Hv8-!~dQ2tNH2=Rn4I>'
        'K2gy57vB~(*M_j~5qKox72~IZ=zP4w&`^i)?@v$V_AiLKk*!f@f^AE55{OQwaMNAbba$|+j@Yf!PYYCQ+`sUH9~>NMH27Z!_T@jI'
        'eOJ`?vG51mKvnbc!6=NLWy9-zJ9NMfoq>7&TN&*k%szb5Xj`YzXwLrtgnxoP#uNYm'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
