# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/silver/zubax/sapog/firmware/tools/testing_uavcan/public_regulated_data_types/uavcan/node/port/SubjectIDList.0.1.uavcan
#
# Generated at:  2021-09-29 15:16:17.854788 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     uavcan.node.port.SubjectIDList
# Version:       0.1
#
# pylint: skip-file

from __future__ import annotations
import numpy as _np_
import typing as _ty_
import pydsdl as _pydsdl_
import pyuavcan.dsdl as _dsdl_
import uavcan.node.port
import uavcan.primitive


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class SubjectIDList_0_1(_dsdl_.CompositeObject):
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    CAPACITY: int = 8192

    def __init__(self, *,
                 mask:        _ty_.Optional[_ty_.Union[_np_.ndarray, _ty_.List[bool]]] = None,
                 sparse_list: _ty_.Optional[_ty_.Union[_np_.ndarray, _ty_.List[uavcan.node.port.SubjectID_1_0]]] = None,
                 total:       _ty_.Optional[uavcan.primitive.Empty_1_0] = None) -> None:
        """
        uavcan.node.port.SubjectIDList.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        If no parameters are provided, the first field will be default-initialized and selected.
        If one parameter is provided, it will be used to initialize and select the field under the same name.
        If more than one parameter is provided, a ValueError will be raised.
        :param mask:        saturated bool[8192] mask
        :param sparse_list: uavcan.node.port.SubjectID.1.0[<=255] sparse_list
        :param total:       uavcan.primitive.Empty.1.0 total
        """
        self._mask:        _ty_.Optional[_np_.ndarray] = None
        self._sparse_list: _ty_.Optional[_np_.ndarray] = None
        self._total:       _ty_.Optional[uavcan.primitive.Empty_1_0] = None
        _init_cnt_: int = 0

        if mask is not None:
            _init_cnt_ += 1
            self.mask = mask

        if sparse_list is not None:
            _init_cnt_ += 1
            self.sparse_list = sparse_list

        if total is not None:
            _init_cnt_ += 1
            self.total = total

        if _init_cnt_ == 0:
            self.mask = _np_.zeros(8192, bool)  # Default initialization
        elif _init_cnt_ == 1:
            pass  # A value is already assigned, nothing to do
        else:
            raise ValueError(f'Union cannot hold values of more than one field')

    @property
    def mask(self) -> _ty_.Optional[_np_.ndarray]:
        """
        saturated bool[8192] mask
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._mask

    @mask.setter
    def mask(self, x: _ty_.Union[_np_.ndarray, _ty_.List[bool]]) -> None:
        if isinstance(x, _np_.ndarray) and x.dtype == bool and x.ndim == 1 and x.size == 8192:
            # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
            self._mask = x
        else:
            # Last resort, slow construction of a new array. New memory may be allocated.
            x = _np_.array(x, bool).flatten()
            if not x.size == 8192:  # Length cannot be checked before casting and flattening
                raise ValueError(f'mask: invalid array length: not {x.size} == 8192')
            self._mask = x
        assert isinstance(self._mask, _np_.ndarray)
        assert self._mask.dtype == bool
        assert self._mask.ndim == 1
        assert len(self._mask) == 8192
        self._sparse_list = None
        self._total = None

    @property
    def sparse_list(self) -> _ty_.Optional[_np_.ndarray]:
        """
        uavcan.node.port.SubjectID.1.0[<=255] sparse_list
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._sparse_list

    @sparse_list.setter
    def sparse_list(self, x: _ty_.Union[_np_.ndarray, _ty_.List[uavcan.node.port.SubjectID_1_0]]) -> None:
        if isinstance(x, _np_.ndarray) and x.dtype == object and x.ndim == 1 and x.size <= 255:
            # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
            self._sparse_list = x
        else:
            # Last resort, slow construction of a new array. New memory may be allocated.
            x = _np_.array(x, object).flatten()
            if not x.size <= 255:  # Length cannot be checked before casting and flattening
                raise ValueError(f'sparse_list: invalid array length: not {x.size} <= 255')
            self._sparse_list = x
        assert isinstance(self._sparse_list, _np_.ndarray)
        assert self._sparse_list.dtype == object
        assert self._sparse_list.ndim == 1
        assert len(self._sparse_list) <= 255
        self._mask = None
        self._total = None

    @property
    def total(self) -> _ty_.Optional[uavcan.primitive.Empty_1_0]:
        """
        uavcan.primitive.Empty.1.0 total
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._total

    @total.setter
    def total(self, x: uavcan.primitive.Empty_1_0) -> None:
        if isinstance(x, uavcan.primitive.Empty_1_0):
            self._total = x
        else:
            raise ValueError(f'total: expected uavcan.primitive.Empty_1_0 got {type(x).__name__}')
        self._mask = None
        self._sparse_list = None

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: SubjectIDList_0_1._SerializerTypeVar_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        if self.mask is not None:  # Union tag 0
            _ser_.add_aligned_u8(0)
            assert len(self.mask) == 8192, 'self.mask: saturated bool[8192]'
            _ser_.add_aligned_array_of_bits(self.mask)
        elif self.sparse_list is not None:  # Union tag 1
            _ser_.add_aligned_u8(1)
            _ser_.pad_to_alignment(8)
            # Variable-length array: length field byte-aligned: True; all elements byte-aligned: True.
            assert len(self.sparse_list) <= 255, 'self.sparse_list: uavcan.node.port.SubjectID.1.0[<=255]'
            _ser_.add_aligned_u8(len(self.sparse_list))
            for _elem0_ in self.sparse_list:
                _ser_.pad_to_alignment(8)
                _elem0_._serialize_(_ser_)
                assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
        elif self.total is not None:  # Union tag 2
            _ser_.add_aligned_u8(2)
            _ser_.pad_to_alignment(8)
            self.total._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        else:
            raise RuntimeError('Malformed union uavcan.node.port.SubjectIDList.0.1')
        _ser_.pad_to_alignment(8)
        assert 8 <= (_ser_.current_bit_length - _base_offset_) <= 8200, \
            'Bad serialization of uavcan.node.port.SubjectIDList.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: SubjectIDList_0_1._DeserializerTypeVar_) -> SubjectIDList_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        _tag0_ = _des_.fetch_aligned_u8()
        if _tag0_ == 0:
            _uni0_ = _des_.fetch_aligned_array_of_bits(8192)
            assert len(_uni0_) == 8192, 'saturated bool[8192]'
            self = SubjectIDList_0_1(mask=_uni0_)
        elif _tag0_ == 1:
            _des_.pad_to_alignment(8)
            # Length field byte-aligned: True; all elements byte-aligned: True.
            _len0_ = _des_.fetch_aligned_u8()
            assert _len0_ >= 0
            if _len0_ > 255:
                raise _des_.FormatError(f'Variable array length prefix {_len0_} > 255')
            _uni1_ = _np_.empty(_len0_, object)
            for _i0_ in range(_len0_):
                _des_.pad_to_alignment(8)
                _e0_ = uavcan.node.port.SubjectID_1_0._deserialize_(_des_)
                assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
                _uni1_[_i0_] = _e0_
            assert len(_uni1_) <= 255, 'uavcan.node.port.SubjectID.1.0[<=255]'
            _des_.pad_to_alignment(8)
            self = SubjectIDList_0_1(sparse_list=_uni1_)
        elif _tag0_ == 2:
            _des_.pad_to_alignment(8)
            _uni2_ = uavcan.primitive.Empty_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = SubjectIDList_0_1(total=_uni2_)
        else:
            raise _des_.FormatError(f'uavcan.node.port.SubjectIDList.0.1: Union tag value {_tag0_} is invalid')
        _des_.pad_to_alignment(8)
        assert 8 <= (_des_.consumed_bit_length - _base_offset_) <= 8200, \
            'Bad deserialization of uavcan.node.port.SubjectIDList.0.1'
        assert isinstance(self, SubjectIDList_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = '(MALFORMED UNION)'
        if self.mask is not None:
            _o_0_ = 'mask=%s' % _np_.array2string(self.mask, separator=',', edgeitems=10, threshold=1024, max_line_width=10240000)
        if self.sparse_list is not None:
            _o_0_ = 'sparse_list=%s' % _np_.array2string(self.sparse_list, separator=',', edgeitems=10, threshold=1024, max_line_width=10240000)
        if self.total is not None:
            _o_0_ = 'total=%s' % self.total
        return f'uavcan.node.port.SubjectIDList.0.1({_o_0_})'

    _EXTENT_BYTES_ = 4097

    _MODEL_: _pydsdl_.DelimitedType = _dsdl_.CompositeObject._restore_constant_(
        'ABzY8L4#Cb0{^|3`)?H26~~XkhQ-EUa4;lk;I_@f5PLT!O$ziu&BKy2EJff%R8>2=yK{H%HM29*xp!<YZB$aJ5tgphl`{RiDpjhK'
        'A0zdbC_nY5s=p=Y&K!Fm*(Lp@MS}0_+{fHGkIy;7v+2KndIpL=_EORfbP!g3EmFlp^^`Y4QT3Z~CyBK(BDeE*M5sD=8EkbEk$;w7'
        '{v`i6U$)156-6S=CD;=mMk<bmhiCkVcX0W|jPEpgRE^?5RFgP0)kj%lTQtq)oqI}~+*bS@k!oD;b~^qMU4NE);7xs+f0EldpBs~^'
        'MrMT0e}h|3IP>AG+|Fz$5eEIk%=!U0+&Auo_SFf?)0B5}`_hKm6Tv+ZwT)bNw}xM9-WQ?hh{(`p6V8&P&SYu_XUyG-<52Js^UV1T'
        'W&E&sOzutL37cFSzk^oF<t4lH;9vu{ta=;A>TbxH<<I#;Jf^P=j{=?sgB$H<4SNE2N_bP5Ze9mwr~O8#bNlAOIs3Em$Y%6+ZcpA)'
        'rhNNH_><0SkNR<vTQ+GE-R(5uP&ISASQnibtzgiJzf45RO`HzKOj9a!jC|LgeJB!P)cAQv{3q`4@)}M&eLo9Bo_0rP;buEL%tZc|'
        'eA%1o=?1?0wBJz?y>^H16<5cdQL~Wa5^u`Qg`P%pi@k(LMX24+8g8+iwbLE0pX9hUi1Ae(Z%M&a6o@^RiX;^py{?&YHv_y>EhSP`'
        '9HGj#(oC?`RYuclnHE8nZSYVRw|S$y8x{9+eAv12P2~movOWJ1$JoKRnG|*MBBsXtBa>!Llci#KY}URqImL2$Ql9drJaCyL&tUcp'
        'Jo%Dc{18phjzq8-8POK$@XoJ$^YRUOSzg&MtTR)ZTY47U8!Xz&?KpB#X!=Vo$ls1%e6+s)7?;Y1yk%cI2qW|X+RHg%C}S!Qi}2y$'
        '!M?cWL@VV@cNb&1vO(84Zl|xUU0=&xPB<qDyEs4#ztJrz<POB;uceYA!_*6$JDVJlmhanBe#>RN?+oXwAir<V_&Uzgroe$v_zB0v'
        'vU@cdcSKFA5NTC=nl<=dP4gsf*IFv=?DAC94CcA6;bV=8+J5PiT9P#|FZ@)rF$D2}eGusyO>u6kxu@3--Bw+zzEdrSF{OOTH69~%'
        ')IrSbsHVvG(GAyV{wgkDE?83@wS{IllLexs(66k~Eh1JYqKN_9EDT%C<%+D8mc1(9BZn2a_J9Wgp8i`IiK92k6)uJ5G2IZ{NjW?B'
        'D(K@o-h#Y~e>XmM`B)~JcZBq4nWWw{{hp!U$DB_0yyH%f^t=j<pKyA-=gm4j*7N3^&h)&KG=JXd(VlmT)}5yP7HIt$rwcvrEa@WY'
        'OQh#Wmq^c(ULbv$^cB)qNxw(>8tFySOQekS`=mc0{UPb=q;HVEN%|J)GU;W~E2M9eu8^*hR!M85?~tyMUL}2(^hc!ck-ks*W72D+'
        '*GX@X{)F_Wq(3A5Iq6N(UzD23O}Z%2`nLDAJ$q0wTCO&i<#T`*6{N*m-jqvZdF45-nGmAq5IQb(qp>B%RX<l@FjriwFch>E4BDZs'
        '&Odbd@}fF)%zskU5$|hU@W&#^LEf$Z>$HpVgJ9Ki6HAEDZnT1<{~0q%1!hiT8f)Q)uJgeR=IhK|vbZ%+Q(TSVhGFirhG4E@U=`9v'
        '@W9P;+3d;`Q!Uns%eBKbsRY2-TC;UnGnS}k9AdY6x07JYFj_BUhUVMdmwWeR*P8zw1P{+qE6y<pK>7RqqHv52h(C?x6F65tCoG}I'
        '@b6?S!3dUsumpr97{L+{mVmGXge4#>0bvOUOE7{ZAS?l42?$F-SOUTl5SD<j1cW6ZECFE&2una%0>TmymVmGXge4#>0bvOUOF&ox'
        '!V(acfUpFFB_J#TVF?IJKv)985)hVvumpr9AS?l42?$F-SOUTl5SD<j1cW6ZECFE&2una%0>TmymVmGX2UvpMVM5NB*kGT5sd!_('
        'ERsCL%+p2VSCq@BU8W-s!*Au7id=dYITnm*fELOI=y~y^%I)<B>$f+zennl73@Kja?}{GgYQKkZIkzl7kW2DQS>L`n1t7oLzKgQG'
        'j{jtb>G+5LYfs|7)-Wm8hSKu!bv#iYV!E6>XsGJ!VP`Th16vlRG{e5WEmoM0(T>j2oE5#;s#Z@0!;g#tbh~jD2FSc80zH9?+(B8O'
        'TG-BHp<yOw62F8(+&-GccCu*QR-3LhO?lA+=`PZ<qp?Sd8FnnL<t%)<!gd9A?C}mBmzmv|i9KAx;-u&^Z{TUP>Lj@F4)y1&Wd$o<'
        'cV!kI>ZS|^O%W*+If6JY&^g_a_dW<5d)ha={ep`4w-?mHKKlCi{!vc*{5xykeDTRXTJg$-@5{f-f0y;lRXh9+LwJr9xk~@$A!tYL'
        'mnkOau%s-MpB_uHj*;ww_`i+u?R##-McQ^9ukd3IeT1=<*DKHL5;pSXe@&#m#PWzTYD4xNHk@QHHf*mi=<1*KsfCeJQz^bY$yAkR'
        'lNtktqs!06HwM*j0AStY6p;}C00'
    )
    assert isinstance(_MODEL_, _pydsdl_.DelimitedType)
