# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /tmp/yakut-dsdl-zmn42v0l/public_regulated_data_types-master/uavcan/si/sample/mass/Scalar.1.0.uavcan
#
# Generated at:  2021-09-29 15:15:51.546942 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     uavcan.si.sample.mass.Scalar
# Version:       1.0
#
# pylint: skip-file

from __future__ import annotations
import numpy as _np_
import typing as _ty_
import pydsdl as _pydsdl_
import pyuavcan.dsdl as _dsdl_
import uavcan.time


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Scalar_1_0(_dsdl_.CompositeObject):
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 timestamp: _ty_.Optional[uavcan.time.SynchronizedTimestamp_1_0] = None,
                 kilogram:  _ty_.Optional[_ty_.Union[int, float, _np_.float32]] = None) -> None:
        """
        uavcan.si.sample.mass.Scalar.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param timestamp: uavcan.time.SynchronizedTimestamp.1.0 timestamp
        :param kilogram:  saturated float32 kilogram
        """
        self._timestamp: uavcan.time.SynchronizedTimestamp_1_0
        self._kilogram:  float

        if timestamp is None:
            self.timestamp = uavcan.time.SynchronizedTimestamp_1_0()
        elif isinstance(timestamp, uavcan.time.SynchronizedTimestamp_1_0):
            self.timestamp = timestamp
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 '
                             f'got {type(timestamp).__name__}')

        self.kilogram = kilogram if kilogram is not None else 0.0

    @property
    def timestamp(self) -> uavcan.time.SynchronizedTimestamp_1_0:
        """
        uavcan.time.SynchronizedTimestamp.1.0 timestamp
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, x: uavcan.time.SynchronizedTimestamp_1_0) -> None:
        if isinstance(x, uavcan.time.SynchronizedTimestamp_1_0):
            self._timestamp = x
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 got {type(x).__name__}')

    @property
    def kilogram(self) -> float:
        """
        saturated float32 kilogram
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._kilogram

    @kilogram.setter
    def kilogram(self, x: _ty_.Union[int, float, _np_.float32]) -> None:
        """Raises ValueError if the value is finite and outside of the permitted range, regardless of the cast mode."""
        x = float(x)
        in_range = -340282346638528859811704183484516925440.0 <= x <= 340282346638528859811704183484516925440.0
        if in_range or not _np_.isfinite(x):
            self._kilogram = x
        else:
            raise ValueError(f'kilogram: value {x} is not in [-340282346638528859811704183484516925440, 340282346638528859811704183484516925440]')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: Scalar_1_0._SerializerTypeVar_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.timestamp._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        if _np_.isfinite(self.kilogram):
            if self.kilogram > 340282346638528859811704183484516925440.0:
                _ser_.add_aligned_f32(340282346638528859811704183484516925440.0)
            elif self.kilogram < -340282346638528859811704183484516925440.0:
                _ser_.add_aligned_f32(-340282346638528859811704183484516925440.0)
            else:
                _ser_.add_aligned_f32(self.kilogram)
        else:
            _ser_.add_aligned_f32(self.kilogram)
        _ser_.pad_to_alignment(8)
        assert 88 <= (_ser_.current_bit_length - _base_offset_) <= 88, \
            'Bad serialization of uavcan.si.sample.mass.Scalar.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: Scalar_1_0._DeserializerTypeVar_) -> Scalar_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "timestamp"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.time.SynchronizedTimestamp_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "kilogram"
        _f1_ = _des_.fetch_aligned_f32()
        self = Scalar_1_0(
            timestamp=_f0_,
            kilogram=_f1_)
        _des_.pad_to_alignment(8)
        assert 88 <= (_des_.consumed_bit_length - _base_offset_) <= 88, \
            'Bad deserialization of uavcan.si.sample.mass.Scalar.1.0'
        assert isinstance(self, Scalar_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'timestamp=%s' % self.timestamp,
            'kilogram=%s' % self.kilogram,
        ])
        return f'uavcan.si.sample.mass.Scalar.1.0({_o_0_})'

    _EXTENT_BYTES_ = 11

    _MODEL_: _pydsdl_.StructureType = _dsdl_.CompositeObject._restore_constant_(
        'ABzY8CxcXB0{^X7TW=h<6_#wvy7?N}j^j89ou-!5dS|88uDnj0wysh)0b|*)>_%wOPB}BwlF-~ra#mUc1)7Hz7BD~u$P~y=$WO>)'
        '(c~dOfj;La1pNhh>^U=>mE_oO6(D_Q$is6E&z1Visejx!J5l}QZ>6I^2chF?t|SZPQ|5)-as4Dp6D<ud^Rrt<WxmN2e>_Tg`DwZQ'
        'N%`k;DW7s<7Qz1Yj17GjJ6bxLMJb$)nAXmg&qAike8wGerDYPAVj`dZjio;==_H-_Tlq<u&%4YRCB4jWUH%>fzr>_5SD8=UlROL#'
        'O__58W|(WxK5?R66jS*PYnhP|ceX~cFH{oCr#yHJ3)+COrI;48jV0m?Xcrgk@r9S!kt!KUBZpwe!jo9bLCk{>W5Wkr9e2>Y>q+B='
        'JRTTP(mq(}Gi}@`3Bbzh`IU!_AUx)5z}|h_Lf8DYd{pL_T(B_?m<o;xI><b@+I%E^m1yoKaZu)`+#vDG?f;&bn0PEWiL=P#iX=Pa'
        '2$v>CFhc|za*{%TctEs_eNJ=|al#a+P)v<T1fQ`XG6w#N(>QY|)UJcjM9BecFG+_xw<<1lF!7k?%S37t@Er+0At_famZqWfnSq!)'
        '1jYE7QYdG91T|%v&q1Jw$BE*9${;pyd`BhGp>#bCUnPt{jv20Q5zTqU<R>6kr*Kgj4`5XdCETqtMOND9;1*!qkcAmXD@{UTK14Uc'
        'pPew-tL+=__tsnB60#=)u#@`?Y<zcaj*u4V{Gqpg+_S*Wyd*QE)9Lrfh%=>ckv$=Ofm=`#u^Bn!E?MtZGLM`EyEDigMfQ>`3_uZR'
        'AS8=p?sKh~lHsT}0TO{oqsP{Q+u#^jixKI8RwI&3BUhy!wu1~r5C+;nFyEKpuh>8y6JJR!wNqbaBZOR#erx0ICRvITL+-u5Odu0t'
        '@TCHMK2wksS&II;O}r5lDQZmFC`?!tV+a)V0jDzjaT6*Mq4@(~)`Ep0Mi|p=5b{>VUaQ#QhmMLkEYvw_#&Lk8STvXx=mUkjF$9Ky'
        '6SY%9A)L!+Hj)_2#Ek1sEQmKPb%XZB+u|KMf%PO7>(ZHivPm}|e7sqT<^1Mvxk{c_UF93Z4ZX1&Cws9|=BM4tpfZ1>X$pKlg@nUq'
        'cC01LJgV}Og^fL;m(RkLeO%SBf6vmepHHroXqomhkLL?V`k?EL>h6lSSQ6L7nrLOvPy!B0p`3V79^~iT9l6f~7X#(Wpxn$ax;n{}'
        '&tW6vZpxrt<f3h&v^`?GnQ5Wrt*24k?F?7KcA9xmo37%6EJTrqO;oq)@@m%&w2dBVzp#NitImp3b3r?F1=FAw3*5COSRR0z|Gin4'
        'G%6sd0P_JVJW){Z=tj&;C|d?4Y4#Ge+p2P2AJJGvrBVsGV8pQ+0s%>w)m2^<`Jo>85ON@(iokD41T8GEiZLU-1SCQKY5HtcWkcXe'
        'R7<Dampk%ECc_BW<qmdRFN8?mY%<}nIm4yR^WSBD=9kiZRDEypahm2Q-6Sn@@-iWM6nP1R2fTWpM~Q8F51`(dNz~zxIqmua3cM5#'
        '^Yaf`fZgwVOyUXdZe}42<k9oHqWAZ5iS`Ta!KhAa2_>D$Jh*2hV;o#Suze(^ad<(ppinxA=Ozkz!s1E969qkGzo!r<3wqkFPuukw'
        'i?eop4)JtB=Pmyk#F>JgMLbo|bC&-+;(S3b*!_!$Qw4p+%2_~srJ$D(FBJ4L;<<ueK|E8?R}tq5dexqP&FZ~o^}KH7T(|n(KzzNR'
        'Zz5hR=v#=d6_g-eE$9uzR}1<!;+2B_0P%7`-$A@o&>tc$6!fOGYZ38cL6@w3%ZTR-`Xg)Sj}gxn^p>@^W$)`)yW5Df1zoZBuOdzt'
        'v}5nFX8qB%_o?D~vY_ksUbn4(`}Tf!>bTQ)E&jyfPc6P@@n;r)Zt)iuKd`uMQCQr!_{`#G7C*Q6g~hKeeq-@li{I6Fe`eAWR~urf'
        'A^HvRK|^deglLHUhIrNxpEbni4e>=oeBBV=G{m<J@tq|yc)vl<he?6W+pc-ox?!fwn!^|6az25hY5b0ar{3&67?$SP>kwuWf!Wj%'
        'i_buC#0Kz8$?#$LUcR{2UFq~YYu)wrwSKSD@AvNXS66SZbXWUp-F~;Xx_+nA>vrqeQK_HVm0>b~xeD6FmoQAkT~zTeaZ&t7e3glf'
        '1M&W*_*L%zA7+7;?fRMD#%F%Je&!z?1LD^QXodJtd{j4>2jbDV4}CnQ9v$gTmtlzGREuBO<nr0N$H7>^{|{a$ZA-Xx5`6JTnD`8S'
        'J<$8lO<4HdktRo=$#IQL+rYGa$mC+b``$9f*7+Z^fI#9b4FCW'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
