# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/silver/zubax/sapog/firmware/tools/testing_uavcan/public_regulated_data_types/uavcan/primitive/scalar/Real64.1.0.uavcan
#
# Generated at:  2021-09-29 15:16:17.679086 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     uavcan.primitive.scalar.Real64
# Version:       1.0
#
# pylint: skip-file

from __future__ import annotations
import numpy as _np_
import typing as _ty_
import pydsdl as _pydsdl_
import pyuavcan.dsdl as _dsdl_


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Real64_1_0(_dsdl_.CompositeObject):
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 value: _ty_.Optional[_ty_.Union[int, float, _np_.float64]] = None) -> None:
        """
        uavcan.primitive.scalar.Real64.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param value: saturated float64 value
        """
        self._value: float

        self.value = value if value is not None else 0.0

    @property
    def value(self) -> float:
        """
        saturated float64 value
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._value

    @value.setter
    def value(self, x: _ty_.Union[int, float, _np_.float64]) -> None:
        """Raises ValueError if the value is finite and outside of the permitted range, regardless of the cast mode."""
        self._value = float(x)  # Range check not required

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: Real64_1_0._SerializerTypeVar_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        # Saturation not required due to compatible native representation of "saturated float64"
        _ser_.add_aligned_f64(self.value)
        _ser_.pad_to_alignment(8)
        assert 64 <= (_ser_.current_bit_length - _base_offset_) <= 64, \
            'Bad serialization of uavcan.primitive.scalar.Real64.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: Real64_1_0._DeserializerTypeVar_) -> Real64_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "value"
        _f0_ = _des_.fetch_aligned_f64()
        self = Real64_1_0(
            value=_f0_)
        _des_.pad_to_alignment(8)
        assert 64 <= (_des_.consumed_bit_length - _base_offset_) <= 64, \
            'Bad deserialization of uavcan.primitive.scalar.Real64.1.0'
        assert isinstance(self, Real64_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'value=%s' % self.value,
        ])
        return f'uavcan.primitive.scalar.Real64.1.0({_o_0_})'

    _EXTENT_BYTES_ = 8

    _MODEL_: _pydsdl_.StructureType = _dsdl_.CompositeObject._restore_constant_(
        'ABzY8L4#Cb0{?YXU5gw=6rEtk#KaFmf{$^Ybd5S)-yc3mP~4X>Ye+-{2}N~x?Q}s;chg<H&IAMIK`~IEkn;a}duKNrBRkM^)!ci}'
        'z2|aH|917CyYt!UFMibR%Au^6W^lc?wSQ{!+AU4dZn}2x!KL`#<Is;q7<>1_u5;;S`t*5vmJZ_FG<E~=yQ4iRY_sfozwyDJxaCmT'
        '+V;yw&enpZc-@@1e(-IRs#(1D<JtLTT3uPq{z%VLylHF*z0b$shV&#|Hq)!56z7ND)#b%3H%w`RHDMa?vhr8+rTETa-P-V9IyX)3'
        'gQ;D!4pmy+2gt$>!ED;nrRq-n@Zov+RJQyEVh^Se(3t(69;JB448b;~?aSAJ{sf$jT{k|A<<$7Nw?zQ@1FYrn><kz`@hh_#mRbr;'
        'F=a{+in&AzGfpHUR8lMvqg+U>kVNq2ge%6h7F;WhC6hv-sfGw76+%RDs-!?%Y0j0PL<*s#!V+_a*z_;um{CQT0C+|TrbH;E;ffU`'
        'D+Vp#L6lR;vCv8&=!OxOf^$q1K~fOLnMOz>sx&1~%#eg;iX+7!iBb*NQ#VSefGk3YW(o_gkm6iZ=t?NC1&Tmj5kU~cj7cC5!%~=5'
        'Vudu;L~Erm;Rt3&L}0}*VG3}CO4IVkyqd@PiLFQ2@l{i{MT+R#Ev&cREqd4WZg5SQWU%l}aBGm@my4gjAouQZ`uXCs)AtiVvGMk6'
        'QZ)H)FY#xo`lPxwfJDj(tFXb9=|z0s9Q&;+P1p9p_%a>ETV`m-zHktzo#`wHApV+F?Z#z;ufYY`Q)sfy2HUmk?AZ64Uu^HP(6;rE'
        'LC4^mwb|P#>&CqHh3VaTtfz(-3LmoblygaDd&gya$1U*^E%zx22vv4~QF>UwWQY@Axb&hrh_h)^c@0AR_}niSx`oW}<~_xCzxLs~'
        ')B9t%o;fGJW!f&q#bqGFZj-mb1V(w_HZ8bu(){<G>uqTJ3;(@sipqnhD;+<0Xv-2-@xP?%t0{Uk)<AamW)u+i3ivA>tnU9k<nZC?'
        '_CRTMeawOG#y69-;b6DZ;o4+xSnpJQ!?<l{o6~R8(U=eUm@oeYCcRQ;DFpxk'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
